### ISSUE TITLE
implement a sourmash classify command?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1099]
I've been pretty impressed with the performance of gather as revealed by @luizirber and @bluegenes, vs the challenges of getting LCA-based approaches to work nicely.

Maybe it's time to implement a 'classify' command that takes a gather database and a lineages spreadsheet and classifies to the desired rank?

I'm currently only +0 on this. The + and - are described pretty well here --

ref https://github.com/dib-lab/sourmash/issues/969

a few random thoughts --
* with sbts in zip files, this can be really lightweight
* charcoal already does something similar, and it's only a few lines.  could add it there as 'charcoal classify' instead.
* not sure how to explain and/or configure the user experience around "do I use a protein database, or a DNA database?"

still +0, maybe verging on 0... it'd be nice to have as a built in command in some circumstances tho! like lca classify but better.

**Comment by bluegenes** [comment]
+1 from me, as I've been using some of your charcoal / other implementations to do this.

I was thinking it would be nice to optionally enable classification as output of `--multigather` if a lineage file is provided.

**Comment by luizirber** [comment]
(even better if it generates a CAMI profile =])

**Comment by ctb** [comment]
also ref https://github.com/dib-lab/sourmash/issues/984

**Comment by ctb** [comment]
I think with #1543 we ended up going in a different, slightly more complicated, but also more flexible direction. Closing this for now.
