### ISSUE TITLE
use a faster `json` library in `lca/lca_db.py`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1111]
perhaps one reason LCA databases are so slow is that we're using a slow JSON parser - the stdlib one!

ref #948 #909 and oddly #737

**Comment by luizirber** [comment]
> perhaps one reason LCA databases are so slow is that we're using a slow JSON parser - the stdlib one!

`orjson` and `rapidjson` seem to be good drop-in replacements. [`hyperjson`](https://github.com/mre/hyperjson) uses Rust underneath. `rapidjson` is in conda-forge already.
https://pythonspeed.com/articles/faster-json-library/

Or we could implement saving/loading in Rust... =]

**Comment by ctb** [comment]
I suspect that #1808 is going to be the best solution here - simply move to sqlite :)
