### ISSUE TITLE
sourmash compute csv output with metacodeR

### ISSUE THREAD

**Issue by FrAoJm** [sourmash-bio/sourmash#1120]
Hi, 
hope all of you are good. 
I used Sourmash compute with a collection of bacterial isolates in two experiments (1 with only one type of bacteria) and another one with several types of bacterias).
I get the csv files and imported as distance matrix to R. 

I would like to perform a nice plot of them using metacoder, but honestly, have no clue how to star with it. Everything I found is for taxonomical LCA. Should I perform some kind of LCA with my data? 

I would appreciate any help with it!
Thanks!

**Comment by ctb** [comment]
hi @FrAoJm do you have an example of the kind of plot (screenshot, whatever) that you want to produce? metacoder does require taxonomy information so you'd probably want to run a `sourmash lca summarize` on your signatures using the LCA databases downloadable [here](https://sourmash.readthedocs.io/en/latest/databases.html), as in [this tutorial](https://sourmash.readthedocs.io/en/latest/tutorials-lca.html).

Please see https://github.com/grunwaldlab/metacoder/issues/246 for another person who did something similar!

Happy to help, please keep asking questions :)

**Comment by FrAoJm** [comment]
Thank you @ctb! Ideally, the PI would like to produce something like; https://www.microbiologyresearch.org/docserver/ahah/fulltext/mgen/6/4/mgen000347-f1_thmb.gif

But in summary, it would be something with the relationship between strains of the same bacteria. I will try to perform LCA with the databases and follow the tutorial. Then I will try to focus on the relationship only in the branch of my samples.  

I will take a look to grunwaldlab/metacoder#246 to see what they did.

Thank you again! Regards!

**Comment by ctb** [comment]
see code in https://github.com/sourmash-bio/sourmash/issues/2041, and also in STAMPS 2022 tutorial - [here](https://github.com/mblstamps/stamps2022/blob/main/kmers_and_sourmash/README.md#visualizing-gather-based-taxonomy-with-metacoder)
