### ISSUE TITLE
release a new version of screed

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1155]
we're getting these warnings,

```
/Users/t/miniconda3/envs/py37/lib/python3.7/site-packages/screed/screedRecord.py:12
  /Users/t/miniconda3/envs/py37/lib/python3.7/site-packages/screed/screedRecord.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import MutableMapping
```

filing this in sourmash issues because no one is really developing screed any more 😂

**Comment by luizirber** [comment]
Those are not the only ones, there are others popping up: https://travis-ci.com/github/dib-lab/sourmash/jobs/369976114#L1130

**Comment by ctb** [comment]
[screed v1.0.5](https://github.com/dib-lab/screed/releases/tag/v1.0.5) released on feb 2, 2021
