### ISSUE TITLE
Disable Python 3.6 builds in conda-forge and bioconda for 4.0

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#1163]
(save some build time)

**Comment by ctb** [comment]
related #1299 - increment screed version req

**Comment by luizirber** [comment]
Fixed for 3.5.1 in https://github.com/conda-forge/sourmash-minimal-feedstock/pull/12 (also covered 4.0 in https://github.com/conda-forge/sourmash-minimal-feedstock/pull/13)
