### ISSUE TITLE
fix rust `Signature` API for minhashes method.

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1167]
see https://github.com/dib-lab/sourmash/pull/1159#issuecomment-671987255 and follow-on.

**Comment by ctb** [comment]
worked on exposing this error more cleanly --

in `test_sourmash_sketch.py::test_dna_defaults()`, I added the following code at the end:
```
siglist = factory()
sig = siglist[0]
```

then:

```
sig.minhash
```
yields
```
E       sourmash.exceptions.Panic: sourmash panicked: thread 'unnamed' panicked with 'not implemented' at src/core/src/ffi/signature.rs:172
```

---

and
```
minhashes = sig.minhashes()
```
causes a segmentation fault.

**Comment by luizirber** [comment]
For whoever ends up implementing this: rename the `.minhashes` method to `.sketches` instead =]
