### ISSUE TITLE
add information about updating dev environment to dev docs

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1181]
Under "If you’re having trouble installing or using the development environment" in the dev docs, it would be nice to have the right commands for updating.

For rust, this seems to be:

```
rustup update
```

for python, it varies, I think? you would do
```
pip install -e .
```
and/or
```
conda update --all
```
I think?

**Comment by ctb** [comment]
This involves modifications to `doc/developer.md`.

(1) Right now we have the following text in the [release docs](https://sourmash.readthedocs.io/en/latest/release.html) -

>You will also need a Rust installation (see Development Environment); be sure to update it to the latest version with `rustup update`.

This should be modified to "To update rust to the latest version, ...." added to the [developer docs](https://sourmash.readthedocs.io/en/latest/developer.html) under a new heading`, "Updating your developer environment", just above "Running tests and checks".

(2) Also add

>"To update your Python dependencies to the latest required for sourmash, you can run `pip install -r requirements.txt`"

(3) there is also a typo in the current dev docs, 

>Finally, ou can also explicitly install all the Python dependencies for sourmash by running

'ou' should be 'you'.

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
On Thu, Apr 01, 2021 at 03:03:46PM -0700, Keya Barve wrote:
> @ctb Can I work on this issue?

sure! I'd suggest picking one issue, and then getting a PR together and
ready for review before taking another issue, tho.

**Comment by keyabarve** [comment]
@ctb I have added a new heading called "Updating your developer environment" just above "Running tests and checks" in `doc/developer.md` and added the commands for updating Rust and Python.
Additionally for (1), should the text "You will also need a Rust installation..." be removed from `doc/release.md`?
