### ISSUE TITLE
How deduce --scaled factor from signature metadata

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1184]
Say I get a signature w/o knowing the underlying genome, how do I determine which scaling factor was used? Ie it says `n: 0` in the metadata, but how to determine if eg `--scaled 1000` or `--scaled 10000` was used? Or can I divide the maximum possible integer (what is it?) by `max_hash` to get at this?

Thanks!

**Comment by ctb** [comment]
On Tue, Aug 25, 2020 at 12:35:47AM -0700, Adrian Viehweger wrote:
> Say I get a signature w/o knowing the underlying genome, how do I determine which scaling factor was used? Ie it says `n: 0` in the metadata, but how to determine if eg `--scaled 1000` or `--scaled 10000` was used? Or can I divide the maximum possible integer (what is it?) by `max_hash` to get at this?

Hmm, do any of these do what you want?

* the minhash object has a scaled property
* sourmash sig describe will give you the scaled value
* if you only have max_hash, sourmash._minhash.get_scaled_for_max_hash(max_hash) will give you the corresponding scaled

best,
--titus

**Comment by phiweger** [comment]
> sourmash sig describe will give you the scaled value

Uh, I didn't know about this! Thanks for the quick response Titus.

Kind regards

**Comment by ctb** [comment]
+1
