### ISSUE TITLE
How should users prepare signatures for large scale metagenome search?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1192]
hi @luizirber re [your blog post on massive scale search](https://blog.luizirber.org/2020/07/22/mag-search/),

what is your directive to people who would like to prepare genome signatures for this kind of search?

I'm guessing:

```
sourmash compute -k 31 --scaled=1000 --name IDENTIFIER genome.fa
```
but would love confirmation of ksize and scaled, or anything else I've forgotten!

thx

**Comment by luizirber** [comment]
These are the [parameters used](https://github.com/dib-lab/wort/blob/9e3c247d45b7af866923d2ec5213f04504de7cd5/wort/blueprints/compute/tasks.py#L42L46) for the metagenomes, so this would generate sigs supported with any of the parameters:

`sourmash compute -k 21,31,51 --scaled 1000 --track-abundance --name IDENTIFIER genome.fa`

(`--track-abundance` and multiple `-k` will make largers sigs, but might be useful for downstream analysis)

**Comment by ctb** [comment]
thanks @luizirber
