### ISSUE TITLE
UnboundLocalError with empty fastq file

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#1194]
I know I'm using an ancient version of sourmash, but is this expected behavior with empty fasta files?
If it is expected behvarior, is it possible to have sourmash exit instead of fail, perhaps with a message like,
`Nucleotide file is empty. Exiting.`

```
^MESC[K== This is sourmash version 3.0.1. ==
^MESC[K== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

^MESC[Ksetting num_hashes to 0 because --scaled is set
^MESC[Kcomputing signatures for files: outputs/sgc_genome_queries_singlem_reads/bgi-MH0027_singlem_reads.fq
^MESC[KComputing signature for ksizes: [31]
^MESC[KComputing only nucleotide (and not protein) signatures.
^MESC[KComputing a total of 1 signature(s).
^MESC[KTracking abundance of input k-mers.
^MESC[K... reading sequences from outputs/sgc_genome_queries_singlem_reads/bgi-MH0027_singlem_reads.fq
Traceback (most recent call last):
  File "/home/tereiter/github/2020-ibd/.snakemake/conda/69e99623/bin/sourmash", line 11, in <module>
    sys.exit(main())
  File "/home/tereiter/github/2020-ibd/.snakemake/conda/69e99623/lib/python3.7/site-packages/sourmash/__main__
.py", line 83, in main
    cmd(sys.argv[2:])
  File "/home/tereiter/github/2020-ibd/.snakemake/conda/69e99623/lib/python3.7/site-packages/sourmash/command_
compute.py", line 345, in compute
    notify('...{} {} sequences', filename, n, end='')
UnboundLocalError: local variable 'n' referenced before assignment
```

I searched issues and couldn't find this error message anywhere, sorry if this has already been taken care of in more recent versions of sourmash!

ls on my file looks like this:
```
-rw-r--r-- 1 tereiter tereiter 0 Sep  4 19:21 outputs/sgc_genome_queries_singlem_reads/bgi-MH0027_singlem_reads.fq
```

**Comment by ctb** [comment]
good catch, I know exactly what's happening.

**Comment by ctb** [comment]
around line 219 in `sourmash/command_compute.py`, there is a for loop:
```
            name = None
            for n, record in enumerate(screed.open(filename)):
                if n % 10000 == 0:
                    if n:
                        notify('\r...{} {}', filename, n, end='')
                    elif args.name_from_first:
                        name = record.name
```
here, `n` needs to be initialized to `0` before entering the for loop, because if the loop code isn't executed at all (e.g. for an empty file) then n isn't ever set.

I would suggest starting by adding an automated test into `tests/test_sourmash_compute.py` that tries to compute on an empty file. You might copy `test_do_sourmash_compute_output_and_name_valid_file_outdir` into a new test name and edit that, for example.

There are actually several places in the `command_compute` code where this should be tested, and then fixed.

**Comment by ctb** [comment]
it looks like this was fixed in https://github.com/dib-lab/sourmash/pull/1347 - see changes to `command_compute` - but never tested. I'll create a new issue about that.

**Comment by ctb** [comment]
whups! the following tests fail when the bug is reintroduced -

```
FAILED tests/test_sourmash_sketch.py::test_do_sourmash_sketchdna_noinput - Va...
FAILED tests/test_sourmash_sketch.py::test_do_sourmash_sketchdna_noinput_singleton
FAILED tests/test_sourmash_sketch.py::test_do_sourmash_sketchdna_noinput_merge
```

so this issue was just left open by mistake. My apologies!
