### ISSUE TITLE
How appropriate are signatures to compare _very_ similar genomes

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1195]
Use case: Bacterial outbreak tracing.

I filter genomes using minhash to reduce the set that is subsequently modelled as outbreak (the "transmission tree").

I was surprised to learn that some genomes (hereafter "query") that seemed quite close to my reference (hereafter "reference" ;) were not included that way.

So I compared the results (sourmash compare, -k 51 --scaled 1000) with [FastANI](https://github.com/ParBLiSS/FastANI):

| comparison | sourmash | fastani
| --- | --- | --- |
| reference vs. query | 0.957 | 0.999881 |
| reference vs. query, containment reference in query | 0.986 | - |
| reference vs. query, containment query in reference | 0.906 | - |
| reference (chromosome only) vs. query | 0.97 | 0.999355 |
| reference (chromosome only) vs. query, containment reference in query | 0.974 | - |
| reference (chromosome only) vs. query, containment query in reference | 0.928 | - |

Is this maybe some kind of "saturation phenomenon" that is happening to the minhash comparisons?

Kind regards

**Comment by nmb85** [comment]
@phiweger I'm just curious, what does changing the `--scaled` argument to 100 or 10 do to your estimated sourmash distance?

**Comment by phiweger** [comment]
reference vs. query --scaled 10: 0.957 -> 0.955, ie not much.

**Comment by ctb** [comment]
hi @phiweger interesting observation - one (slightly paranoid) thought is, ANI is a different computation than Jaccard similarity. ANI takes into account only those regions that are alignable, whereas Jaccard similarity takes into account differences as well, via the size of union of k-mers on the denominator of the equation. It might be worth checking that there are not chunks of unalignable sequence in one or the other.

**Comment by phiweger** [comment]
you mean like a large plasmid in one but not the other?

**Comment by ctb** [comment]
On Wed, Sep 09, 2020 at 07:48:08AM -0700, Adrian Viehweger wrote:
> you mean like a large plasmid in one but not the other?

yep! or accessory elements.

**Comment by phiweger** [comment]
ah that might explain it -- I did not realize that ANI is for "mapped fragments" only, discarding the rest. thanks @ctb !
