### ISSUE TITLE
sourmash index ... --from-file not working?

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1196]
Running sourmash v3.5.0

```bash
sourmash index -k 31 --from-file sketches.txt index.sbt.zip 
sourmash index -k 31 index.sbt.zip --from-file sketches.txt
```

both yields

```bash
index: error: the following arguments are required: signatures
```

Am I using `--from-file` correctly?

**Comment by bluegenes** [comment]
Hi @phiweger! Unfortunately, index `--from-file` requires at least one signature passed in via command line. We've fixed this for a future major release (4.x), but it can't be integrated into 3.x versions without breaking other uses.

**Comment by ctb** [comment]
right, it would break backwards compatibility. see https://github.com/dib-lab/sourmash/issues/1066. Sorry :(

**Comment by phiweger** [comment]
\*sob\* ;)
