### ISSUE TITLE
Missing data in genome comparisons 

### ISSUE THREAD

**Issue by adc0032** [sourmash-bio/sourmash#1205]
Hi!!
Thank you for the software!

I actually have a question, and not so much an issue. 
I wanted to get an idea of genetic distance between a reference assembly and two strains of a sister species that were assembled using the reference sequence previously mentioned. 

I may be missing something fundamental about how this analysis is performed, but how are N's or masked regions handled during this process?

**Comment by ctb** [comment]
hi @adc0032! any non-ACGT k-mer is ignored completely, so those regions wouldn't show up in the analysis at all.

happy to expand on what this means if you have questions!

anticipating one question by a little bit, note that sourmash (well, and any Jaccard similarity based comparison) 
doesn't do anything with contiguity or structural content - it decomposes the input data into overlapping k-mers, discarding any and all information about which regions are where. so it's a pure "word content" analysis, and sourmash in particular ignores words containing Ns.

you might be particularly interested in the results of `sourmash sig overlap` which will give you the gory details of numbers shared between two input signatures.

**Comment by adc0032** [comment]
@ctb Thank you so very much!!!
