### ISSUE TITLE
Expose a function to produce a list of all hashes from a sequence

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#1214]
Currently there is no way to retrieve in Python the list of hashes generated for a sequence. This could be refactored out of `add_sequence` in Rust and returned to Python.

(This would probably be useful when testing new sequencing encodings)

Relevant issues:
- https://github.com/dib-lab/sourmash/issues/1057 moving add_sequence to SigsTrait, implemented in ~#1201~ #1223 )
- https://github.com/dib-lab/sourmash/issues/483#issuecomment-523611249: this issue could make "hash to k-mer" easier to implement
  * https://github.com/dib-lab/sourmash/pull/477 modified the `compute` command, but this method could be executed without necessarily making the compute command more complicated.

**Comment by ctb** [comment]
Just to confirm, this would allow fast protein and translated hashing, right? [I have a specific use for that :)](https://github.com/spacegraphcats/spacegraphcats/issues/293#issuecomment-729440090)

**Comment by ctb** [comment]
I was looking into this because of https://github.com/dib-lab/sourmash/issues/1372, and ...I am now confused.

#1201 is mentioned above as resolving https://github.com/dib-lab/sourmash/issues/1057, but I don't see it in the code there.

@luizirber could you update with what needs to be done for this issue? thank you!

**Comment by luizirber** [comment]
Oops, I updated #1057 to point to #1223, because I moved the HLL code in #1201.

**Comment by ctb** [comment]
ok, so for this issue we can modify add_sequence to return the hashes?

**Comment by luizirber** [comment]
I don't think we should modify, but instead create a new one (and refactor common parts out of `add_sequence`?).

I don't think the goal here is returning hashes every time `.add_sequence` is called, but instead having a function that return all the hashes for a sequence (even if they are not added to the sketch).

**Comment by ctb** [comment]
@erikyoung85 this would be another nice project for you :)
