### ISSUE TITLE
How to get all the genomes of 0 similarity after sourmash compare

### ISSUE THREAD

**Issue by polinanvkv** [sourmash-bio/sourmash#1251]
Hello, 

firstly, thanks for your useful tool! I have a quick question about its usage. My final goal is to compare 4k bacterial/archaeal genomes and discard those which are same. For that I run `compute`, `index` and `compare` following the tutorial.  As a result of `sourmash compare`  there's a huge `out.csv` matrix which I need to process to retrieve those genomes which have a score of 0 in the intersection. It could be realised with a python script for example, but I was hoping for a ready-made solution :P  Maybe I misunderstood the documentation, but I didn't find anything for my problem. Could you please comment on that? Many thanks in advance!

**Comment by ctb** [comment]
hi @polinanvkv hmm, I can't actually think of a good way to get at this!

To make sure I understand - 
* you have N genomes
* you build a compare matrix

and now you want to do what --

1. extract any genome that has no similarity with any other genomes?

or

2. extract all genomes that have no similarity with at least one other genome?

or

3. extract all pairs of genomes that have no similarity with each other?

these would all have different solutions ... thanks!

**Comment by polinanvkv** [comment]
hello @ctb ! thanks for specifying my own question. I guess I am speaking about statement #1. 

Let me explain my problem: imagine I downloaded 1000 genomes from different sources. Therefore, I expect that some of them might be identical in my collection (let's say in total there are 200 similar genomes), i.e. I've got a redundant dataset. I want to make it non-redundant, so I compare my genomes using sourmash, and want to keep only those which are unique and are not similar to anything else in the dataset. So I want to keep only those 800 non-redundant genomes and exclude the 200 similar ones.

Hope I made it clearer :)

**Comment by ctb** [comment]
ok, thanks!

when I've encountered this problem before (e.g. Shawn Higdon's work, https://pubmed.ncbi.nlm.nih.gov/32986754/) the goal was to keep a single representative genome from each cluster.  Is that what you want, or do you only want genomes for which there is no duplication?

---

If you want a single representative genome from each cluster, I had already posted some clustering work with sourmash output here,

https://github.com/ctb/2017-sourmash-cluster

and I wrote up some code for shawn that randomly selected from a cluster. I could revisit that and give you some clean code sometime this week if you're interested.

**Comment by polinanvkv** [comment]
hello again @ctb ! yes, if possible I would like to be able to extract both single representatives from each cluster +  the non-duplicated genomes. Would be great if this feature would be implemented in sourmash, I guess many people are going to be interested!

**Comment by polinanvkv** [comment]
Hello @ctb ! While waiting, I tried to make up my own decent solution, and I came up with a dirty and quick way to extract only the non-duplicated genomes. I suppose if I set a custom threshold for similarity, say 0.2, and in the similarity matrix just remove the lines where there are any values >0.2, I will be able to extract the non-duplicated genomes, by taking genomes corresponding to lines which remain in the matrix. Right? I’m still stuck with the cluster representatives though. I had a look at sources you posted but it‘s rather difficult to get to it without the context.

**Comment by ctb** [comment]
hi @polinanvkv check out

https://gist.github.com/ctb/85fe2efb23b70bbd72ea6a69750d1284

and let me know if it works for you!

ref https://github.com/dib-lab/sourmash/issues/1251

**Comment by ctb** [comment]
p.s. thanks for asking, this ended up making me think about how to do it better/less confusingly, and I think it worked out really nicely!

**Comment by ctb** [comment]
I'm going to close this for now - please let us know if you have any further questions!
