### ISSUE TITLE
revisit default sketch sizes for protein

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#1259]
Current defaults:

```
    dna='k=31,scaled=1000,noabund',
    protein='k=10,scaled=200,noabund',
    dayhoff='k=16,scaled=200,noabund',
    hp='k=42,scaled=200,noabund'
```

I'd like to propose making the default `scaled=100` for all protein alphabets. It seems to be working well for the things I've been doing, and is ...simpler than 200?

**Comment by bluegenes** [comment]
Given @ctb's trials with metagenomes, perhaps we should think about revising protein `scaled` in the opposite direction -- e.g. `scaled=1000`

**Comment by ctb** [comment]
from slack --

@bluegenes - 
>I guess I was thinking that scaled=100 might be more versatile — seems to produce a number of hashes for viruses, and had good resolution for gtdb things. But based on metagenomes titus was running, scaled=100 was way too slow and scaled=1000 seemed to work well! So I think my use cases don’t represent the range of things we want to do!

me:
>10:34 AM
re tessa’s comment, it is not likely that functional searches will work at scaled=1000
10:34 AM
so …maybe we should compare sketching speed and data volumes for a real metagenome
10:34 AM
I’ll do that and get back ta ya

**Comment by ctb** [comment]
ok, finally did some of this.

SRR606249 is 28 GB -
```
% ls -la abundtrim/
28,463,275,968 SRR606249.abundtrim.fq.gz
```
(note, despite the .fq.gz, this is an uncompressed file 😬 )

Made protein sig with scaled=100:
```
% sourmash sketch translate abundtrim/SRR606249.abundtrim.fq.gz -o SRR606249.protein.scaled=100.sig -p k=21,k=31,k=51,scaled=100
...
% ls -la SRR606249.protein.scaled=100.sig
196,799,057
```
196 MB output file.

```
% /usr/bin/time -v sourmash sig downsample --scaled=1000 SRR606249.protein.scaled\=100.sig -o SRR606249.protein.scaled\=1000.sig

== This is sourmash version 4.0.0a1. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 3 sigs from 'SRR606249.protein.scaled=100.sig'
loaded and downsampled 3 signatures
        Command being timed: "sourmash sig downsample --scaled=1000 SRR606249.protein.scaled=100.sig -o SRR606249.protein.scaled=1000.sig"
        User time (seconds): 4.43
        System time (seconds): 0.42
        Percent of CPU this job got: 95%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:05.10
        Maximum resident set size (kbytes): 473628
```
so 5 seconds and 473 MB of RAM to downsample.

```
% ls -lh
total 152M
drwxrwxr-x 2 ctbrown ctbrown    3 Jan  1 19:34  abundtrim
drwxrwxr-x 2 ctbrown ctbrown    9 Jan  2 07:01  genbank
drwxrwxr-x 2 ctbrown ctbrown    3 Jan  1 20:15  sigs
-rw-rw-r-- 1 ctbrown ctbrown  18M Feb  2 07:05 'SRR606249.protein.scaled=1000.sig'
-rw-rw-r-- 1 ctbrown ctbrown 188M Feb  2 07:04 'SRR606249.protein.scaled=100.sig'
```

```
% ls -lh
total 85M
drwxrwxr-x 2 ctbrown ctbrown    3 Jan  1 19:34  abundtrim
drwxrwxr-x 2 ctbrown ctbrown    9 Jan  2 07:01  genbank
drwxrwxr-x 2 ctbrown ctbrown    3 Jan  1 20:15  sigs
-rw-rw-r-- 1 ctbrown ctbrown 7.6M Feb  2 07:05 'SRR606249.protein.scaled=1000.sig.gz'
-rw-rw-r-- 1 ctbrown ctbrown  77M Feb  2 07:04 'SRR606249.protein.scaled=100.sig.gz'
```

## conclusions

as expected, 10x bigger on disk. compressed is probably good, but with our current storage approach there's only so much you can do. is there a nice, simple, well supported binary format we can use?

loading and downsampling time is kind of minimal.

I think keeping defaults at 100 or 200 is probably fine, but if we do metagenomes in bulk, a scaled of 1000 is probably appropriate unless we decide to look into improving disk space storage size more specifically.

**Comment by ctb** [comment]
I'm going to close this for now.
