### ISSUE TITLE
Add downsampling to select_sketch in rust

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#1292]
Currently `sig.select_sketch` in Rust only return sketches that match exactly a template. But... If there is a `scaled=10` sketch and the template is `scaled=100`, the sketch can be downsampled.

There is some code to do that in https://github.com/luizirber/2021-01-27-olga-remove-protein/commit/e9603f36e8e57488a490767056a44f071af1026c, but this triggers copies all the time. Might need to think better (maybe an extra parameter, `downsample`?) on how to control this behavior.

**Comment by ctb** [comment]
@luizirber I think this is being resolved in your new rust work, yes?

**Comment by luizirber** [comment]
This wasn't quite covered in #2230. Exposing the `Select` trait was done, but the selecion is not doing the downsampling. [This is the place that needs](https://github.com/sourmash-bio/sourmash/blob/e47c18cd9ce408ade44df4baacbfedf251184848/src/core/src/storage.rs#L437L438):
1) proper error handling (not a generic MismatchKSizes!)
2) do the downsampling, based on the selection

cc @bluegenes

**Comment by bluegenes** [comment]
@luizirber - how would you suggest better handling the error? 

Separately, do we also need to modify `select_sketch` for query downsampling (and allow downsampling within `mh.check_compatible`?

**Comment by luizirber** [comment]
> @luizirber - how would you suggest better handling the error?

Returning an empty sig as in #2931 sounds good!
 
> Separately, do we also need to modify `select_sketch` for query downsampling (and allow downsampling within `mh.check_compatible`?

`select_sketch` should be deprecated and removed 🙃 
and base everything on top of the `Select` trait instead.
So, I would say no need to fix it.

**Comment by bluegenes** [comment]
Closing after merging #2931!
