### ISSUE TITLE
resolve sourmash deprecation warnings for 4.0 release

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1296]
the tests currently spit out a LOT of warnings. fixme.

**Comment by luizirber** [comment]
Turns out new ones appeared, related to [`load_signatures`/`load_file_as_signatures`](https://github.com/dib-lab/sourmash/runs/1835248045#step:12:53). Reopening.

**Comment by ctb** [comment]
I found running `py.test -Werror` to be useful in cleaning up the new ones. Do you think we should enable that by default in the testing?

**Comment by luizirber** [comment]
> I found running `py.test -Werror` to be useful in cleaning up the new ones. Do you think we should enable that by default in the testing?

Yup! It might be a bit scary for new people, tho. One solution would be enabling only in CI (like we do with `PYTHONDEVMODE`), but that might be even more confusing ("why does it pass locally, but fail in the PR checks?")

**Comment by ctb** [comment]
agreed. for now, I'll just keep an eye on it for future PRs.
