### ISSUE TITLE
increment conda packaging requirements for screed

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1299]
with the release of screed v1.0.5, which resolves some deprecation warnings, we need to update the conda package for sourmash-minimal I think.

**Comment by ctb** [comment]
note screed v1.0.5 is available on conda-forge:
```
screed                         1.0.5    pyhd8ed1ab_0  conda-forge
```

**Comment by luizirber** [comment]
Fixed in https://github.com/conda-forge/sourmash-minimal-feedstock/pull/13
