### ISSUE TITLE
Questions and concerns for 4.0.0rc1

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1338]
please add comments below if you have questions or concerns about [sourmash v4.0 release candidate 1](https://github.com/dib-lab/sourmash/releases/tag/v4.0.0rc1)

See also comments [on twitter thread](https://twitter.com/ctitusbrown/status/1362750039613841409)

**Comment by klamens** [comment]
'accept file list in sourmash sig cat (#1236)' - Could we also have it for the sketch function (input fasta files)?

**Comment by ctb** [comment]
On Thu, Feb 18, 2021 at 02:29:28AM -0800, klamens wrote:
> 'accept file list in sourmash sig cat (#1236)' - Could we also have it for the sketch function (input fasta files)?

well THAT's a brilliant idea! *laugh* yes :)

**Comment by klamens** [comment]
> On Thu, Feb 18, 2021 at 02:29:28AM -0800, klamens wrote: 'accept file list in sourmash sig cat (#1236)' - Could we also have it for the sketch function (input fasta files)?
> well THAT's a brilliant idea! *laugh* yes :)

On Windows there is a max number of characters for the command line - VERY annoying when we have a lot of input files. A file list would help a lot! Tnx!!

**Comment by ctb** [comment]
👍  - also happy to drop you some snakemake Snakefiles that do this for you, which is what we use - enables parallelism! - but this is a great feature idea :)

**Comment by ctb** [comment]
per Mick - https://twitter.com/BioMickWatson/status/1362753564381175814 - how about updated database etc?

**Comment by ctb** [comment]
@klamens please see https://github.com/dib-lab/sourmash/pull/1362 for `--from-file`.

**Comment by ctb** [comment]
@klamens the new feature (`--from-file` on `sourmash sketch`) will be released in the next version of sourmash, along with other recent changes. We don't have a firm date for that release but it will be sourmash v4.1.0, probably by end of April.

If you want to try it out before then and need our help, please let us know!

**Comment by ctb** [comment]
done!
