### ISSUE TITLE
support deletion of hashes by setting abundance to 0?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1355]
So https://github.com/dib-lab/sourmash/pull/1046 added a `clear` option to `set_abundances`, but setting abundances to zero doesn't delete the hash, which seems nonintuitive.

code:
```python
import sourmash
mh = sourmash.minhash.MinHash(n=0, ksize=31, scaled=1, track_abundance=True)

d = { 1: 5, 2: 3 }
mh.set_abundances(d)
print(dict(mh.hashes))

e = { 1: 0 }
mh.set_abundances(e, clear=False)
print(dict(mh.hashes))
```
yields
```
{1: 5, 2: 3}
{1: 5, 2: 3}
```

also what happens if there are negatives? you get an overflow error, which is ok but not intuitive :).

**Comment by bryshalm** [comment]
Where is sourmash is this?

**Comment by ctb** [comment]
the `MinHash` class is defined in `src/sourmash/minhash.py`, and then the Rust code is ...elsewhere :). This is probably a good first issue only if you already know rust!

**Comment by mr-eyes** [comment]
Please correct me if I'm wrong. Here's my understanding of this issue:

- If `clear=False`, then add the abundance values to the old ones.
- Expected behavior: Same as current but remove the whole hash if the abundance is set to `<= 0`.
