### ISSUE TITLE
Extracting k-mers from signatures still possible?

### ISSUE THREAD

**Issue by Glfrey** [sourmash-bio/sourmash#1372]
Hi!

I can see in the past there's been a script to convert signatures generated by sourmash back to their respective k-mers which was located in utils directory, but in the current github utils directory the 'signature-to-kmers.py'  is no longer there.  Is there some way I can still do this or has this been dropped? I'm using sourmash4.0 if that helps.

**Comment by ctb** [comment]
hi @Glfrey please see https://github.com/dib-lab/sourmash/pull/724/ - if this works for you, please do let me know!

**Comment by ctb** [comment]
This command worked for me, in 4.0 -
```
utils/signature-to-kmers.py data/GCF_000005845.2_ASM584v2_genomic.fna.sig data/GCF_000005845.2_ASM584v2_genomic.fna.gz --output-kmers xyz --output-sequences xxx
```

**Comment by Glfrey** [comment]
Hi @ctb, thank you so much for your rapid reply. Trying the command that worked for you returned 'utils/signature-to-kmers.py: No such file or directory' and just copying and pasting the "signature-to-kmers.py" into a file and running it returned 'from sourmash._minhash import hash_murmur ModuleNotFoundError: No module named 'sourmash._minhash'. I installed sourmash using conda, should I be going about this differently?

**Comment by ctb** [comment]
hi @Glfrey, ahh, sorry ;).

The code in that PR is not yet available through any sourmash distribution - it's an unmerged change request (pull request, or PR). If you don't want to go through the hassle of installing sourmash in developer mode, which would be a chore, you can go grab the script directly from https://github.com/dib-lab/sourmash/blob/add/hashes_to_kmer/utils/signature-to-kmers.py and run it, by doing something like this:

```
curl -L -O https://raw.githubusercontent.com/dib-lab/sourmash/add/hashes_to_kmer/utils/signature-to-kmers.py
chmod +x signature-to-kmers.py
./signature-to-kmers.py
```
and that should work. Let me know if it doesn't!

**Comment by Glfrey** [comment]
@ctb thank you so much, it's running now. I'll let you know how it goes. Is it normal for it to take a little while? My signature file is 375B and the compressed genome file is 168M.

**Comment by ctb** [comment]
yes, this is not a terribly optimized solution ;). We are planning to fix that (see the commentary in the PR for details).

**Comment by Glfrey** [comment]
Brilliant thank you, I just wanted to make sure so I know to leave it for a while. I'll let you know it it goes, thank you so much for your rapid help, it's greatly appreciated as I'm on a bit of a sourmash binge with a bunch of genomes at the moment. It's an awesome program, I'm so impressed by how quickly it churns out results given the massive size of the genomes I'm working with.

**Comment by ctb** [comment]
That's wonderful to hear! Let us know how it goes!

**Comment by Glfrey** [comment]
Hi @ctb, unfortunately it didn't work. The program returned "read 594102056bp, found 0 kmers matching hashvals". I've confirmed I fed the program the same genome file the signatures were generated with and I'm currently in the process of trying it out with a different set of signatures to see if I get any success.

**Comment by ctb** [comment]
hmm, that is a bummer.  I double checked the code to make sure it wasn't some obvious-to-me error and I still don't see the bug, but I'm sure it's there :).

Maybe try on some smaller sequences so it's faster to iterate? If you can send me some sequences and the signatures (titus@idyll.org) I can give it a try, too.

hrm, I also have some ideas for double checking - I could have the script produce a signature for the sequences, too, and that would be something you can compare directly.

**Comment by Glfrey** [comment]
Hi @ctb, if you wouldn't mind also trying it out that would be fab. I got the same result with a different dataset so I'm redoing the signatures for a couple of the smallest datasets at a few different k-mer values and I'll send them on once I've got them. The idea about having the script produce a signature for the sequences sounds good, I assume the signatures should match completely between the signature file and what the script produces?

**Comment by ctb** [comment]
hi @Glfrey thanks, I got your e-mail and tried running things - with, I think, success! See output at bottom.

I updated the signature-to-kmers script over in #724 in a few ways -
* more informative & incremental reporting while running
* calculates Jaccard similarity and containment of found k-mers vs input signatures
* does some other validation

so you should redo the curl etc etc to get the new script.

## output

I'll send you the output file by e-mail.

```
% ../utils/signature-to-kmers.py Triticum_stivum.IWGSC.dna.chromosome.1D_k31.fa.gz.sig Triticum_aestivum.IWGSC.dna.chromosome.1D.fa.gz  --output-kmers k-31.csv
loaded signature from 'Triticum_aestivum.IWGSC.dna.chromosome.1D_k31.fa.gz.sig'; ksize=31
^R. Triticum_aestivum.IW read 149800 kb / found kmers:83669/242525
^R. Triticum_aestivum.IW read 187000 kb / found kmers:101654/242525
done reading sequences!
read 495606760 bp, found 242525 kmers matching hashvals
jaccard similarity between query and found k-mers is 1.0
jaccard containment of found k-mers by query is 1.0
jaccard containment of query by found k-mers is 1.0
```

**Comment by ctb** [comment]
report back is that it works, huzzah!

now, to speed it up with https://github.com/dib-lab/sourmash/issues/1214...

**Comment by ctb** [comment]
see https://github.com/sourmash-bio/sourmash/pull/1695
