### ISSUE TITLE
Mismatch in default parameters between `sourmash sketch` and `sourmash compute`

### ISSUE THREAD

**Issue by camillescott** [sourmash-bio/sourmash#1385]
In 4.0, `sourmash compute` uses a default of `num=500`, while `sourmash sketch` uses `scaled=1000` as the default. This could be confusing to users upgrading to 4.0, and is not documented under the `--help` output. I would suggest that either:

* The default parameters be reported when running `sourmash sketch dna --help`
* The diagnostic output reports the parameters being used under the hood
* The `--help` output links to https://sourmash.readthedocs.io/en/latest/sourmash-sketch.html#default-parameters

**Comment by ctb** [comment]
Absolutely. I especially love the point that the default parameters should be in the `--help` docs, thanks!
