### ISSUE TITLE
update tests to use `runtmp` fixture instead of `utils.TempDirectory()`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1386]
(This is a "repeatable quest" issue that involves many small changes; it's good for people looking for a good first issue, or second issue, to go through our contribution pipeline.)

Many of our tests under `tests/` use the following syntax to place things in a temporary directory that will get cleaned up at the end of the test run:

```
def test_plot_override_labeltext():
    with utils.TempDirectory() as location:
        ...
        status, out, err = utils.runscript('sourmash', ..., in_directory=location)
```

This can be replaced with the newer, cleaner and more concise (less indentation!) syntax:

```
@utils.in_tempdir
def test_plot_override_labeltext(c):
    c.run_sourmash('...')
   status, out, err = c.last_result.status, c.last_result.out, c.last_result.err
```

For this repeatable quest, please refactor any three tests to use the newer syntax.

**Comment by Pranavug** [comment]
@ctb can I take up this issue? I think I can give it a shot.

**Comment by ctb** [comment]
of course! please just indicate which three tests you're planning to update!

**Comment by Pranavug** [comment]
Thanks, @ctb ! I am planning to work on the following tests: test_cmd_signature.py, test_sourmash_compute.py and test_sourmash_sketch.py. Will send a PR soon.

**Comment by ctb** [comment]
hi @Pranavug please pick three test _functions_ only, not three test files - thanks :). (It's a big and boring job otherwise!)

**Comment by Pranavug** [comment]
Thanks for clarifying!
@ctb I have created a PR. Please take a look here: [#1443](https://github.com/dib-lab/sourmash/pull/1443).

I have made changes to the following functions in the file `tests/test_sourmash_compute.py:`

1. test_do_sourmash_compute
2. test_do_sourmash_compute_outdir
3. test_do_sourmash_compute_output_valid_file
4. test_do_sourmash_compute_output_stdout_valid

**Comment by ctb** [comment]
thanks! I'll take a look!

(Note that you can just put the issue/PR number #1443 or the full URL https://github.com/dib-lab/sourmash/pull/1443, you don't need to turn it into a Markdown link - although it works just fine if you do!)

**Comment by ctb** [comment]
note that as of #1487, you can and should no longer use `@utils.in_tempdir` and should instead `runtmp` as per https://github.com/dib-lab/sourmash/pull/1487/files#diff-9191b251a88574cc364ff4d5d63f7a56311821f3febba3a7f83a0f1edb9d3763R862 - for extra bonus points, after your first successful PR using that, create a new issue with new instructions, and close this one :)

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
sure! note change in title and the last comment I made about using runtmp, instead.
