### ISSUE TITLE
ID not displayed w/ sourmash lca classify v4 on premade database, v3 works

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1394]
I sketched some genomes using v4:

```
find SGB_genome_fastas_part1 -name '*.fa' -not -path '*/\.*' | parallel -j8  sourmash sketch dna -p k=21,k=31,k=51,scaled=1000 --outdir sigs_1 {}
```

Then I ran `sourmash lca classify ...` (v4) using [this](https://osf.io/gs29b/) premade database, and the ID column in the result was missing.

Reverting back to v3 solved the problem.

**Comment by ctb** [comment]
If you get a chance to share the output of `sourmash lca classify` from 4.0, I'd appreciate it - but I should be able to take a look in the next day or two, thanks for making sure v3 is good!

**Comment by phiweger** [comment]
It's really just missing a value in the first column, ie "ID" exists as column name, but all first fields in the subsequent rows are empty.

**Comment by ctb** [comment]
Gotcha. Looks like this is a consequence of https://github.com/dib-lab/sourmash/pull/1179 and https://github.com/dib-lab/sourmash/pull/1232. I think the same resolution as in #1232 is appropriate here, in which we switch from `sig.name` to `str(sig)`.

**Comment by ctb** [comment]
An alternative would be for @phiweger to specify a name for his signatures with `--name` when creating them ;).
