### ISSUE TITLE
should we change `latest` branch to `main`?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1412]
this seems to be new/default/suggested behavior for both `git` and `github` --

* https://github.com/github/renaming
* https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/

**Comment by luizirber** [comment]
It doesn't really affect contributors cloning the repo (because `git` knows that `latest` is our default branch), so I don't think we need to go the trouble of changing names again (and updating docs, and CI, and downstream recipes in bioconda/conda-forge...)

**Comment by ctb** [comment]
k.
