### ISSUE TITLE
check lca database error text

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1415]
In `src/sourmash/lca/lca_db.py`, the `LCA_Database.load(...)` class method checks to make sure that the filename is a directory, and if it is not, it raises a `ValueError` with the following string: `"'{db_name}' is not a file and cannot be loaded as an LCA database"`. Currently this string is not checked for in the relevant tests.

Add a check for this string value in `tests/test_lca.py` functions `test_databases_load_fail_on_dir` and `test_databases_load_fail_on_not_exist` by looking at `str(exc.value)` after the `pytest.raises` block.

**Comment by keyabarve** [comment]
@ctb Can I try working on this issue? I'm a little unclear on what exactly needs to be done.

**Comment by ctb** [comment]
go for it!

this is the key instruction:
>Add a check for this string value in `tests/test_lca.py` functions `test_databases_load_fail_on_dir` and `test_databases_load_fail_on_not_exist` by looking at `str(exc.value)` after the `pytest.raises` block.

For an example of us doing something similar to this, see `test_gather_error_no_sigs_traverse()` in `tests/test_sourmash.py` - the assert statements at the bottom are basically what you want to do here, suitably modified.

**Comment by ctb** [comment]
note that you can run _just_ the two tests you are working on by doing `py.test tests -k test_databases_load_fail_on_dir`.

**Comment by keyabarve** [comment]
Will try, thanks!

**Comment by keyabarve** [comment]
@ctb I can't seem to find the functions ```test_databases_load_fail_on_dir``` and ```test_databases_load_fail_on_not_exist``` in ```tests/test_lca.py```. Do I need to create these functions?

**Comment by ctb** [comment]
argh, I think they're buried in some pull request, actually. I'll go find them and report back :)

**Comment by ctb** [comment]
ahh! they are here, https://github.com/dib-lab/sourmash/pull/1406.

if you want to work on this, you can! You will need to start from branch `refactor/db_load_multiindex` instead of `latest`, and then set up the pull request into that branch (instead of latest).

Alternatively, you could wait until #1406 is merged :).

apologies for the confusion!

**Comment by ctb** [comment]
whups, well, #1406 is merged - so you should be able to update to `latest` and see the functions!

**Comment by keyabarve** [comment]
Alright, thanks!

**Comment by keyabarve** [comment]
@ctb Could you provide some clarification on what exactly needs to be done?

**Comment by ctb** [comment]
please see [this comment](https://github.com/dib-lab/sourmash/issues/1415#issuecomment-810518985) and give it a try; once you have an open PR with some changes, I'd be happy to help further.

**Comment by keyabarve** [comment]
Alright, I'll do that. Thanks!
