### ISSUE TITLE
update call to `notify` in `src/sourmash/search.py` with f-strings

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1418]
(a specific issue for the general case in https://github.com/dib-lab/sourmash/issues/1409)

in `src/sourmash/search.py`, there is a call to `notify` in the function `gather_databases` that uses `{}` instead of f-strings. please update!

this issue is for https://github.com/itsabhianant

**Comment by noturshek** [comment]
Hi @ctb ,

Thanks for the favor. This is to inform you that I have started to work on the issue and will be sending a PR as soon as I resolve the issue.

Best,
Abhishek
