### ISSUE TITLE
change `sourmash compute` to `sourmash sketch` in tests

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1419]
In sourmash 4.0, we deprecated `sourmash compute`; it will be removed in sourmash 5.

However, we use `sourmash compute` in many tests (see, for example, `tests/test_sourmash.py::test_do_compare_quiet()`) and this will need to be fixed before we remove `sourmash compute`.

To tackle this issue,
* pick 3-5 test functions in a test file
* create a new branch and pull request, and in the PR indicate which file and functions you're fixing
* link to this issue in the PR description
* fix the test functions to use `sourmash sketch`, commit to PR

#1536 is an example of this, if interested parties want to take a look at the changes in that PR!

**Comment by ctb** [comment]
@itsabhianant this might be a good next issue!

**Comment by noturshek** [comment]
Hi @ctb,

I have read the issue and also got to the files `test_sourmash_compute.py` and `test_sourmash_sketch.py` but I can't get what is to be fixed? Like are there specific functions that need to be replaced or we have to replace `compute` everywhere in the program with `sketch`. It would be a great help if you would explain to me in brief what need's to be fixed.

Best,
Abhishek

**Comment by ctb** [comment]
yes, replace all command-line tests that call `sourmash compute` with the appropriately refigured `sourmash sketch`! None of the tests in `test_sourmash_compute.py` or `test_sourmash_sketch.py` would need to be changed.

For example, in `tests/test_sourmash.py::test_do_compare_quiet()`, this test will break if we remove the `sourmash compute` functionality altogether, which we plan to do in sourmash v5.

To fix that particular test, you would need to replace
```
c.run_sourmash('compute', '-k', '31', testdata1, testdata2)
```
with
```
c.run_sourmash('sketch', 'dna', '-p', 'k=31', testdata1, testdata2)
```
I think.

**Comment by keyabarve** [comment]
Can I take up this issue? @ctb

**Comment by ctb** [comment]
On Wed, May 05, 2021 at 01:02:43PM -0700, Keya Barve wrote:
> Can I take up this issue? @ctb  

yep! start small please :)

**Comment by keyabarve** [comment]
Are there any specific files where `sourmash compute` needs to be replaced with `sourmash sketch`? Are there any other changes to be made apart from just changing `compute` to `sketch`?

**Comment by ctb** [comment]
hi @keyabarve, I suggest spending some time digging around in the sourmash `tests/` directory and then reporting back what you found. There are well over 100 tests that use `sourmash compute`, I think.

There is (hopefully) robust documentation for `sourmash compute` [here](https://sourmash.readthedocs.io/en/latest/command-line.html#sourmash-compute-make-sourmash-signatures-from-sequence-data), and for `sourmash sketch` [here](https://sourmash.readthedocs.io/en/latest/command-line.html#sourmash-sketch-make-sourmash-signatures-from-sequence-data). They take arguments in very different ways, so this isn't a search and replace...

I would prefer you try making some changes and then figuring out whether they work, rather than asking if the changes are correct up front. Scales better :).

**Comment by ctb** [comment]
two more quick notes:
* `test_sourmash_compute.py` will probably be removed in 5.0 completely. Don't worry about changing that.
* all of the tests in `test_sourmash_compute.py` were translated in the way that this issue requests when they were copied over to `test_sourmash_sketch.py` (as I saw no reason to discard perfectly good tests!) So if you are looking for how to do the translation, looking at similarly named tests in the two files is one way to do it.

hope that helps!

**Comment by keyabarve** [comment]
Hmm, I'll take a look at it and get back! :)

**Comment by keyabarve** [comment]
Following are some things I observed in the tests and my questions regarding the same:

In the function `test_do_sourmash_check_knowngood_dna_comparisons_use_rna(c)`
- In `test_sourmash_compute.py` there is `c.run_sourmash('compute', '-k', '21', '--singleton', '--rna', testdata1)`
- In `test_sourmash_sketch.py` there is `c.run_sourmash('sketch', 'rna', '-p', 'k=21,num=500', '--singleton', testdata1)`
Both these lines above are equivalents of each other. The `compute` part contains `'-k'` and `'21'`, whereas the `sketch` part contains 'k=21,num=500'`. In this case, the number 21 is common. 

But if we consider the function `test_do_sourmash_check_knowngood_protein_comparisons()`
-  In `test_sourmash_compute.py` there is `status, out, err = utils.runscript('sourmash', ['compute', '-k', '21' '--singleton', '--protein', '--no-dna',testdata1], in_directory=location)`
-  In `test_sourmash_sketch.py` there is `status, out, err = utils.runscript('sourmash', ['sketch', 'translate','-p', 'k=7,num=500','--singleton',testdata1], in_directory=location)`
Both these lines above are also equivalents of each other. The `compute` part contains `'-k'` and `'21'`, whereas the `sketch` part contains `'k=7,num=500'`. In this case, there is no common number. 

My questions are:
- What do these numbers represent? Why are they the same in one case and different in the other? How do we know which number to put where?
- There are some elements that are common to both `compute` and `sketch` but some elements that are unique to each of them. What do these unique elements represent? How do we know which elements should be common and which ones should be unique?

**Comment by ctb** [comment]
hi keya, there is command-line documentation linked above that should answer most of these questions; have you read those yet?

**Comment by ctb** [comment]
(also, conveniently, in most cases if you get the parameters wrong the tests should fail!)

**Comment by keyabarve** [comment]
Yes, I discussed the same with @luizirber today, so I have some clarity. I'll start working on 2-3 tests and move forward from there! :)

**Comment by keyabarve** [comment]
@ctb PRs #1536 and #1680 only replace `compute` with `sketch` in `tests/test_sourmash.py`. It still needs to be replaced in all of the other test files. Should I create a new issue for the same and can I start working on it?

**Comment by ctb** [comment]
sure!
