### ISSUE TITLE
fix tests that fail to close files that they open

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1435]
There are several tests in `test_lca.py` that are causing warnings during the tests, because I did a bad thing and opened files without closing them.

The three tests are:
```
test_single_summarize_to_output
test_single_classify_to_output
test_single_classify_to_output_no_name
```
and they all use some variant of this code,
```
outdata = open(os.path.join(location, 'outfile.txt'), 'rt').read()
```
which doesn't close the file. This results in a warning when py.test runs the tests.

The proper usage is something like
```
with open(...) as fp:
   outdata = fp.read()
```
which will use a context manager to close the file after the `with` block.

Fix!

**Comment by keyabarve** [comment]
Can I try to fix this? @ctb

**Comment by ctb** [comment]
sure!
