### ISSUE TITLE
consider adding one-to-many option for `compare`

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#1438]
In many of my workflows, I'm running one-to-many comparisons, rather than all-by-all comparisons. 

To enable this at the CLI level, we could add an option, e.g. `--anchor` or `--query`,  to specify the anchor/query to compare against all other specified signatures. Containment would always be directional in this application (containment of anchor sig), though both jaccard and maximum containment would be useful outputs as well.

main benefit: runtime/memory for large comparison sets + avoid parsing all-by-all output for desired comparisons.
drawbacks: changed compare output  == potential impact on `sourmash plot` + semantic versioning issue?

alternatively, separate `anchor-compare` command, or similar?

**Comment by ctb** [comment]
how does this differ from sourmash search?

**Comment by bluegenes** [comment]
ahaha, a fair question.. it doesn't!
