### ISSUE TITLE
provide a summarization command for signature collections

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1439]
from https://github.com/dib-lab/sourmash/pull/1349#issuecomment-786850141 - 

@bluegenes suggests:

>`sourmash sig describe` --> yes, would be nice to support usage, but output may not be as useful? Likely too many sigs for full output, and `sourmash sig describe <zipfile> | head` would no longer represent the parameters of all sigfiles, since it's possible to incorporate incompatible signatures. If enabled, maybe we could summarize the sig params (e.g. num sigs per ksize/alpha/scaled ) as tsv or tabbed terminal output? Or have a quick default option that gives info for first sig, and `summarize` option that gives full summary? Somewhat related to #1190.

maybe a `sourmash sig summary` or `sourmash sig summarize` command?

**Comment by ctb** [comment]
cc #1599 #1352

**Comment by ctb** [comment]
with manifests & the manifest API, this becomes much more straightforward!

**Comment by ctb** [comment]
oh! @bluegenes do you think we should alias `fileinfo` to `summarize`?

**Comment by bluegenes** [comment]
fileinfo is plenty descriptive, but sure, why not!
