### ISSUE TITLE
create a `MinHash` function to copy abundances from one `MinHash` to another

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1463]
Over in #1392, I implement a code block that retrieves abundances from a sketch using hashes; in `src/sourmash/commands.py`, function `gather`:

```python=
            if is_abundance:
                # reinflate abundances
                hashes = set(next_query.minhash.hashes)
                orig_abunds = orig_query_mh.hashes
                abunds = { h: orig_abunds[h] for h in hashes }

                abund_query_mh = orig_query_mh.copy_and_clear()
                # orig_query might have been downsampled...
                abund_query_mh.downsample(scaled=next_query.minhash.scaled)
                abund_query_mh.set_abundances(abunds)
                next_query.minhash = abund_query_mh
```
Here, `next_query.minhash` is a flattened `MinHash` object derived from `orig_query_mh`, and we are constructing a new `MinHash` object `abund_query_mh` that has all of the hashes from `next_query.minhash` with abundances for those hashes taken from `orig_query_mh`.

This is potentially a generically useful function that is kind of the converse of `flatten()`, so let's make it a method on the  `MinHash` class!

TODO:
* create a new method on `MinHash` objects (see `src/sourmash/minhash.py`) named something like `inflate`;
* this method should take one argument in addition to `self`, a `MinHash` object with `track_abundance=True`;
* this method should create a new `MinHash` object that borrows the abundances from the second argument using only the hashes from `self`;
* replace the code block in `commands.gather()` with using this new function (and see if it can apply to `multigather`;
* write some tests for `tests/test_minhash.py`;

**Comment by keyabarve** [comment]
@ctb Is this `inflate` function supposed to be written in `src/sourmash/minhash.py`? Should this function be inside any particular class?

**Comment by ctb** [comment]
yes, in the `MinHash` class. It probably needs to be defined on `FrozenMinHash` where it should raise an exception, too.

**Comment by ctb** [comment]
(order doesn't matter)
