### ISSUE TITLE
enable saving of hashes w/abundances in `multigather --output-unassigned` 

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1464]
In #1392, I noticed that in `src/sourmash/commands.py`, function `multigather`, that abundances are not saved when unassigned hashes are output. See code block starting with `with open(output_unassigned, 'wt') as fp:`.

TODO:
* look at the code in `gather`, and copy the code block to reinflate abundances over to `multigather`;
* write tests for this feature of `multigather` (probably starting with the relevant test for `gather`, which is `test_gather_output_unassigned_with_abundance`)

This could wait until after #1463 is fixed, or be done in the same PR as that issue.

**Comment by keyabarve** [comment]
@ctb I'd like to work on this issue.

**Comment by ctb** [comment]
On Sat, Jun 12, 2021 at 04:10:42PM -0700, Keya Barve wrote:
> @ctb I'd like to work on this issue.

sure! generally you should signal that by creating a pull request (even if
incomplete) and linking to it from the issue.

**Comment by keyabarve** [comment]
@ctb Should #1463 be resolved before working on this?

**Comment by ctb** [comment]
> This could wait until after #1463 is fixed, or be done in the same PR as that issue.

After, or during, either way.

**Comment by keyabarve** [comment]
@ctb Is this issue the same as #1707?

**Comment by ctb** [comment]
yep! closing as duplicate.
