### ISSUE TITLE
provide `&` and `|` operators for `MinHash`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1479]
In #1474 / #1392, we provide `MinHash.intersection(...)` which joins `MinHash.merge(...)` (equivalent to union).

At the time I couldn't figure out how to provide analogs to the set intersection and union operators, which are `&` and `|`. @luizirber pointed out that it's as simple as providing `__and__` and `__or__` on `MinHash` classes; see [this post](https://www.geeksforgeeks.org/operator-overloading-in-python/) for example.

To fix this issue,
* add `__and__` and `__or__` methods on the `MinHash` class;
* add some tests to `tests/test__minhash.py` that confirms they do the same thing as `intersection` and `__add__`, respectively;

**Comment by bluegenes** [comment]
should this be closed? @hehouts @ctb

**Comment by hehouts** [comment]
yes! didnt think to do this, my bad

**Comment by ctb** [comment]
ok - for future reference, "Fixes #<issue number>" in a PR will auto-close it, which is what should have happened, but I just noticed you had "Fixes issue #<issue number>" which doesn't meet the very strict pattern that github looks for 😉
