### ISSUE TITLE
provide `.copy()` method for both `SourmashSignature()` and `MinHash`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1485]
I'm getting tired of using `copy.copy(...)` 😆 

The idea here is to:

* provide `copy` methods on both the `SourmashSignature` and `MinHash` classes. Naively, `copy.copy(self)` should work?
* replace the calls to `copy.copy(...)` in the current sourmash code with the new method.

**Comment by ctb** [comment]
note that `MinHash` in `src/sourmash/minhash.py` already contains a `__copy__(self)` method, could just add a `copy = __copy__` below that. (And write some tests.)

**Comment by ctb** [comment]
actually, if we go with https://github.com/dib-lab/sourmash/pull/1508/, then we won't need `.copy()` for `MinHash` objects because you will instead just call `mutable()` or `frozen()` to get a copy for your desired purpose. Maybe we want to take a similar approach with `SourmashSignature` in the future?

**Comment by keyabarve** [comment]
I would like to work on this. @ctb

**Comment by keyabarve** [comment]
Could you provide a little clarification on what needs to be done here? Which files/functions need to be changed, etc.

**Comment by ctb** [comment]
Here's some reading, too - https://docs.python.org/3/library/copy.html, 
>In order for a class to define its own copy implementation, it can define special methods `__copy__()` and `__deepcopy__()`. The former is called to implement the shallow copy operation; no additional arguments are passed. 

So:

1. define `__copy__(...)` and `copy(...)` methods on `MinHash` subclasses in `src/sourmash/minhash.py`
2. define `__copy__(...)` and `copy(...)` methods on `SourmashSignature` in `src/sourmash/signature.py`
3. write tests to make sure they work properly, in `tests/test_minhash.py` and `tests/test_signature.py` respectively.

**Comment by keyabarve** [comment]
Thanks, I will check it out!
