### ISSUE TITLE
further refactor `gather_databases()` function in search.py

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1517]
per @luizirber, on running gather on a gigantic signature --

>Right now it is spending all the time inside sum_abunds = sum(( orig_query_abunds[k] for k in orig_query_hashes)), because it is pulling each hash of the original query individually (all, err, billions of them?)

Digging into this code, it does this each iteration - and the only reason is because the original query may have been downsampled. Most times it won't need to be calculated more than once.

We should be easily able to refactor this code in one or two ways -
* first, cache this by scaled value, maybe? that would be easy to do.
* second, refactor this code out to a method on `MinHash` and (going further) then oxidize it.

This is the trend we're heading towards in https://github.com/dib-lab/sourmash/pull/1512 and previous, too - move stuff away from Python and into `MinHash`.

Naively I wonder if this is or could be solved by a similar function to the one needed for https://github.com/dib-lab/sourmash/issues/1463

**Comment by ctb** [comment]
aiee! `weighted_missed` (which is what this is used to calculate) isn't even used in the loop 😆 . So this is a largely unnecessary calculation anyway!

There are others that are similar in there, tho, that could be improved. But they're all much, much smaller.

**Comment by mr-eyes** [comment]
What do I need here to get started?

**Comment by ctb** [comment]
I think this was fixed in https://github.com/sourmash-bio/sourmash/pull/1613, actually.
