### ISSUE TITLE
add brief descriptions and `-h/--help` text to sourmash commands

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1557]
There are a variety of sourmash command-line commands that could use a user experience upgrade.

`sourmash compute` is a model of a good command - when you run `sourmash compute` without any arguments, it says:
```
usage:

** WARNING: the sourmash compute command is DEPRECATED as of 4.0 and
** will be removed in 5.0. Please see the 'sourmash sketch' command instead.

   sourmash compute -k 21,31,51 *.fa *.fq

Create MinHash sketches at k-mer sizes of 21, 31 and 51, for
all FASTA and FASTQ files in the current directory, and save them in
signature files ending in '.sig'. You can rapidly compare these files
with `compare` and query them with `search`, among other operations;
see the full documentation at http://sourmash.rtfd.io/.

The key options for compute are:

 * `-k/--ksize <int>[, <int>]: k-mer size(s) to use, e.g. -k 21,31,51
 * `-n/--num <int>` or `--scaled <int>`: set size or resolution of sketches
 * `--track-abundance`: track abundances of hashes (default False)
 * `--dna or --protein`: nucleotide and/or protein signatures (default `--dna`)
 * `--merge <name>`: compute a merged signature across all inputs.
 * `--singleton`: compute individual signatures for each sequence.
 * `--name-from-first`: set name of signature from first sequence in file.
 * `-o/--output`: save all computed signatures to this file.

Please see -h for all of the options as well as more detailed help.

---
```

this kind of helpful text should be the default for commands; but, `sourmash search` just gives you this:
```
usage:  search [-h] [-q] [--threshold T] [--save-matches FILE] [--best-only]
               [-n N] [--containment] [--max-containment] [--ignore-abundance]
               [--scaled FLOAT] [-o FILE] [--md5 MD5] [-k K] [--protein]
               [--no-protein] [--dayhoff] [--no-dayhoff] [--hp] [--no-hp]
               [--dna] [--no-dna]
               query databases [databases ...]
 search: error: the following arguments are required: query, databases
```

To get started on this issue, 
* select a command to focus on from the commands below;
* find the relevant command-line wrapper under `src/sourmash/cli/`
* create a new branch
* taking information from the command-line docs, https://sourmash.readthedocs.io/en/latest/command-line.html,
   * create a draft 'usage' string as in https://github.com/dib-lab/sourmash/blob/latest/src/sourmash/cli/compute.py
   * create a docstring at the top of the file, as in https://github.com/dib-lab/sourmash/blob/latest/src/sourmash/cli/compute.py
   * add the docstring and usage string to the subparser call, as in https://github.com/dib-lab/sourmash/blob/latest/src/sourmash/cli/compute.py
* verify that the usage string is output when you run the command with no arguments
* verify that the docstring is contained in the output of `-h`
* ask for review! we may want to edit the docstring upon review, so don't worry too much about the contents until you have the PR working.

Please check these off as you start a PR to fix them:
- [x] all of the sourmash sig subcommands
- [x] sourmash gather
- [x] sourmash search
- [x] sourmash compare
- [ ] sourmash sketch dna, protein, translate

**Comment by mr-eyes** [comment]
So, we need to print a help/usage message even if the user didn't explicitly pass `--help` in the command?

**Comment by ctb** [comment]
On Fri, Jun 04, 2021 at 11:55:25AM -0700, Mohamed Abuelanin wrote:
> So, we need to print a help/usage message even if the user didn't explicitly pass `--help` in the command?

I think so.

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
sure.

**Comment by keyabarve** [comment]
@ctb should i do something similar to what i did for #1612 here?

**Comment by ctb** [comment]
yep!

**Comment by keyabarve** [comment]
The sourmash sig subcommands are handled in #1714.
The gather, search and compare commands are handled in #1735.
