### ISSUE TITLE
pip/conda both install outdated sourmash

### ISSUE THREAD

**Issue by rchikhi** [sourmash-bio/sourmash#1561]
```
$ pip --version
pip 21.1.1 from /home/rayan/.local/lib/pypy3.6/site-packages/pip (python 3.6)

$ pip install sourmash
Defaulting to user installation because normal site-packages is not writeable
Collecting sourmash
  Downloading sourmash-3.5.1-py2.py3-none-manylinux2010_x86_64.whl (1.2 MB)
[...]

$ sourmash sketch
sourmash: error: argument cmd: invalid choice: 'sketch' 

$ sourmash
== This is sourmash version 3.5.1. ==
[..]
```

**Comment by rchikhi** [comment]
Hum, conda too:

```
$ conda install -c conda-forge -c bioconda sourmash
[..]
    sourmash-3.3.0             |   py37h8f50634_1         4.1 MB  bioconda
```

**Comment by rchikhi** [comment]
I'd be fine with staying in version 3 except that README mentions the command `sketch` which is not implemented in version 3

**Comment by mr-eyes** [comment]
Hi @rchikhi ,
Could you please try installing the packages in a new environment and report the results?

```
conda create -n tmp -c conda-forge -c bioconda sourmash
```

**Comment by ctb** [comment]
hi rayan, you'll need to use Python >= 3.7 - my guess is you're using 3.6? Sourmash 4 dropped support for 3.6 and earlier.

Let me know if that doesn't work - I'll revisit in a bit myself. This isn't awesome behavior by pip and conda even if it does turn out to be because of Python 3.6! 😆

**Comment by ctb** [comment]
ok, revisited, and saw:

>python 3.6

in the first set of output. So that's probably the problem.

If you create a new conda environment just specifying sourmash as @mr-eyes suggested, that should work!

**Comment by rchikhi** [comment]
thanks for your answers! yep, nicely spotted, my pip was using Python 3.6. I tried with Python 3.7 and it worked well. (both through pip and @mr-eyes cmdline)

**Comment by rchikhi** [comment]
This can be closed unless you'd like to further fix it for 3.6

**Comment by ctb** [comment]
thanks! I'll close it for now, see if it pops up again :)

**Comment by davidlevybooth** [comment]
Same error when installing from conda in Python 3.7.12 env

from https://sourmash.readthedocs.io/en/latest/:
`conda install -c conda-forge -c bioconda sourmash`
`sourmash sketch dna -p k=21,k=31,k=51,scaled=1000 genomes/*.fa --name-from-first -f
`
`sourmash: error: argument cmd: invalid choice: 'sketch' (choose from 'categorize', 'compare', 'compute', 'dump', 'gather', 'import_csv', 'index', 'info', 'migrate', 'multigather', 'plot', 'sbt_combine', 'search', 'watch', 'lca', 'sig', 'signature', 'storage')`

**Comment by ctb** [comment]
hi @davidlevybooth thanks - what does `sourmash info` say? (this looks like sourmash v1.)

also, what does `python -V` give you?

thank you!

**Comment by davidlevybooth** [comment]
Running this command from the github readme:

`conda create -n sourmash_env -c conda-forge -c bioconda sourmash python=3.7`

Installed python 3.7.12 and sourmash 3.3.0 

Running the above command with `python=3.8` installed sourmash 4.4.0. 

BTW, really enjoying the database construction flexibility now that sourmash is installed properly!

**Comment by ctb** [comment]
I'm really glad that worked for you, and we should probably update things to deprecate python3.7 more clearly!

And  in re:
>BTW, really enjoying the database construction flexibility now that sourmash is installed properly!

thank you ❤️ , that was a lot of work 😅!
