### ISSUE TITLE
MinHash Similarity precision

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#1572]
If we have 2 sequences containing 4 kmers each, they are different in only one kmer. Shouldn't the similarity be 75% instead of 60%?

**Reproduce:**

```python
from sourmash import MinHash

mh1 = MinHash(n=0, scaled = 1, ksize=21)
mh1.add_sequence('ATGAGAGACGATAGACAGATGACC')

mh2 = MinHash(n=0, scaled = 1, ksize=21)
mh2.add_sequence('ATGAGAGACGATAGACAGATGACT')

print(f"mh1 hashes: {sorted(mh1.hashes)}")
print(f"mh2 hashes: {sorted(mh2.hashes)}")

print(f"similarity:{mh1.similarity(mh2)}")

```

**Output:**

```
mh1 hashes: [7385331214843500221, 16414705137837825029, 16597798512601531329, 16685850496431748149]
mh2 hashes: [7032764938230067276, 7385331214843500221, 16414705137837825029, 16597798512601531329]
similarity:0.6
```

Shouldn't it be = 0.75?

**Comment by bluegenes** [comment]
Maybe you're thinking containment? Otherwise, they differ by 2 k-mers (one in each mh)?

jaccard similarity (intersection/union) = 3/5
mh1 containment (intersection/mh1) = 3/4
mh2 containment (intersection/mh2) = 3/4

**Comment by mr-eyes** [comment]
I got it! thank you :) super clear now.
