### ISSUE TITLE
Why is the idx reversed for fig labels but not for matrix reordering in fig.py?

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#1605]
```
# re-order labels along rows, top to bottom
idx1 = Z1['leaves']
reordered_labels = [ labeltext[i] for i in reversed(idx1) ]
# reorder D by the clustering in the dendrogram
D = D[idx1, :]
D = D[:, idx1]
```
https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/fig.py#L62

I was just trying to make a clustered heatmap for the output of `sourmash tax summarize --output-format lineage_summary` and I was reading the code for compare viz and saw that the label vector is reverse ordered based on `idx1`, but the comp matrix is reordered just based on `idx1` and i'm confused...wouldn't this  make it so that the labels and the matrix were in opposite order? like `1, 2, 3` and `3, 2, 1`?

**Comment by ctb** [comment]
I'm afraid I don't understand the code, either. I reached this point after
an unreasonable amount of trial and error :).

Does it actually do the wrong thing? I tried to check the output carefully.

**Comment by taylorreiter** [comment]
I'm not sure, it did the wrong thing when I repurposed this code for #1607, but that code was obviously in a different context. I'll double check this later and report back.

**Comment by taylorreiter** [comment]
Ok i'm 99.9% sure they're reversed 🙃

**Comment by taylorreiter** [comment]
And I think replacing line 62 (https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/fig.py#L62)
```
    reordered_labels = [ labeltext[i] for i in reversed(idx1) ]
```
with
```
    reordered_labels = [ labeltext[i] for i in idx1]
```
should fix it, but I'm not sure how/if we should write unit tests for this

**Comment by ctb** [comment]
fixed in https://github.com/sourmash-bio/sourmash/pull/1821
