### ISSUE TITLE
How to parse a sig starting from a json string using the python API?

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1608]
Say I have a (JSON) string that contains the signature data. How can I parse this into a `SourmashSignature` object using the python API? `StringIO` does not work with `load_one_signature`; I could write the data into some temporary file and read that, but I thought there might be an easier way, though looking at [the fn def](https://github.com/sourmash-bio/sourmash/blob/74de59ad7dfad889a385e4f4f5b48e25b8c3a9b3/src/sourmash/signature.py#L238) it seems there is not?

**Comment by ctb** [comment]
On Sat, Jun 19, 2021 at 05:47:20AM -0700, Adrian Viehweger wrote:
> Say I have a (JSON) string that contains the signature data. How can I parse this into a `SourmashSignature` object using the python API?

sourmash.signature.load_signatures(json_str)

or

sourmash.signature.load_one_signature(json_str)

best,
--titus

**Comment by ctb** [comment]
(note that, for better or for worse, we do not currently guarantee this
particular API with semantic versioning; that's because we have hopes of
changing it at some point. :)
