### ISSUE TITLE
upgrade command-line docs for `sourmash sig` subcommands

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1612]
The various `sourmash sig` subcommands (cat, extract, etc) do not give very useful information when invoked on the command line without any arguments --

```
% sourmash sig cat
usage:  cat [-h] [-q] [-o FILE] [-u] signatures [signatures ...]
 cat: error: the following arguments are required: signatures
```

to address this:
* pick a sourmash sig subcommand that doesn't have useful output when run w/o arguments
* find the relevant subcommand file (e.g. `src/sourmash/cli/sig/cat.py`)
* in that file, add a `description=__doc__` and `usage=usage` argument to the `subparser.add_parser(...)` call; see `src/sourmash/compute.py` for an example
* initialize the `__doc__` and `usage` strings from the command-line docs
* ask for initial review and someone will work with you on the text

This can also be done for many other commands than just the `sourmash sig`, too ;).

**Comment by ctb** [comment]
relevant: https://github.com/sourmash-bio/sourmash/issues/899

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
yep!
