### ISSUE TITLE
Update docs with new sourmash-bio information

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1618]
* update URLs in docs
* guidance on using gitter (or matrix/evolution) to connect with online discussion

**Comment by luizirber** [comment]
Also add gitter/matrix badge to README

**Comment by ctb** [comment]
relevant: https://github.com/sourmash-bio/sourmash/issues/1002

**Comment by ctb** [comment]
initial URL porting done here, https://github.com/sourmash-bio/sourmash/pull/1629
