### ISSUE TITLE
gather against a mix of compatible and incompatible databases

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#1637]
trying out https://github.com/sourmash-bio/sourmash/pull/1590#issuecomment-867220787
> running a gather against all available databases (rather than only using databases with the right ksize/scaled) 

I provided databases in for multiple ksizes (`k7-11` protein) for a gather with `k=11`.
```
== This is sourmash version 4.1.3.dev16+g9dbd8b50. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

picking column 'name' of type 'identprefix' from 'output.protein-demo/sigs/protein/GCF_003143755.sig.csv'
loaded 1 distinct values into picklist.
WARNING: 1 values in picklist column 'name' were not distinct
selecting specified query k=11
loaded query: GCF_003143755... (k=11, protein)
no compatible signatures found in 'tests/test-data/databases/gtdb-rs202-reps.protein-k7.sbt.zip'
```
To enable compatible + incompatible databases for `gather`, we need to ignore incompatible databases as long as there are some compatible sigs in one of the provided databases.

**Comment by ctb** [comment]
right - as we've gotten more flexible with `Index` objects and so on, this has become more of a problem! My hot take is that we should be able to properly distinguish between -

* at least one database exists, is loadable, and has relevant signatures (win!)
* all the databases exist, all are loadable, but none have relevant signatures (fail with appropriate error message!)
* one or more of the databases does not exist or is not loadable

Once upon a time this was more complicated b/c we were missing things like database compatibility checking, but with the newly enhanced™️ `Index.select(...)` stuff we can check for compatibility on load properly now.

**Comment by ctb** [comment]
see also https://github.com/sourmash-bio/sourmash/issues/977

**Comment by ctb** [comment]
relevant: #1877
