### ISSUE TITLE
Direct access to hash fn

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1663]
I am trying to calculate hashes for all kmers in a certain space. I found a [script]() in this repo that was used to calculate this independent of sourmash using the `mmh3` library. Now I try this:

```python
import mmh3
from sourmash.minhash import get_minhash_default_seed

get_minhash_default_seed()  # 42
mmh3.hash64('ABCDEF', seed=get_minhash_default_seed())[0]  # 4472632055005803327
```

But the hash is different from when I use sourmash -- what am I doing wrong here?

```bash
cat test.fa
# >test
# ABCDEF
sourmash sketch protein -p k=6,scaled=1,dayhoff -o sig test.fa
cat sig
# ... "mins":[10768638168805974592] ...
```

**Comment by phiweger** [comment]
None of this works for me either:

```python
mmh3.hash64(to_bytes('ABCDEF'), seed=get_minhash_default_seed())[0]
# 4472632055005803327


from sourmash import lib
lib.hash_murmur(to_bytes('ABCDEF'), 42)
# 4472632055005803327


from sourmash import MinHash
mh = MinHash(ksize=6, dayhoff=True, is_protein=True, scaled=1)
mh.add_sequence('ABCDEF')
mh.hashes  # empty {}
```

**Comment by ctb** [comment]
Yeah, you need to use `add_protein`, sorry ;(. `add_sequence` is for adding DNA sequence only, and in this case it's trying to translate `ABCDEF` from DNA into protein.

Here:
```
>>> mh = MinHash(n=0, ksize=6, dayhoff=True, is_protein=True, scaled=1)
>>> mh.add_sequence('ABCDEF')
>>> mh.hashes
{}
>>> mh.add_protein('ABCDEF')
>>> mh.hashes
{10768638168805974592: 1}
```

I'll have to dig a bit to figure out the reason why the hashes are different, tho.

**Comment by ctb** [comment]
and @mr-eyes is working on #1214 over in https://github.com/sourmash-bio/sourmash/pull/1653, which should hopefully provide a simpler way to deal with this issue.

**Comment by phiweger** [comment]
More weirdness @ctb -- is this a bug?

As stated above I want to get all hashes for all Dayhoff sequences of k=7, which turn out to be `6 ** 7` ie 279,936 sequences. When I hash them, I only get `78,125` hashes. Since there is no reverse complement and all the sequences are unique, is this explainable or a computation error?

```python
from collections import Counter
from itertools import product

from sourmash import MinHash  # v4.2
from tqdm import tqdm

# Generate all possible sequences of len 7 using Dayhoff encoding
vocab = 'ABCDEF'
p = [''.join(i) for i in product(vocab, repeat=7)]
assert len(p) == len(set(p)) == len(vocab) ** 7 
# 279,936 sequences


# Hash these sequences
hashes = []
for i in tqdm(p):
    mh = MinHash(ksize=7, dayhoff=True, is_protein=True, scaled=1, n=0)
    mh.add_protein(i)
    hashes.append(list(mh.hashes)[0])
assert len(set(hashes)) == len(p), 'Odd, this is unexpected ...'
# Only 78,125 hashes


Counter(hashes).most_common(10)
'''
[(15621553511600302476, 128),
 (15172692902608038558, 64),
 (16198871515767958450, 64),
 (10053822624959840190, 64),
 (996771667391163610, 64),
 (16241567574402240584, 64),
 (14822778361119392056, 64),
 (8842100629538717181, 64),
 (12361043099660319636, 64),
 (4020207384456581143, 64)]
'''

```

**Comment by phiweger** [comment]
Can the hash space sort of "wrap around" @luizirber to the beginning, ie might the above be hash collisions?

```python
# Expanding on the above
assert sum(Counter(hashes).values()) == len(p)
# Indeed
```

**Comment by ctb** [comment]
ok, finally figured this out 😆 .

`add_protein` adds a protein sequence, not a dayhoff sequence. The translation into Dayhoff encoding is done by sourmash. So what you are seeing is (probably) correct behavior where it is translating your `i` into Dayhoff encoding, and then adding that.

**Comment by ctb** [comment]
so:
```python
import sourmash.minhash

# Hash these sequences
hashes = []
for i in tqdm(p):
    h = sourmash.minhash.hash_murmur(i)
    hashes.append(h)

print(len(set(hashes)))
assert len(set(hashes)) == len(p), 'Odd, this is unexpected ...'


Counter(hashes).most_common(10)
```
does what you think it should.

**Comment by ctb** [comment]
(note that if you want these hashes in a `MinHash` object, you can use `mh.add_hash(i)`.)

**Comment by phiweger** [comment]
Thank you very much for taking the time to clarify this!

**Comment by ctb** [comment]
glad it wasn't "terrible bug that we've not detected thus far" 😆

**Comment by phiweger** [comment]
I now get why I was getting different hashes from CLI vs. API, basically `hash_murmur('ABC') != hash_murmur('abc')` -- I could have done so many cool things in the past hour ;)

**Comment by phiweger** [comment]
Hm, still me. When I Dayhoff hash some proteins, the resulting signature contains hashes that should not be in the hash set defined by `ksize` and the Dayhoff alphabet (`abcdef`) -- @ctb @olgabot I've attached `coding.txt` so you can replicate the code below, don't mind the `.txt` extension, it's a `.faa` but Github does not let you attach this file extension.

[coding.txt](https://github.com/sourmash-bio/sourmash/files/6825793/coding.txt)
```python


from itertools import product
import json

from tqdm import tqdm
from sourmash.minhash import hash_murmur


# Dayhoff alphabet -- https://github.com/sourmash-bio/sourmash/pull/689
vocab = 'abcdef'

# Define the reference space
k = 7
p = set([''.join(i) for i in product(vocab, repeat=k)])
assert len(p) == 6**k

# Hash these sequences
ref = set()
for i in tqdm(p):
    h = hash_murmur(i)
    ref.add(h)
assert len(ref) == len(p)

# Which hashes are found in a query signature?
# sourmash sketch protein -p k=7,scaled=100,dayhoff,abund -o sig coding.txt
with open('sig', 'r') as file:
    sig = json.load(file)
    qry = set(sig[0]['signatures'][0]['mins'])

# All of them should be in the reference space, right?
assert len(qry.intersection(ref)) == len(qry), 'Why wouldn\'t his be true?'
# prints "Why wouldn't this be true"?
# 894 hashes in the intersection vs. 914 hashes in qry
```

**Comment by phiweger** [comment]
Ah, I have not included the stop codon in the alphabet. Which sign do you use there?

**Comment by ctb** [comment]
`*`

**Comment by phiweger** [comment]
Same result for `vocab = 'abcdef*'`.

**Comment by phiweger** [comment]
So the question is, what are the hashes that are not in the (in theory exhaustive) k-mer reference set?

**Comment by ctb** [comment]
Tried code with https://github.com/sourmash-bio/sourmash/blob/latest/tests/test-data/ecoli.faa, assertion passes.

Looks like the stop codon is the problem.

Looks like the problem is that the stop codon is not encoded to the stop codon in aa-to-dayhoff.

Also looks like a related problem that when there are invalid aa, they are not detected or caught in any way, so we are trusting the input data.

More detailed explanation etc incoming.

**Comment by ctb** [comment]
Please see https://github.com/sourmash-bio/sourmash/pull/1673.

There is a coupled problem here -
* stop symbols (`*`) are part of what is hashed by `add_protein`.
* therefore, if (e.g.) in a protein file you have `*` at the end of sequences, you get an "extra" hash value for each sequence.
* however, `*` are not included in dayhoff and hp encoding tables in `encoding.rs`, so `map` doesn't  know what to do with them in `signature.rs`. I'm honestly not sure what happens here, but it appears that they are not being mapped from `*` to `*` in the dayhoff/hp translations. 

This last bit is what leads to your problem in your program above. You are checking to see if `abcdef*` shows up in the hashes, but the aa sequence `CADHIF*` doesn't actually get converted into `abcdef*`. To fix this in #1673, I add `*` to the translation tables, but I think this needs a bit more thought.

**Comment by ctb** [comment]
p.s. definitely ill-defined behavior in here, maybe also a bug, thank you for digging!!

**Comment by phiweger** [comment]
I'm sure you know this, but there is an extended protein alphabet which I ran into frequently, so I adjusted the translation into Dayhoff like so:

```python
def dayhoff(seq):
    '''
    The "default" Dayhoff encoding does not cover some of the letters in the 
    "Extended IUPAC" protein encoding, see e.g.
    
    https://biopython.org/DIST/docs/api/Bio.Alphabet.IUPAC.ExtendedIUPACProtein-class.html
    
    > Extended uppercase IUPAC protein single letter alphabet including X etc.
    In addition to the standard 20 single letter protein codes, this includes:
    
    [ ] B = "Asx"; Aspartic acid (R) or Asparagine (N)
    [ ] X = "Xxx"; Unknown or 'other' amino acid
    [x] Z = "Glx"; Glutamic acid (E) or Glutamine (Q)
    [x] J = "Xle"; Leucine (L) or Isoleucine (I), used in mass-spec (NMR)
    [x] U = "Sec"; Seleno__cysteine__
    [x] O = "Pyl"; Pyrro__lysine__
    
    We simply add them, where they map to a unique Dayhoff character ([x]):
    '''
    alphabet = {
        'C' + 'U': 'a', 
        'GSTAP': 'b',
        'DENQ' + 'Z': 'c',
        'RHK' + 'O': 'd',
        'LVMI' + 'J': 'e',
        'YFW': 'f',
        '*': '*'}
    '''
    With this scheme, i.e. only excluding proteins that have letters X and B in
    them, we can go through > 99.5 % of the Uniprot SPROT database (n=562,015):
    '''
    translation = ''
    for letter in seq:
        for k in alphabet.keys():
            if letter in k:
                translation += alphabet[k]
    assert len(translation) == len(seq)
    return translation
```

**Comment by ctb** [comment]
hey @phiweger I'd be curious for your thoughts on this [new documentation](https://github.com/sourmash-bio/sourmash/blob/update/dayhoff_hp_stop/doc/api-example.md#introduction-k-mers-molecule-types-and-hashing) I'm adding over in #1673. No particular hurry.

**Comment by phiweger** [comment]
This adds a lot of clarity, especially on the behaviour of the different functions, thank you for writing this documentation! A minor comment of a point I did not see covered:

> So, for example, the amino acid sequence `CADHIF*` is mapped to `abcdef*` in the Dayhoff encoding.

I'd add a comment on when it matters that sequences be case sensitive and when not. For example, the Dayhoff hashing requires the sequence in all lower-case letters, while DNA can be fed upper or lower-case, right?

**Comment by ctb** [comment]
thanks - I should probably verify the behavior more before writing about it, but I think all _input_ sequence should be properly cleaned, and there's no canonical way to feed Dayhoff or hp into sourmash MinHash objects.

**Comment by phiweger** [comment]
@ctb is the corrected Dayhoff behaviour already part of merge #1653 ? I stepped through the comments but could not find anything, although I might have just overlooked it.

**Comment by ctb** [comment]
it's in #1673.

**Comment by ctb** [comment]
which is also already merged :)

**Comment by ctb** [comment]
(so I think we can close this issue, too?)

**Comment by phiweger** [comment]
ah of course, thank you!
