### ISSUE TITLE
Motif predictions using protein sketch

### ISSUE THREAD

**Issue by elzerac** [sourmash-bio/sourmash#1692]
Hello, 

Thank you so much for creating sourmash and the awesome documentation. I am interested in using sourmash for protein motif identification in PhIPseq libraries. I love the idea of identifying kmer motifs using dayhoff similarities. Antibodies likely recognized short motifs with shared chemical structure. I was wondering if there's any way to pull out the motifs from the hash table similar to issue #1372 . I tried to use the code that said it doesn't work for protein and it didn't work (haha). Even if I could pull out the dayhoff motifs that would be very interesting, but would be the coolest if I could look at the amino acid contribution to each position in the kmer. Are there any work arounds that I could get started on? I'm not the most experienced coder.

I know this may be a big feature request but I just wanted to put it out there!

**Comment by ctb** [comment]
you are in luck! the merge of https://github.com/sourmash-bio/sourmash/pull/1653 by @mr-eyes makes this (hopefully) fairly straighforward, and the code for protein/dayhoff [in the docs](https://sourmash.readthedocs.io/en/latest/api-example.html#protein-based-encodings) might show you what you need to do, albeit in Python! I'll take a look at #1372 and see if it's possible to write something simple to do it from the command line - it should be now.

**Comment by ctb** [comment]
I got started on this, and ran into some trouble with the translation stuff (going from protein/dayhoff/hp hashes back to DNA). The DNA hashes back to DNA k-mers and the protein hashes back to protein k-mers works fine, though.  I'm guessing you would be most immediately interested in protein k-mers so if you want to play around with that experimental code let me know and I can focus on getting that tested and available first.

**Comment by elzerac** [comment]
Wow! Thank you so much. Yes, we are currently trying to use protein fasta files as input, so if we can read out the protein kmers that would be so awesome!

**Comment by ctb** [comment]
see https://github.com/sourmash-bio/sourmash/pull/1695
