### ISSUE TITLE
Draft release notes for 4.2.2

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1705]
from https://hackmd.io/Wa1xssUlQrybqn4lnkax1A -

---

# draft release notes 4.2.2

```
git checkout latest
git pull
git log --oneline v4.2.1..latest
```

## 4.2.2 release notes

Major new features:

* added functionality to recover original k-mers given hashes - `sourmash sig kmers` et al. (#1653, #1695, #1701)

Documentation updates:

* Updated picklist docs (#1683)
* Updated the 'how to release' doc after 4.2.0 release (#1649)
 
Minor new features:

* Adjusted dayhoff and hp encodings to tolerate stop codons in the protein sequence (#1673)

Bug fixes and performance improvements:

* Fixed panic bug in `sourmash sketch` dna with bad input and `--check-sequence` (#1702)

Refactoring and cleanup:

* Changed `sourmash compute` to `sourmash sketch` in `tests/test_sourmash.py` (#1680, #1687)
* Tested and fixed `sourmash_args.load_many_signatures(...)` and `lca_db.load_single_database` (#1684)

**Comment by mr-eyes** [comment]
I think `seq_to_hashes` was never introduced in a release before mentioning its bug fixes.
