### ISSUE TITLE
update `sourmash multigather` to save hash abundances to `.unassigned.sig`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1707]
In https://github.com/sourmash-bio/sourmash/issues/1620, we factored out the abundance-recovery behavior in `sourmash gather` for `--output-unassigned` into a new `MinHash.inflate(...)` method.  This abundance-recovery behavior could now easily be added to multigather, which currently doesn't recover abundances properly.

See `CTB: note, multigather does not save abundances` in commands.py, near line 980.

To fix:
* start by writing a test for multigather based on the `gather` tests for inflation, and make sure that fails on multigather;
* fix multigather's implementation to pass the test by using the `inflate` method

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
sure!

**Comment by ctb** [comment]
being tackled in #1720.
