### ISSUE TITLE
confirm and/or add bounds checking for scaled and num in `sourmash sketch`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1708]
https://github.com/sourmash-bio/sourmash/issues/1243 and the associated PRs https://github.com/sourmash-bio/sourmash/pull/1688 and https://github.com/sourmash-bio/sourmash/pull/1650 added checks for the values of `--num-hashes` and `--scaled` on (among other CLI functions) `sourmash compute`. We should make sure that the param string values now used in `sourmash sketch` (`-p num=...` and `-p scaled=...`) also emit errors and warnings appropriately.

**Comment by keyabarve** [comment]
@ctb Can I work on this issue?

**Comment by ctb** [comment]
On Wed, Aug 11, 2021 at 10:39:08AM -0700, Keya Barve wrote:
> @ctb Can I work on this issue?

sure!

**Comment by keyabarve** [comment]
@ctb I had a few questions:
I had written the functions `check_scaled_bounds` and `add_scaled_arg` for `--scaled` and `check_num_bounds` and `add_num_arg` for `--num` in `src/sourmash/cli/utils.py`. I had then called the `add_scaled_arg` and `add_num_arg` functions in the files for each command. 
- Should I be using these functions for the `sketch` command too?
- If so, in which file should I call these functions in for the `sketch` command? I can't seem to find a file called `sketch.py` with the `subparser.add_argument(..)` code blocks. Instead, there is a `sketch` folder, which has 4 files: `__init__.py`, `dna.py`, `protein.py` and `translate.py`. But I can't find the `subparser.add_argument(..)` blocks for `--scaled` and `--num` in them.
- Should I write tests to check this behavior in `tests/test_sourmash_sketch.py`?

**Comment by ctb** [comment]
I think you should use common functions, but you might have to do something different here because `sourmash sketch` doesn't use `--scaled` and `--num` but rather parameter strings with `-p`.

**Comment by keyabarve** [comment]
> I think you should use common functions, but you might have to do something different here because `sourmash sketch` doesn't use `--scaled` and `--num` but rather parameter strings with `-p`.
>
In which file(s) should I call the functions and where can I find the parameter strings?

**Comment by ctb** [comment]
Generally, tests for command-line functionality should go together with other tests for that command line functionality, so please put the tests with the other `sourmash sketch` tests.

The functions called by `sourmash sketch` subcommands can be found by tracing the functions called in the `src/sourmash/cli/` folder, as per usual. That will guide you to the code that parse the `-p` parameters.

**Comment by keyabarve** [comment]
Thank you, I'll do that.
