### ISSUE TITLE
sourmash sketch protein should complain when you feed DNA

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#1719]
This is just based on behavioural observation ;) but I have now several times fed the genome `.fasta` directly into the protein sketching w/o previous `prodigal`ing. No complaints, and then I wonder for several seconds why there are no matches to anything. Maybe as simple as

```
assert len(set(seq[:1000])) > 4
```

**Comment by ctb** [comment]
great minds think alike, although I actually like your solution better 😆 

https://github.com/sourmash-bio/sourmash/pull/1037

**Comment by phiweger** [comment]
:) I'll close here to not duplicate
