### ISSUE TITLE
'Argument list too long' when using sourmash index

### ISSUE THREAD

**Issue by polinanvkv** [sourmash-bio/sourmash#1721]
Hello! 

I am running sourmash on ~2M files. When trying to execute `sourmash index` I get the error in the log file:
```
/var/lib/slurmd/job2459738/slurm_script: line 25: /home/users/pnovikova/miniconda3/envs/smash/bin/sourmash: Argument list too long
/var/lib/slurmd/job2459738/slurm_script: line 28: /home/users/pnovikova/miniconda3/envs/smash/bin/sourmash: Argument list too long
``` 

I understand the issue is with the huge file number, and I've seen people submitting same issues here but still couldn't get if this problem is solved. Hope so :) 

P.S.
I've got `sourmash                  3.2.2            py37h516909a_0    bioconda`. 

Thanks in advance!

**Comment by ctb** [comment]
hi @polinanvkv, if you upgrade to the latest version of sourmash (4.2.2, I think?), then you can use `--from-file` to pass in a file containing your list of files. I don't exactly remember when we added that feature, but it was after 4.x, I'm afraid! But all of the file formats and so on are compatible so it shouldn't be a big chore to upgrade.

**Comment by ctb** [comment]
(the behavior was added in [sourmash 4.0.0](https://github.com/sourmash-bio/sourmash/releases/tag/v4.0.0); please see [the migration guide](https://sourmash.readthedocs.io/en/latest/support.html#migrating-from-sourmash-v3-x-to-sourmash-v4-x) for info on how to upgrade versions!)

**Comment by polinanvkv** [comment]
@ctb thank a lot! I upgraded sourmash and it works perfectly now :)

**Comment by ctb** [comment]
excellent! glad to hear it!
