### ISSUE TITLE
sourmash tax error

### ISSUE THREAD

**Issue by maguileraf** [sourmash-bio/sourmash#1722]
I am trying to use “sourmash tax” but I keep getting the “No taxonomic identifiers” error

sourmash tax metagenome --gather-csv ../output/xylella_abund/xylella_368_abund.csv --taxonomy xylella_db_metadata.csv 
== This is sourmash version 4.2.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
ERROR: cannot read taxonomy assignments from ‘xylella_db_metadata.csv’: No taxonomic identifiers found.

**Comment by bluegenes** [comment]
Hi @maguileraf,

Can you give us an example of what `xylella_db_metadata.csv` looks like? It seems likely we're not finding the right column names to read the taxonomy assignments.

**Comment by maguileraf** [comment]
Hi @bluegenes,

I figured out the error since the header for the identifier needs to be called 'ident'. I tried running it again and it now says:
sourmash tax metagenome --gather-csv ../output/xylella_abund/xylella_368_abund.csv --taxonomy xylella_db_metadata_2.csv 

== This is sourmash version 4.2.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Exiting.
ERROR: Not all required gather columns are present in ../output/xylella_abund/xylella_368_abund.csv.

[xylella_db_metadata_2.csv](https://github.com/sourmash-bio/sourmash/files/7049124/xylella_db_metadata_2.csv)

**Comment by maguileraf** [comment]
I think this error is because that gather data was obtained with sourmash 3.X 
I just tried it with another sample where I used gather sourmash 4.X and it works!

**Comment by bluegenes** [comment]
> I think this error is because that gather data was obtained with sourmash 3.X
I just tried it with another sample where I used gather sourmash 4.X and it works!

Great! Yeah `tax` requires at least the following columns to be in the `gather` csv:  ('query_name', 'name', 'f_unique_weighted', 'f_unique_to_query', 'unique_intersect_bp', 'remaining_bp', 'query_md5', 'query_filename'), some of which were added in `v 4.1.2` :)
