### ISSUE TITLE
Add "--seed" to sketch?

### ISSUE THREAD

**Issue by klamens** [sourmash-bio/sourmash#1731]
I noticed there is no way to change the seed in the sketch function (in contrast to the compute function). Will this be updated in the future?

**Comment by ctb** [comment]
On Mon, Aug 30, 2021 at 01:59:43AM -0700, klamens wrote:
> I noticed there is no way to change the seed in the sketch function (in contrast to the compute function). Will this be updated in the future?

hi, try -p seed=43 - should work! either way, let me know; we should
put it in the docs ;)

**Comment by ctb** [comment]
closing this issue in favor of #1732
