### ISSUE TITLE
Handling ambiguous base pairs in input

### ISSUE THREAD

**Issue by brendanwee** [sourmash-bio/sourmash#1733]
I am trying to create a custom database and some of my reference genomes have ambiguous base pairs `N`

When computing the minhash from the python API I get the following error:
```
  File ".../sourmash/minhash.py", line 295, in add_sequence
    self._methodcall(lib.kmerminhash_add_sequence, to_bytes(sequence),
  File ".../sourmash/utils.py", line 25, in _methodcall
    return rustcall(func, self._get_objptr(), *args)
  File ".../sourmash/utils.py", line 78, in rustcall
    raise exc
ValueError: invalid DNA character in input k-mer: TTGCAGAAGATGACCCTGTTCGTCTTTTGGATGCTTTGGTGGATAATCTCN
```

Should these bases be preprocessed differently before trying to process the hash? Or should sourmash be able to handle these in some way?

Thanks in advance

**Comment by ctb** [comment]
hi @brendanwee! Please see [the API example docs](https://sourmash.readthedocs.io/en/latest/api-example.html#invalid-characters-in-dna-and-protein-sequences) - you can use `force=True` with `add_sequence`:

```
>>> dnaseq = "nTGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGC"
>>> K = 31
>>> mh = MinHash(n=0, ksize=K, scaled=1)
>>> mh.add_sequence(dnaseq)
Traceback (most recent call last):
    ...
ValueError: invalid DNA character in input k-mer: NTGCGAGTGTTGAAGTTCGGCGGTACATCAG
>>> mh.add_sequence(dnaseq, force=True)
>>> len(mh)
4
```

please let us know if that doesn't work!

**Comment by brendanwee** [comment]
That worked! Thanks
