### ISSUE TITLE
update `tests/test_sourmash.py::test_storage_convert` to use `runtmp` fixture instead of `utils.TempDirectory()`

### ISSUE THREAD

**Issue by keyabarve** [sourmash-bio/sourmash#1734]
This is a continuation of  #1386.

Over in #1718, all of the tests were updated to use `runtmp` fixture instead of `utils.TempDirectory()`, except this one test, because IPFS needed to be installed to test this. 

In this issue, this test needs to be updated.

**Comment by ctb** [comment]
being tackled in #1739.
