### ISSUE TITLE
change name of gather output column `avg_abund` to `avg_cov` or `avg_coverage`

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#1737]
@bluegenes and I just had a conversation in slack trying to figure out what information is represented by the `avg_abund` column in the gather output csv. Using documentation like https://sourmash.readthedocs.io/en/latest/classifying-signatures.html, we figured out that it basically represents average coverage of the genome. We wanted to start a conversation about potentially changing the output column to `avg_cov`, where the documentation would state that it's based on average k-mer abundances. We think this might be more intuitive.

**Comment by ctb** [comment]
two hot takes -

changing column names feels like kind of a big ask (requires major version bump), in relation to providing better documentation.

"abundance" implies "coverage", I think. so it feels more general?

anyway, tagging with 5.0 so we can consider it for major version bump.

**Comment by taylorreiter** [comment]
I think coverage has the connotation of "genome coverage", while abundance could refer to abundance within the genome or metagenome. But the the word "coverage" could be added to the documentation instead of changing the colname so that it carries that connotation?
