### ISSUE TITLE
Prepared databases: scaled=10000 instead of described 1000

### ISSUE THREAD

**Issue by VGalata** [sourmash-bio/sourmash#1745]
Hello,

First of all, thanks a lot for the amazing tool!

I have a rather short question about the prepared databases available on the `sourmash` [web site](https://sourmash.readthedocs.io/en/latest/databases.html#gtdb-all-genomes-258k-genomes). I downloaded the "GTDB all genomes" database (`k=51`, LCA) and assumed that `scaled` was 1000 as mentioned in the description. However, after running `sourmash gather` I got the warning `WARNING: final scaled was 10000, vs query scaled of 1000`. `sourmash sig describe` confirmed that.

I have not checked the other database files, but should they have `scaled=10000` or `scaled=1000`? And if my queries have `scale=1000` will the signatures in the database then be "scaled down" or are the search results now biased in some way?

Thanks in advance!

Best,
Valentina

**Comment by ctb** [comment]
hi valentina,

our mistake - the LCA databases have a scaled of 10,000.

sourmash adjusts the scaled for you.

please leave this issue open and we'll fix the databases page. Thank you!!

best,
--titus

**Comment by VGalata** [comment]
Okay, awesome! Thanks a lot for the quick reply!

**Comment by ctb** [comment]
I took a look at the databases page and the LCA databases are now define as having scaled=10000. So, closing this issue!
