### ISSUE TITLE
error loading genbank-k31.lca.json.gz database

### ISSUE THREAD

**Issue by maguileraf** [sourmash-bio/sourmash#1763]
I get the following error and I am not sure what is going on:
Killedading database /projects/LINbase_BR/databases/genbank-k31.lca.json.gz

Any ideas?

**Comment by mr-eyes** [comment]
Hi,

Please provide the command you have used and the full error message you got.

**Comment by ctb** [comment]
out of memory

**Comment by maguileraf** [comment]
sourmash lca classify --db /projects/LINbase_BR/databases/genbank-k31.lca.json.gz --query ../../sigs/MAG_bins_sigs/669_bin.4.fa.sig 

== This is sourmash version 4.2.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Killedading database /projects/LINbase_BR/databases/genbank-k31.lca.json.gz

**Comment by ctb** [comment]
(the "killed" is almost always because you ran out of memory)

**Comment by maguileraf** [comment]
Yup, increased the memory and it worked!
