### ISSUE TITLE
provide sensible default signature names for `sourmash sig intersect`

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1801]
right now, many of the sig subcommands don't explicitly name the output signatures. Maybe this should change where sensible names can be inferred?

see discussion in https://github.com/sourmash-bio/sourmash/issues/1171#issuecomment-1013688377

**Comment by taylorreiter** [comment]
could we add the `--name` parameter to the command line? I don't dislike the default name, but it would be nice to set the name manually.

**Comment by ctb** [comment]
two or three thoughts -

sure, it's easy enough :). but why not use `sourmash sig merge ... | sourmash sig rename`?

Probably part of the problem is that `--name` isn't part of the set of options that work by default across all of the `sourmash sig` commands. If we put in the effort to add it to `sourmash sig merge` we should consider (a) what other good default options there should be and (b) implementing them in a "standard" way for all of the `sig` subcommands, somewhat like we've done with `-q/--quiet`, `-k`, and the molecule ypes.

Another part of the problem is that the default naming scheme is kinda not good here; it just names it the md5sum. Maybe instead of choosing the default we could print out something helpful like `naming it default; use --name to set the name`.

**Comment by taylorreiter** [comment]
I was mostly just surprised that I got an error with `--name` using `sourmash sig intersect`; seems like there is more to consider than just adding the param. I guess `rename` is fine for this, a little annoying to have two steps but better then not having any options :)

**Comment by ctb** [comment]
Diving into this a little - some fun facts.

* `sig merge` takes `--name` as an argument to name the merged signature.
* `sig extract`, `sig filter`, and `sig flatten` take `--name` arguments that _select_ the signatures to operate on. I don't know if we've ever used this. Might be good to change it up to use some of the other sig selection mechanisms (but, major version change) or eliminate it since `sig grep` supports a more flexible signature selection mechanism anyway;
* I think `sig inflate`, `sig filter`, `sig downsample`, and `sig flatten` keep the signature name from the signature they're operating on; **double check this** and make sure it's tested!

So candidates for a `--name` or `--rename` argument (joining `sig merge`) are:

* `sig intersect`
* `sig subtract`

which is frankly much simpler than I was expecting.

**Comment by ctb** [comment]
`sig intersect` and `sig subtract` support `--set-name` as of today's release of sourmash v4.8.9.
