### ISSUE TITLE
`gather` output is just over 80 characters wide...

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1803]
...which means it wraps on my screen. grr.

**Comment by ctb** [comment]
(it should be 80 char wide exactly. or maybe this should be a parameter.)

**Comment by luizirber** [comment]
:older_man:

**Comment by ctb** [comment]
lol, I _did_ say maybe it should be a parameter... :)

**Comment by ctb** [comment]
git off mah lawn!

**Comment by ctb** [comment]
ISTR there are some libraries out there for columnar output formatting that will automatically adjust for screen size. We should just use those.

**Comment by ctb** [comment]
e.g. tabulate, https://github.com/sourmash-bio/sourmash/issues/389

**Comment by ctb** [comment]
Fixed in #2176.
