### ISSUE TITLE
release notes for sourmash 4.2.4

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1822]
editing here: https://hackmd.io/46Bzn-p8QkidTI71zi9tBg?both

```
git checkout latest
git pull
git log --oneline v4.2.3..latest
```

Medium bug fixes:

* fix bug where `sourmash sketch ... --singleton -o output.sig` drops signatures (#1810)
* fix `sourmash search --containment` with two abund signatures (#1780)
* fix plot/labels/CSV ordering with `sourmash plot --csv` (#1821)

Small bug fixes:

* fix `Index.search_abund` downsampling and filename output (#1820)
* check to make sure that .zip files exist before trying to load from them (#1777)
* fix and test and refactor output information during signature creation (#1826)

Minor new functionality:

* adjust text output of gather to indicate weighted/unweighted results (#1819)
* update `sourmash multigather` to save hash abundances to `.unassigned.sig` (#1720)
* re-inflate prefetch output sketches (#1827)

Cleanup and documentation fixes:

* fix 'sketch' output info (#1794)
* fix PMID for mock metagenome (#1811)
* check to make sure that = is in param strings where necessary (#1775)

Developer updates:

* set pickfile on SourmashPicklist.load (#1776)
* Fix new clippy lints in beta (1.59, next stable) (#1791)
* Rust updates (clippy, MSRV, CI, wasm-pack) (#1786)
* disable the `fix_lint` component of the py38 tests in `tox.ini` (#1823)

**Comment by mr-eyes** [comment]
`sourmash gather --help` is not showing the new `avg_abund` column.

**Comment by ctb** [comment]
> `sourmash gather --help` is not showing the new `avg_abund` column.

sorry, which PR is this in relation to, or is this something that is a blocker for a release, or?

**Comment by mr-eyes** [comment]
I did install `pip install git+https://github.com/sourmash-bio/sourmash.git`.

```
❯ sourmash --version
sourmash 4.2.4.dev16+ge3804f2
```

**Comment by ctb** [comment]
perhaps I should rephrase: why are you posting this in the release notes issue? does it have to do with the release?

**Comment by mr-eyes** [comment]
Sorry, I should have posted in a separate issue :)

**Comment by ctb** [comment]
ahh! ok :)

**Comment by ctb** [comment]
v4.2.4 is released and wending its way through conda-forge and bioconda 🎉

**Comment by ctb** [comment]
> Sorry, I should have posted in a separate issue :)

punted to https://github.com/sourmash-bio/sourmash/issues/1831
