### ISSUE TITLE
`prefetch` can't parse SBT in a different directory name

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#1829]
In `sourmash prefetch`, loading a directory containing an SBT index will fail if the directory name is different from the SBT prefix.

A suggested fix would be one of these:
	- Printing a warning to the user.
	- Error and specifying the wrong behavior.
	- Allowing the behavior.
	- Make the index prefix a parameter alongside the directory name (In case a directory contains multiple SBTs).

The current directory structure must be:
```
{PREFIX}
├── {PREFIX}.sbt.json
└── .sbt.{PREFIX}
```

**Comment by ctb** [comment]
hi @mr-eyes I see that the following all works for me -

```
mkdir aaa
sourmash index aaa/bbb.sbt.json tests/test-data/prot/protein.zip 
sourmash prefetch tests/test-data/prot/protein/GCA_001593925.1_ASM159392v1_protein.faa.gz.sig aaa/bbb
sourmash prefetch tests/test-data/prot/protein/GCA_001593925.1_ASM159392v1_protein.faa.gz.sig aaa/bbb.sbt.json

mv aaa ccc
sourmash prefetch tests/test-data/prot/protein/GCA_001593925.1_ASM159392v1_protein.faa.gz.sig ccc/bbb.sbt.json 
sourmash prefetch tests/test-data/prot/protein/GCA_001593925.1_ASM159392v1_protein.faa.gz.sig ccc/bbb
```

does that work for you?

if it does, could you paste in the commands that led to your initial error?

**Comment by mr-eyes** [comment]
Yes, that worked for me. So basically, I was passing the directory name of the SBT without the dir/sbt_prefix and accidentally I was having the SBT itself in my current working directory. The problem was totally from my side and the files structure. Sorry!

**Comment by ctb** [comment]
no worries, better safe than sorry - command lines are good to report in issues for exactly this reason, tho :)
