### ISSUE TITLE
How to read the containment matrix?

### ISSUE THREAD

**Issue by ZeweiSong** [sourmash-bio/sourmash#1835]
Hi,

If I got a containment matrix as:
     a     b
a   1     0.3
b   0.6  1

Am I right that C(a,b) = 0.3, and C(b,a) = 0.6? Or instead the reverse is true?

Thanks!

Zewei

**Comment by ctb** [comment]
hi @ZeweiSong, dug into the code a little bit to be sure -- 

per https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/compare.py#L58,

C(a, b) = containment of b in a

I did the following:

```
% sourmash sig merge tests/test-data/47.fa.sig tests/test-data/63.fa.sig -o 47-63-merge.sig
% sourmash search tests/test-data/47.fa.sig 47-63-merge.sig --containment
...
similarity   match
----------   -----
100.0%       491c0a81

% sourmash compare tests/test-data/47.fa.sig 47-63-merge.sig --containment --csv mat.csv

0-NC_009665.1 She...    [1.    0.656]
1-491c0a81              [1. 1.]
min similarity in matrix: 0.656

% cat mat.csv
"NC_009665.1 Shewanella baltica OS185, complete genome",491c0a81
1.0,0.6564798376870403
1.0,1.0
```

and so to articulate more clearly for myself 😆 ,

the value in row a for column b is the containment of the sketch b in sketch a.

**Comment by ctb** [comment]
actually I'll leave this open for a doc update :)

**Comment by ZeweiSong** [comment]
Thanks! I figured it out today the similar way like what you did : )

**Comment by ctb** [comment]
"Trust but verify" :)
