### ISSUE TITLE
Trouble having results with `lca summarize` when using custom DB

### ISSUE THREAD

**Issue by patriciatran** [sourmash-bio/sourmash#1842]
Hello!

I am trying to `run lca summarize` on a custom built LCA database, but the output is always a file with a single header line. 
The command I'm using is `sourmash lca summarize --db my_database.lca.json --query output_sourmash/*.sig --threshold 1 -o [outfile]`

The db was built using:
`sourmash sketch dna -p scaled=1000,k=31 /storage1/data10/Metagenome/Final_Bin_Set/*.fasta`
then:
`cd ..`
`sourmash index final_bin_set_mendota2020_kmer31_db final_bin_set_kmer31/*.sig --dna -k 31`
The LCA index was built using:
`sourmash lca index -f Tran_MAG_taxonomy.csv my_database.lca.json final_bin_set_kmer31/*.sig`
The taxonomy follows the example in the tutorial for the TARA ocean 2017 project.

I ran the `lca summarize` command with the genbank db like in the tutorial, as well as the Delmont TARA ocean database, and the GTDBTk LCA database downloaded on your website, and all those worked fine and was ablel to get results in the `csv` file . So I think it has to do with the way I built my LCA database. Do you have any insight on what I could do differently please?

Thanks!

Patricia

**Comment by ctb** [comment]
hi @patriciatran! thanks for filing an issue!

what does
```
sourmash lca rankinfo my_database.lca.json 
```
return?

and do you get any output if you do
```
sourmash search --containment --threshold=0 any_sig.sig my_database.lca.json
```
?

thanks!

**Comment by patriciatran** [comment]
Hi, thanks for your quick reply!
I get:
```
(soursmash) patricia@sulfur:/storage1/data10/test_runs/soursmash$ sourmash lca rankinfo my_database.lca.json 

== This is sourmash version 4.2.4. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 1 LCA databases. ksize=31, scaled=10000 moltype=DNA
(no hashvals with lineages found)
```

and the second command gives me

```
(soursmash) patricia@sulfur:/storage1/data10/test_runs/soursmash$ sourmash search --containment --threshold=0 output_sourmash/*.sig my_database.lca.json 

== This is sourmash version 4.2.4. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

select query k=31 automatically.
loaded query: /slowdata/Reads/Paired_Bact_Vi... (k=31, DNA)
loaded 15 signatures and 1 databases total.

444 matches; showing first 3:
similarity   match
----------   -----
 31.8%       .../52494.2.360304.GTCTGATC-GTCTGATC.filter-METAGENOME.fastq
 30.4%       .../52494.2.360304.ACGACAGA-ACGACAGA.filter-METAGENOME.fastq
 28.8%       .../52494.2.360304.ACATTGCG-ACATTGCG.filter-METAGENOME.fastq
```

**Comment by ctb** [comment]
OK! I hadn't thought of it this way, but rankinfo is a good debugging approach 😆 

So it seems like you _do_ have matches, but _not_  to anything with taxonomic lineages attached. So that suggests that this:

> The LCA index was built using:
> `sourmash lca index -f Tran_MAG_taxonomy.csv my_database.lca.json final_bin_set_kmer31/*.sig`
> The taxonomy follows the example in the tutorial for the TARA ocean 2017 project.

is where the problem lies. Could you try subselecting 2-3 rows from `Tran_MAG_taxonomy.csv` and use that to build an LCA database, and then paste some or all of the output from that here?

**Comment by ctb** [comment]
actually, an addendum: it looks a lot like the sequence names (e.g. `.../52494.2.360304.GTCTGATC-GTCTGATC.filter-METAGENOME.fastq`) are probably not correct in terms of the sample identifiers. Can you try setting them with `sourmash sketch dna --name-from-first` per the advice [here](https://dib-lab.github.io/genome-grist/configuring/#preparing-information-on-local-genomes)? Basically, the identifiers in the taxonomy CSV would need to match to the identifier (space-delimited) on the first sequence in each genome bin.

**Comment by ctb** [comment]
more addendum: you want `sourmash sig describe` on a sourmash signature file to show a `signature name:` that contains the right identifier as the first space-separated word in the signature name.

here, the "right identifier" is the identifier used in the taxonomy spreadsheet.

**Comment by patriciatran** [comment]
Hello!

(**TLDR: issue resolved! It involved having only the MAG name that matches the first column in the taxonomy csv file, and nothing else in the headers (no scaff name, etc.). Writing my full steps here in case someone has a similar issue. Thanks!**)

I tried a couple of things as per your comment in this thread:

I have a folder with MAGS (.fasta) that I made some signatures with (*.sig) and I want to use those to make a LCA DB. Following your instructions, I appended the MAG identifier to the fasta headers, separated with a space
```
sourmash sketch dna -p scaled=1000,k=31 --name-from-first /storage1/data10/test_runs/soursmash/mags_to_make_by_db_from/renamed/*.fasta
```
For example: the fasta headers were: 
```
>Ga0485167_metabat2_ours.023 Ga0485167_0000610
CCGGTGCCACGCTCAACGGCTCGGCTTCCGATGACGGCCTGCCCA
```

Next I went back to my working folder and made the LCA index using the signatures of the MAGS I just created:
```
sourmash lca index -f Tran_MAG_taxonomy.csv my_mags_final_bin_set_mendota2020 signatures_final_bin_set_16FEB2022/*.sig
```

To give you an example, here are 2-3 lines of my `.csv` file:
```
ident,superkingdom,phylum,class,order,family,genus,species
Ga0485159_metabat2_ours.113,Bacteria,Patescibacteria,Paceibacteria,SW-4-49-11,SW-4-49-11,na,na
Ga0485163_metabat2_jgi.030_sub,Bacteria,Patescibacteria,WWE3,2-01-FULL-39-13,2-01-FULL-39-13,na,na
```
This is what is shown when I try to run `lca index` command:
```
Building LCA database with ksize=31 scaled=10000 moltype=DNA.
examining spreadsheet headers...
** assuming column 'ident' is identifiers in spreadsheet
431 distinct identities in spreadsheet out of 431 rows.
263 distinct lineages in spreadsheet out of 431 rows.
... loaded 431 signatures.
loaded 116890 hashes at ksize=31 scaled=10000
0 assigned lineages out of 263 distinct lineages in spreadsheet.
0 identifiers used out of 431 distinct identifiers in spreadsheet.
saving to LCA DB: my_mags_final_bin_set_mendota2020.lca.json
WARNING: no lineage provided for 431 signatures.
WARNING: no signatures for 431 spreadsheet rows.
WARNING: 263 unused lineages.
WARNING: 431 unused identifiers.
```

So, it seems that the signatures names still aren't found as shown above.
`sourmash sig describe signatures_final_bin_set_16FEB2022/*.sig`
gives me:
```
---ded 1 signatures from 'signatures_final_bin_set_16FEB2022/Ga0485172_metabat2_ours.101.fasta.sig'
signature filename: signatures_final_bin_set_16FEB2022/Ga0485172_metabat2_ours.152.fasta.sig
signature: Ga0485172_metabat2_ours.152 Ga0485172_0002220
```
So it seems like the signature read includes the portion after the space, and not just the MAG name.
After removing the scaffold name from each fasta files, `lca rank info` gives me this:
```
loaded 1 LCA databases. ksize=31, scaled=10000 moltype=DNA
superkingdom: 423 (0.4%)
phylum: 55 (0.0%)
class: 567 (0.5%)
order: 4171 (3.6%)
family: 21897 (18.7%)
genus: 78912 (67.5%)
species: 10865 (9.3%)
strain: 0 (0.0%)
```
which makes much more sense!

Finally, what I wanted to do was to find was taxa were in my metagenomes: using from my MAG_DB that I just built (.lca.json) and my metagenomic reads (output_sourmash/*.sig -- named with the FASTQ named....):
``
sourmash lca summarize --db my_mags_final_bin_set_without_scaff_name_mendota2020.lca.json --query output_sourmash/*.sig --threshold 1 -o lca_summarize_mendota_metagenomes_vs_my_final_bin_set.csv
``
which gave me a complete CSV file with the count for each "taxa" in all my metagenomes (reads fastq files).

Thank you!!

Patricia

**Comment by ctb** [comment]
awesome, thank you very much for letting us know!

I don't see the exact lca index command in there but I should have suggested you add in `--split-identifiers` to break off the identifiers from the names...
