### ISSUE TITLE
provide simple/standard command-line pattern matching for search and gather.

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1865]
(extracted from https://github.com/sourmash-bio/sourmash/issues/1075#issuecomment-869002447)

@bluegenes and I talked a bit in a teleconference about the idea of adding generic pattern matching for inclusion/exclusion of signatures from search, building off of picklists and manifests. Hot take UX:

```
sourmash gather --exclude GCA_0583288 ...
sourmash gather --include GCA_0583288 ...
```

this could be readily implemented as part of the picklist API, and/or take inspiration from the functionality of `sig grep` (#1075 / #1864), which works on manifests.

**Comment by bluegenes** [comment]
+1 (which I guess is already obvious). But to lay out a use case -- this sort of include/exclude would vastly simplify database searches with a sig that may be present in the database. We can picklist exclude already of course, but who wants to make a whole file when you just wrote up with a lovely way to ... not do that! 🙂

**Comment by ctb** [comment]
a nice way to enable this would be to refactor the pattern matching functionality in `sig grep` so that it was a set of methods on `CollectionManifest`; then we could do the 'manifest to subset manifest (via manifest grep) to picklist' dance.

**Comment by ctb** [comment]
I ended up implementing two `CollectionManifest` methods in #1864, `filter_rows` and `filter_on_columns`, that should make this straightforward.
