### ISSUE TITLE
Consistent over-estimate bias for large hash sizes

### ISSUE THREAD

**Issue by dkoslicki** [sourmash-bio/sourmash#187]
There may be a subtle error in the way sourmash is estimating the Jaccard index. In Theorem 1 of the [Broder paper](http://gatekeeper.dec.com/ftp/pub/dec/SRC/publications/broder/positano-final-wpnums.pdf) (and in the [Mash paper](http://download.springer.com/static/pdf/329/art%253A10.1186%252Fs13059-016-0997-x.pdf?originUrl=http%3A%2F%2Fgenomebiology.biomedcentral.com%2Farticle%2F10.1186%2Fs13059-016-0997-x&token2=exp=1492732863~acl=%2Fstatic%2Fpdf%2F329%2Fart%25253A10.1186%25252Fs13059-016-0997-x.pdf*~hmac=892764d5954378d0a874da2c48ae2fb6c91b30248d6012f9ea068c97ffefd0b6)), the Jaccard index is estimated as (in pseduo-code):
```python
len(hash_list1.union(hash_list2)[0:k].intersect(hash_list1.intersect(hash_list2))) / float(k)
```
It appears that sourmash is using:
```python
len(hash_list1.intersect(hash_list2)) / float(k)
```
to estimate the Jaccard index. I hypothesized that this will lead to a consistent over-estimate of the Jaccard index for larger hash lists. I put together [a test script](https://gist.github.com/dkoslicki/7ab359cb1b7fe931ee7135e6ffd2d768) to see if this was the case, and indeed sourmash appears to be consistently over-estimating the Jaccard index. The following figures (generated by [that test script](https://gist.github.com/dkoslicki/7ab359cb1b7fe931ee7135e6ffd2d768)), demonstrate that fact:
![histogram](https://cloud.githubusercontent.com/assets/6362936/25257216/3d4e4436-25eb-11e7-852d-02ff0114bc21.png)
![differences](https://cloud.githubusercontent.com/assets/6362936/25257219/450fe58a-25eb-11e7-9130-d4def1c6dce5.png)

I'm pretty sure the root cause is in [this part of the sourmash code](https://github.com/dib-lab/sourmash/blob/1033479f841afbd6acf3b7f06d64ed3319b115dc/sourmash_lib/kmer_min_hash.hh#L257) since the intersection should only be computed for the first ``k`` elements of the union of the hash lists.

I don't speak C++, otherwise I'd offer a solution.

**Comment by ctb** [comment]
thanks @dkoslicki - we may have fixed this 2 days ago ;). See https://github.com/dib-lab/sourmash/pull/150, which is now merged.

As of that merge, sourmash and mash agree on some test data sets.

**Comment by ctb** [comment]
(as in, I have found no test data sets on which they disagree!)

**Comment by dkoslicki** [comment]
Interesting! I did do the experiments using a fresh pull, so I did get the changes of #150. I wonder if, even though Mash says in their [paper](http://download.springer.com/static/pdf/329/art%253A10.1186%252Fs13059-016-0997-x.pdf?originUrl=http%3A%2F%2Fgenomebiology.biomedcentral.com%2Farticle%2F10.1186%2Fs13059-016-0997-x&token2=exp=1492734924~acl=%2Fstatic%2Fpdf%2F329%2Fart%25253A10.1186%25252Fs13059-016-0997-x.pdf*~hmac=75a7bd9fcdbaba364404a38d4619303e555540710dd8e1ab180e87b34ed9655b) (page 10, equation (3)) that they only use ``k`` hashes from the union to compute the intersection, the code doesn't actually implement this (I haven't looked into this). In any case, as it stands, there is certainly a small, but noticeable bias in the Jaccard estimates (when it should be an unbiased estimate). Thankfully, for smaller hash list lengths, this bias is quite negligible.

**Comment by ctb** [comment]
ok - thanks for checking, and extra thanks for being so careful in the first
place!  I will look into it... but maybe not for a week or two :)

**Comment by ctb** [comment]
"a week or two" => 1.5 years...

but in any case I see the same thing. (Note, this script works with only a few minor changes for Python 3 and sourmash_lib => sourmash.)

**Comment by ctb** [comment]
OK, so I dug into the code a bit more, and I noticed that the TestBias script doesn't deal with canonical forms of k-mers; see [utils/compute-dna-mh-another-way.py](https://github.com/dib-lab/sourmash/blob/master/utils/compute-dna-mh-another-way.py) for the right Python code.

FWIW, the following code should create a MinHash that calculates an exact Jaccard similarity, without discarding any k-mers:

```
sourmash.MinHash(n=0, ksize=ksize, scaled=1)
```

**Comment by ctb** [comment]
Huzzah, the canonicalization fixes things! We now get the expected symmetric set of differences.

![histogram](https://user-images.githubusercontent.com/51016/50599134-f960d480-0e61-11e9-87ab-8077fec89424.png)
![differences](https://user-images.githubusercontent.com/51016/50599135-f960d480-0e61-11e9-924d-ffe504051269.png)

Note this is _different_ from the question as to whether we are doing the correct thing, or the same thing as mash. It just saying that we don't see a systematic under or over estimate...

**Comment by ctb** [comment]
closing - we've spent a lot of time recently investigating the overall accuracy, and we're on pretty solid ground.
