### ISSUE TITLE
Add the `-A` flag to `sourmash sig subtract` to allow for signature subtraction from signatures with abundance tracking

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#1888]
I just tried to subtract a signature (a set of core genes) from another signature (a transcriptome), with the goal of getting track abund hashes from all expressed genes that were not in the core genome. I got the error, `Cannot use subtract on signatures with abundance tracking, sorry!` Would it be possible to add an `-A` flag like `sourmash sig intersect` has, so I could choose which signature to inherit abundances from??

**Comment by ctb** [comment]
yep - you want to subtract the hashes in a boolean fashion (present/not present), and then inherit the abundances on remaining hashes?

**Comment by taylorreiter** [comment]
yes exactly!

**Comment by ctb** [comment]
working on it over here: https://github.com/sourmash-bio/sourmash/pull/1889.

I have a bit more to do to round out the PR, but the current code should work. Also see the new `sourmash sig inflate` 😁
