### ISSUE TITLE
Creating signatures with tar.bz2 files

### ISSUE THREAD

**Issue by krastegar** [sourmash-bio/sourmash#1927]
Hi I have around 750 metagenome sequences in tar.bz2 files. Everytime I try to create a signature for these archives I get a ValueError: unknown file format for 'SRS015038.tar.bz2'. I was hoping if you guys could tell me a way to pipe bzcat into the sourmash sketch command that way it can bypass the unknown file format error

**Comment by ctb** [comment]
hi @krastegar, this is one of the input formats that sourmash _can't_ open directly, I'm afraid 😄 . It's a compound file format that has multiple files in each file, like a zip file.

To view the list of files in the .tar.bz2 archive, do `tar tjvf <filename>`. To unpack them, do `tar xjvf <filename>`. If the unpacked files are FASTQ or FASTA you can feed them into sourmash from there.

Please update us on the output and happy to help more once you know what's in the .tar.bz2 files!

**Comment by krastegar** [comment]
Hi @ctb, in each .tar.bz2 file there are 3 fastq files: samplename.trimmed.1.fastq, samplename.trimmed.2.fastq, samplename.trimmedsingleton1.fastq. The issue is unpacking all of the tar.bz2 files takes up too much storage space. So I was hoping I could pipe bzcat command with sourmash, but I don't know if this is feasable

**Comment by ctb** [comment]
hi @krastegar gotcha.

I haven't tried this myself yet, but riffing off of https://www.gnu.org/software/tar/manual/html_node/Writing-to-Standard-Output.html, you could do:
```
tar -xOjf file.tar.bz2 | sourmash sketch dna - -merge output.sig
```
It's not working for my on my Mac laptop, and I don't have ready access to a Linux box right now.

But, if you can get:
```
tar -xOjf file.tar.bz2 | head
```
to show you FASTQ sequence, the above should work!

If not, I can probably whip you up a quick Python script that will read through the tar file and pull out the sequence files in memory. But please try the above first :)

**Comment by luizirber** [comment]
> ```
> tar -xOjf file.tar.bz2 | sourmash sketch dna - -merge output.sig
> ```

heh, I was about to suggest that =P

> It's not working for my on my Mac laptop, and I don't have ready access to a Linux box right now.

Default `tar` in macOS is BSD `tar`, it might work with `gtar` (from `brew install gnu-tar`)

**Comment by ctb** [comment]
not conda-installable :(.

**Comment by krastegar** [comment]
Thanks for the advice! So I tried tar -xOjf file.tar.bz2 | head and I can see the sequences, but I can't pipe it into the sourmash command that you gave me. It says that the merge command was not found

**Comment by ctb** [comment]
Yep, I have a typo in there - it should be two dashes before merge, and I also messed up the arguments. Sorry! Try this:
```
... | sourmash sketch dna - --merge somename -o output.sig
```
Here, `somename` will be the name of the output signature, and `output.sig` will be the filename to which it will be saved.

**Comment by krastegar** [comment]
so this is the code I put`for i in *; do tar -x0jf $i | sourmash sketch dna - --merge somename -o output.sig; done
` 
The error that I received was this: 

computing signatures for files: -
Computing a total of 1 signature(s) for each input.
... reading sequences from -
no sequences found in '-'?!
tar: Options '-[0-7][lmh]' not supported by *this* tar
Try 'tar --help' or 'tar --usage' for more information.

I also took out the dash:
``for i in *; do tar -x0jf $i | sourmash sketch dna $i --merge somename -o output.sig; done
and this is the error I get: 
ValueError: unknown file format for 'SRS015059.tar.bz2' (this is the first file in my directory that I am looping through)

**Comment by ctb** [comment]
ugh, looks like your tar doesn't support the output-to-stdout option. I'll see if I can pull together a script in a bit; might take me a few days.

In the meantime, you could try unpacking things to a /tmp or /scratch directory that might have more space for temporary files.

**Comment by ctb** [comment]
Had a few minutes, felt like exploring the `tarfile` module, worked out ok ;)

Here's the code:
```python
#! /usr/bin/env python3
import tarfile
import sys

BUFSIZE=1024*1024*10

# using https://docs.python.org/3/library/tarfile.html

with tarfile.open(sys.argv[1], "r:bz2") as tf:
    for m in tf.getmembers():
        fp = tf.extractfile(m)
        data = fp.read(BUFSIZE)
        while data:
            sys.stdout.write(data.decode('utf-8'))
            data = fp.read(BUFSIZE)
```

I put it in a file named `sketch-tar.py` and then ran:
```shell
python sketch-tar.py xyz.tar.bz2 | sourmash sketch dna - -o xyz.sig --merge xyz
```
and verified the `xyz.sig` output was identical to running the `sourmash sketch` command on the original files.

Hope that helps! Report back either way!

**Comment by ctb** [comment]
(lightly updated the code, pls take from the issue - should have `python3` in the first line, as well as `BUFSIZE` in the `fp.read(...)` lines)

**Comment by krastegar** [comment]
Thank you again for the help, unfortunately this method did not work as well, 
the code i used: 
`python3 sketch-tar.py SRS024470.tar.bz2 | sourmash sketch dna - -o xyz.sig --merge xyz`

the error I got: 
`AttributeError: 'NoneType' object has no attribute 'read'
no sequences found in '-'?!`

my sketch-tar.py:
```
#! /usr/bin/ python3
import tarfile
import sys

BUFSIZE=1024*1024*10

# using https://docs.python.org/3/library/tarfile.html

with tarfile.open(sys.argv[1], "r:bz2") as tf:
    for m in tf.getmembers():
        fp = tf.extractfile(m)
        data = fp.read(BUFSIZE)
        while data:
            sys.stdout.write(data.decode('utf-8'))
            data = fp.read(BUFSIZE)
```

**Comment by ctb** [comment]
that's very weird - seems like for whatever reason the `fp = tf.extractfile(m)` line isn't working, so `fp` is None 🤔 .

reading the docs, this can occur if there are oddball files in the tar.

Try this one adjustment and lmk --
```python
#! /usr/bin/env python3                                                         
import tarfile
import sys

BUFSIZE=1024*1024*10

# using https://docs.python.org/3/library/tarfile.html                          

with tarfile.open(sys.argv[1], "r:bz2") as tf:
    for m in tf.getmembers():
        fp = tf.extractfile(m)
        if fp is None:
            print(f"skipping {m}", file=sys.stderr)
        else:
            print(f"reading {m}", file=sys.stderr)

        data = fp.read(BUFSIZE)
        while data:
            sys.stdout.write(data.decode('utf-8'))
            data = fp.read(BUFSIZE)
```

**Comment by krastegar** [comment]
Hi, 

Sorry for the late reply. I did make the adjustments like you said and I still get this error: 
computing signatures for files: -
Computing a total of 1 signature(s) for each input.
... reading sequences from -
no sequences found in '-'?!

**Comment by ctb** [comment]
huh. what do you see when you do:
```
python3 sketch-tar.py SRS024470.tar.bz2  | head
```
? do you see anything that looks like sequence data?

**Comment by krastegar** [comment]
This is what happens. 

Traceback (most recent call last):
  File "/mnt/HDD/kia/HMP_reference/sketch-tar.py", line 12, in <module>
    data = fp.read(BUFSIZE)
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by krastegar** [comment]
when I run `bzcat SRS024470.tar.bz2 | head` I get this output

SRS024470/0002775000176000017500000000000011553344057011063 5ustar  vfelixigsSRS024470/SRS024470.denovo_duplicates_marked.trimmed.singleton.fastq0000644000176000017500101653135611553344065023765 0ustar  vfelixigs@61HHCAAXX100518:5:100:10008:14724/2
CGCAAGAAAGACTGCAACATCTGCTACTTCTTCTGTATTTCCAAATCGTTTCATTGGAATTTGAGCGAGAGACATTTCTTTAATTTTTTCC
+61HHCAAXX100518:5:100:10008:14724/2
257/2,2727348?;?33<39<2=2;77382;;<36*2/23;,+;BB1+B;*6A3+>1B+?B*?1<9(2>9B?1*615>B@0BAA@>=@B#
@61HHCAAXX100518:5:100:10024:11589/2
AAATAATTAAAAAGAGAGTTTCTGGGGAACAAGAAGAAAAGAAAAAAGAAAAAAACAACAAAACAGAACAACACCACCGTGACGTACACACAC
+61HHCAAXX100518:5:100:10024:11589/2
222<::922;+<41)6*75<?6:9+**0:*2?====@75742A==++::+==41;/64:?>:>@>:7?7AA@*:@?2700;@@2@@21221A#
@61HHCAAXX100518:5:100:10039:3612/2
GCCAGCTGGCGTTCTGTAAAATTTGGCGAACTGATGCTTACATATTTCAGTAACTGACTAGCGATTTCTTTCAGATCTTTAGCCGTCATTTTATTACTTCG

**Comment by ctb** [comment]
argh that's because I gave you broke code. I'm terrible.

There should be additional output above the traceback, starting with 'skipping ...' - what does that say?

In any case, pls try below:
```python
#! /usr/bin/env python3
import tarfile
import sys

BUFSIZE=1024*1024*10

# using https://docs.python.org/3/library/tarfile.html

with tarfile.open(sys.argv[1], "r:bz2") as tf:
    for m in tf.getmembers():
        fp = tf.extractfile(m)
        if fp is None:
            print(f"skipping {m}", file=sys.stderr)
            continue
        else:
            print(f"reading {m}", file=sys.stderr)

        data = fp.read(BUFSIZE)
        while data:
            sys.stdout.write(data.decode('utf-8'))
            data = fp.read(BUFSIZE)
```

**Comment by krastegar** [comment]
The 💯 is :100:

**Comment by krastegar** [comment]
I think it worked! the output is shown below

skipping <TarInfo 'SRS024470' at 0x7fa0fd561ac0>
reading <TarInfo 'SRS024470/SRS024470.denovo_duplicates_marked.trimmed.singleton.fastq' at 0x7fa0fd4e5a00>
@61HHCAAXX100518:5:100:10008:14724/2
CGCAAGAAAGACTGCAACATCTGCTACTTCTTCTGTATTTCCAAATCGTTTCATTGGAATTTGAGCGAGAGACATTTCTTTAATTTTTTCC
+61HHCAAXX100518:5:100:10008:14724/2
257/2,2727348?;?33<39<2=2;77382;;<36*2/23;,+;BB1+B;*6A3+>1B+?B*?1<9(2>9B?1*615>B@0BAA@>=@B#
@61HHCAAXX100518:5:100:10024:11589/2
AAATAATTAAAAAGAGAGTTTCTGGGGAACAAGAAGAAAAGAAAAAAGAAAAAAACAACAAAACAGAACAACACCACCGTGACGTACACACAC
+61HHCAAXX100518:5:100:10024:11589/2
222<::922;+<41)6*75<?6:9+**0:*2?====@75742A==++::+==41;/64:?>:>@>:7?7AA@*:@?2700;@@2@@21221A#
@61HHCAAXX100518:5:100:10039:3612/2
GCCAGCTGGCGTTCTGTAAAATTTGGCGAACTGATGCTTACATATTTCAGTAACTGACTAGCGATTTCTTTCAGATCTTTAGCCGTCATTTTATTACTTCG
Traceback (most recent call last):
  File "/mnt/HDD/kia/HMP_reference/sketch-tar.py", line 20, in <module>
    sys.stdout.write(data.decode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by krastegar** [comment]
I am just concerned with the BrokenPipeError? would I be able to use this script in a for loop?

**Comment by ctb** [comment]
yay! now try piping it into sourmash sketch as above and let's see what happens 😆

**Comment by ctb** [comment]
the BrokenPipeError comes from `head` refusing to read more than 10 lines. It shouldn't happen in the full sketching.

**Comment by krastegar** [comment]
@ctb ........YOU ARE GENIUS. I am privileged to have been in the same chat as GREATNESS. It produced the signature (if you couldnt tell by my excitement)

**Comment by ctb** [comment]
😆 excellent! I'll close this for now ;), but please reopen or file new issue if you run into problems!
