### ISSUE TITLE
benchmark cmd `tox -e asv` requires `python=3.10`

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#1937]
When benchmarking using `tox -e asv` on my `python 3.9` env, it requires a specific python version of `3.10` as described in the following error.

```sh
· No executable found for python 3.10
· No environments selected
```

**Comment by luizirber** [comment]
Ah, indeed, it is in https://github.com/sourmash-bio/sourmash/blob/d1d8397c9f015a5acf317b83877fc51e44b78b5f/asv.conf.json#L9

(I tried to default all dev to the newest Python version we support in https://github.com/sourmash-bio/sourmash/pull/1839)

Maybe removing that lines works better, according to [docs](https://asv.readthedocs.io/en/stable/asv.conf.json.html#pythons):
> The versions of Python to run the benchmarks in. If not provided, it will to default to the version of Python that the asv command (master) is being run under.
