### ISSUE TITLE
TODO items for next minor release of sourmash (v4.4.0)

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1942]
@luizirber spake in re arm64 arch support (https://github.com/sourmash-bio/sourmash/pull/1935 and https://github.com/conda-forge/sourmash-minimal-feedstock/pull/28),

>I also discovered there is an easier way to do it on conda, will merge next time we release sourmash

**Comment by luizirber** [comment]
partial solution: https://github.com/luizirber/sourmash-minimal-feedstock/commit/2d82ee73298f0538b215a9d3fa4bca56156af009
(can also uncomment the `NO_BUILD` and `DYLD_LIBRARY_PATH` lines)

**Comment by ctb** [comment]
@luizirber did this get added?

**Comment by luizirber** [comment]
Yup.
