### ISSUE TITLE
can we remove khmer tests?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1947]
the khmer compatibility tests are failing, probably because we no longer keep khmer releases up to date, but we no longer use khmer internally except in one location in `nodegraph.py`. Can we remove the khmer compat tests?

**Comment by ctb** [comment]
@luizirber the only code that still uses khmer is in `src/sourmash/nodegraph.py:Nodegraph.to_khmer_nodegraph()`.

**Comment by luizirber** [comment]
I'm OK with removing it
