### ISSUE TITLE
Sourmash Gather command

### ISSUE THREAD

**Issue by krastegar** [sourmash-bio/sourmash#1975]
Hi I am having issues reproducing a graph that I found in one of your guy's papers with my own data set. I was hoping if you could walk me through the process of how you made this image (figure 2): https://dib-lab.github.io/2020-paper-sourmash-gather/

**Comment by ctb** [comment]
hi @krastegar! The Jupyter notebook to build that figure is here,

https://github.com/dib-lab/2021-paper-sourmash-gather-pipeline/blob/latest/gather/gather_report.ipynb

and I think all you will need beyond the gather output is the names dataframe. I'll send you the info over the weekend, but you might also look into https://github.com/dib-lab/genome-grist, which is what we actually use in the paper to generate the raw data files.

More soon!

**Comment by krastegar** [comment]
Ok thank you @ctb ! I also was wondering how the gather command works? If I have a 600 fastq files does it pick a Sequence from the lca database and that most accurately represents my entire 600Sequences? and then picks the a set of sequences from my data set that represents the one chosen from the database?

**Comment by ctb** [comment]
600 sequences -> k-mers -> sketch (scaled downsampling of k-mers)

Then find sequence that contains most k-mers in sketch. Remove found k-mers from sketch.
Repeat.

:)

**Comment by krastegar** [comment]
I guess I am still confused. Does this mean that its finding sequences in my data set (600seq) and removing the kmers from the sequence that has the most kmers?

**Comment by ctb** [comment]
I totally failed to follow up here, my apologies; but based on https://github.com/sourmash-bio/sourmash/issues/2205 you figured it out! Closing.
