### ISSUE TITLE
Failing _future_ tests due to `pyparsing` package recent update

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#1976]
PR #1955 introduced using `pyparsing.original_text_for`, However, they updated `original_text_for` to `originalTextFor` which solved the problem running tests on my machine.

https://github.com/pyparsing/pyparsing/blob/a73e4d25cbd4e7bb39b56a608023bc7815d95bab/docs/whats_new_in_3_0_0.rst?plain=1#L680

**Comment by mr-eyes** [comment]
I think this issue can be resolved by either fixing the pyparsing version in the `requirements.txt` or updating the single line that uses it.

**Comment by luizirber** [comment]
But is `original_text_for` even used? it was imported, but can't find it anywhere in the file.

I removed it in #1974, will merge when tests pass.

**Comment by mr-eyes** [comment]
> But is `original_text_for` even used? it was imported, but can't find it anywhere in the file.
> 
> 
> 
> I removed it in #1974, will merge when tests pass.

I should have noticed that 😆 thank you @luizirber

**Comment by bluegenes** [comment]
I think it got added accidentally 🤦🏼‍♀️ - thanks for tracking this down and fixing!
