### ISSUE TITLE
slim down tests that are run on _every_ PR

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#1999]
We run an awful lot of tests. Maybe we can run some of these on `latest` once a week or something?

I think -
* wheel building
* dev env instructions
* metadata checks

**Comment by luizirber** [comment]
Maybe [this example](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1) from the GH actions documentation for running only when the PR is merged?

Once a week sounds a bit too late and accumulate errors that will be more trouble to fix.

**Comment by mr-eyes** [comment]
@luizirber this sounds good.
I was thinking to trigger those actions upon renaming to [MRG]. https://github.com/marketplace/actions/pr-title-checker

**Comment by ctb** [comment]
> 

Agree, sounds good.

Once a day would also be fine :).

**Comment by luizirber** [comment]
> Once a day would also be fine :).

We do run them daily, but we need more people checking results (and reverting PRs/fixing problems)

> @luizirber this sounds good. I was thinking to trigger those actions upon renaming to [MRG]. https://github.com/marketplace/actions/pr-title-checker

Nice! We can also trigger them when someone approves the PR (which is doable without external actions)

**Comment by ctb** [comment]
On Wed, Apr 27, 2022 at 08:12:37AM -0700, Luiz Irber wrote:
> > Once a day would also be fine :).
> 
> We do run them daily, but we need more people checking results (and reverting PRs/fixing problems)

Has this been a problem? I do get the notifications, and I get around to
fixing it eventually, if no one else does.

**Comment by ctb** [comment]
dependabot behavior adjusted in https://github.com/sourmash-bio/sourmash/pull/2142

**Comment by ctb** [comment]
this was tackled in a variety of PRs, including #2138, #2142, and https://github.com/sourmash-bio/sourmash/pull/2087.
