### ISSUE TITLE
What to do about untrustworthy jaccard --> ANI estimates?

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2004]
When estimating ANI from Jaccard (only for `scaled` jaccard searches via `sourmash search`), we can run into cases where the error around the Jaccard estimate itself is too high for the Jaccard --> ANI conversion to be trustworthy.

We currently notify with a warning and store `ani_untrustworthy` in `SearchResult`.
```
WARNING: Error on Jaccard distance point estimate is too high (0.0010).
```
We could:
1. add `ani_untrustworthy` column to `Jaccard` search output (though it is irrelevant for any other search/ANI)
2. zero out the ANI estimate (`""`/`None` probably better than 0, as 0 is a valid ANI result)

**Comment by ctb** [comment]
I like zeroing it out. That, combined with the warning, should be enough.
