### ISSUE TITLE
support gzip and/or zipped taxonomy CSVs?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2012]
we should support .gz for our input CSVs.

we could also support .zip files that contain a SOURMASH-TAXONOMY.csv file or something. Or even have standard names for genbank, gtdb, and lins taxonomies.

**Comment by ctb** [comment]
taxonomy csv.gz files implemented in #2178.

**Comment by ctb** [comment]
so https://github.com/sourmash-bio/sourmash/pull/2195 is implementing CSV loading from zipfiles, and it currently uses `SOURMASH-TAXONOMY.csv` as the filename _inside_ the zip from which it will load taxonomy information. Is this a good name?

Separately, note that there is no `sourmash tax` command that takes in both a zipfile database and a taxonomy so at least for the moment this code doesn't simplify the CLI that much. However, it could simplify `sourmash lca index` a bit.

**Comment by bluegenes** [comment]
> so https://github.com/sourmash-bio/sourmash/pull/2195 is implementing CSV loading from zipfiles, and it currently uses SOURMASH-TAXONOMY.csv as the filename inside the zip from which it will load taxonomy information. Is this a good name?

Idea to allow multiple taxonomies per db here: https://github.com/sourmash-bio/sourmash/pull/2195#issuecomment-1213275883

> Separately, note that there is no sourmash tax command that takes in both a zipfile database and a taxonomy so at least for the moment this code doesn't simplify the CLI that much. However, it could simplify sourmash lca index a bit.

Right... I guess I'm thinking `tax` commands could take in a database and just read the taxonomy file(s) from it. That way folks can just use a single file, rather than needing to mess with two separate ones.

**Comment by ctb** [comment]
> Right... I guess I'm thinking `tax` commands could take in a database and just read the taxonomy file(s) from it. That way folks can just use a single file, rather than needing to mess with two separate ones.

ok - so it doesn't simplify the CLI, but does remove the need to deal with an extra file. Got it!

**Comment by ctb** [comment]
note, removed the `SOURMASH-TAXONOMY` name from #2195; will address over in #2154.

**Comment by ctb** [comment]
Trying to figure out how distributing multiple taxonomies in a zip file would work at the command line.

The most obvious idea is:
```
sourmash tax classify -g gather.csv -t gtdb-xyz.zip --gtdb
```
which would load `GTDB-TAXONOMY.csv` from `gtdb-xyz.zip`, vs
```
sourmash tax classify -g gather.csv -t gtdb-xyz.zip --ncbi
```
which would load `NCBI-TAXONOMY.csv` from `gtdb-xyz.zip`.

Then we could potentially add `--lins` later on for https://github.com/sourmash-bio/sourmash/issues/1813.

Alternative command-line switches would be `--tax-type ncbi` or something but I feel like `--ncbi` and `--gtdb` are probably simplest and easiest to remember.

**Comment by ctb** [comment]
@bluegenes thoughts ^^^ ?

**Comment by bluegenes** [comment]
I like `--gtdb` and `--ncbi`, especially since I can't see us integrating so many taxonomies that having an argument per tax type would be unwieldy. 

`--lins` definitely useful when we get there!
