### ISSUE TITLE
fix taxonomy csv(s) for gtdb-rs207?

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2048]
The taxonomy csvs on farm are not correct -- does this mean our uploaded csv's are also incorrect?

 `/group/ctbrowngrp/sourmash-db/gtdb-rs207/gtdb-rs207.taxonomy.csv.gz`-- 11525 rows
 `/group/ctbrowngrp/sourmash-db/gtdb-rs207/gtdb-rs207.taxonomy.with-strain.csv.gz` -- 16563 rows

**Comment by ctb** [comment]
The ones on OSF look good to me -

```
curl -JLO https://osf.io/v3zmg/download
gunzip gtdb-rs207.taxonomy.csv.gz
wc -l gtdb-rs207.taxonomy.csv
curl -JLO https://osf.io/r87td/download
gunzip -c gtdb-rs207.taxonomy.with-strain.csv.gz| wc -l
```
gives 317543 for both CSVs.

**Comment by bluegenes** [comment]
`/group/ctbrowngrp/gtdb/gtdb-rs207.taxonomy.with-strain.csv` also has 317543 -- I'll move it over

**Comment by bluegenes** [comment]
they're ok -- closing!
