### ISSUE TITLE
Why must scale be >=100?

### ISSUE THREAD

**Issue by dkoslicki** [sourmash-bio/sourmash#2064]
I've noticed that sourmash requires the scale to be >= 100, but at times (especially for testing purposes) it would be handy to set a scaled=1. Is there a technical limitation or other rational of why the scale can't be any smaller than 100?

**Comment by ctb** [comment]
it's a warning - it's not enforced in any way. We use scaled=1 all the time :).

**Comment by ctb** [comment]
(it's just really, really slow; we don't want users new to the FracMinHash concept to settle on it and then complain "but it's really slow (when we use it in this off label way!)"

**Comment by dkoslicki** [comment]
Ah, gotcha. I misinterpreted the warning as it changing 1 to 100.
