### ISSUE TITLE
Unable to download prepared GenBank databases

### ISSUE THREAD

**Issue by aboffin** [sourmash-bio/sourmash#2134]
Hi,

Apologies if this is not the right place to raise this issue, I have trouble downloading the GenBank signature files (e.g., [genbank-2022.03-fungi-k51.zip](https://dweb.link/ipfs/bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam)). 

I get these error messages and download fails with both `wget` and `curl` with the same result (download interrupted due to connection being closed).

```
$ wget https://dweb.link/ipfs/bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam -O genbank-2022.03-fungi-k51.zip
...
...
--2022-07-21 21:38:57--  (try: 6)  https://bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam.ipfs.dweb.link/
Connecting to bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam.ipfs.dweb.link (bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam.ipfs.dweb.link)|209.94.90.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2763963759 (2.6G) [application/zip]
Saving to: ‘genbank-2022.03-fungi-k51.zip’

27% [=================>                                                  ] 769,654,784 --.-K/s   in 12m 16s 

2022-07-21 21:51:13 (1021 KB/s) - Connection closed at byte 769654784. Retrying.

--2022-07-21 21:51:19--  (try: 7)  https://bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam.ipfs.dweb.link/
Connecting to bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam.ipfs.dweb.link (bafybeibnrtt45f7wez2xb3fy5rxhatpeevc3rilm2gs65u5h6gc4u72fam.ipfs.dweb.link)|209.94.90.1|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 2763963759 (2.6G), 1994308975 (1.9G) remaining [application/zip]
Saving to: ‘genbank-2022.03-fungi-k51.zip’

42% [++++++++++++++++++=========>                                      ] 1,173,355,543 1.05MB/s   in 7m 47s 

2022-07-21 21:59:07 (845 KB/s) - Read error at byte 1173355543/2763963759 (Connection reset by peer).
```

Thank you for any pointers,
Sen

**Comment by ctb** [comment]
hi Sen, giving it a try myself right now!

**Comment by ctb** [comment]
hi @aboffin the download finished for me at UC Davis - took about 1.5 hours. Here at UCD we don't have any special connection to the download servers, but we do have a reasonably high bandwidth Internet connection - is that maybe the problem?

@luizirber any suggestions for alternative approaches to download?

**Comment by aboffin** [comment]
Hi @ctb  thank you for checking this. I was able to download the fungi file, right now I am having issues with the bacterial Genbank file. I had earlier forgotten to mention that I am trying these download commands in a AWS instance. 

Based on some suggestions online, I tried `wget` with `--no-http-keep-alive`, `--auth-no-challenge` and `--no-check-certificate` or `--continue --progress=dot:mega --tries=0` with similar results. There were many attempts to retry to download where the read error occurred, but ultimately the download fails. I quit the `--tries=0` download since waiting for response from server (retry) was taking too long.

Further digging up, I found `lftp` and the download appears to be going well (20%) the furthest download so far 🤞 

Thanks again for following up, I appreciate it.

**Comment by aboffin** [comment]
Can confirm that `lftp` works and may be an option to try if there are issues with `wget` or `curl` while downloading the prepared Genbank databases.

**Comment by ctb** [comment]
> Can confirm that `lftp` works and may be an option to try if there are issues with `wget` or `curl` while downloading the prepared Genbank databases.

thanks, @aboffin - much appreciated. we'll update the docs!

**Comment by taylorreiter** [comment]
I am also having trouble with `wget`. I checked the docs and don't see recs regarding `lftp` yet and it wasn't intuitive how to run it...@aboffin would you be willing to share the command you used?

**Comment by aboffin** [comment]
@taylorreiter Sure, here it is:
```sh
lftp -c 'set net:idle 10
         set ssl:verify-certificate no
         set net:max-retries 0
         set net:reconnect-interval-base 3
         set net:reconnect-interval-max 3
         pget -n 10 -c "https://dweb.link/ipfs/bafybeifyrwbx5dnay4mflboc5zai2de3xrvcxtgiu4j7adzj6qrxhb3zva" -o genbank-2022.03-archaea-k51.zip'      
```
