### ISSUE TITLE
counterintuitive printed notification: downsampling during prefetch

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2182]
Minor UX issue.

Running prefetch with: 
- query signatures scaled=200
- database signatures scaled=1000

This must necessarily search at scaled=1000, but the initial output contains the following line:

**all sketches will be downsampled to scaled=200** 

which makes it seem like it will be `scaled=200`

command:
```
sourmash prefetch 1903c117_50m-3_assembly.fa.sig.gz scaled1000.zip \
--ksize 10 --protein --save-matches 1903c117_50m_x_phylodb.k10-scaled1000.zip \
-o 1903c117_50m_x_phylodb.k10-scaled1000.prefetch.csv
```

output:
```
== This is sourmash version 4.4.3. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

selecting specified query k=10
loaded query: 1903c117_50m... (k=10, protein)
all sketches will be downsampled to scaled=200
saving all matching database signatures to '1903c117_50m_x_phylodb.k10-scaled1000.zip'
loading signatures from '/home/ntpierce/2022-ocsmash-db/phyloDB/phylodb_1.076.scaled1000.ff.zip'
total of 159 matching signatures.
saved 159 matches to CSV file '1903c117_50m_x_phylodb.k10-scaled1000.prefetch.csv'
of 172037 distinct query hashes, 4065 were found in matches above threshold.
a total of 167972 query hashes remain unmatched.
final scaled value (max across query and all matches) is 1000
```

The last line is great -- I know the search happened at `1000`. But the early line gave me pause. Perhaps we could add the word _query_, e.g. **all query sketches will be downsampled to scaled=200`**.  

It might also help to say "These sketches will be dynamically downsampled as needed for search against reference signatures."

**Comment by ctb** [comment]
oops!

note: sort of tangentially relevant to large-scale UX stuff, https://github.com/sourmash-bio/sourmash/issues/1426.
