### ISSUE TITLE
support distance matrix output from `compare`?

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2196]
`sourmash compare` outputs a similarity matrix. Many tools want the opposite, a distance matrix.

It would be relatively straightforward to support `--distance` (outputs 1-value). This would work for jaccard, containment, and ANI outputs, which would avoid any errors brought on by custom scripts transforming values.

from discussion with @nvpatin

**Comment by ctb** [comment]
see also https://github.com/sourmash-bio/sourmash/issues/491 for other output requests.

**Comment by ctb** [comment]
question: would we need to adjust the `plot` command in any way?

**Comment by ctb** [comment]
It looks like `plot` needs to be adjusted to compensate - using the code in #2225,
```
sourmash compare -o cmp podar-ref/*.fa.sig -k 21 --ani --distance
sourmash plot cmp
```
I get:
```
/Users/t/dev/sourmash/src/sourmash/commands.py:297: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Y = sch.linkage(D, method='single')
```
My guess is that scipy.cluster expects a similarity matrix.
