### ISSUE TITLE
specifying multiple lineages for `sourmash tax` commands

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2213]
for sourmash `tax`, specify multiple taxonomy files like so:
`sourmash tax annotate -g GATHER.csv --taxonomy DB_1.csv DB_2.csv`

Here, `DB_1` and `DB_2` taxonomies will be loaded, with `DB_2` overwriting any shared identifiers.

The following command is "valid" but does NOT have the same function:

`sourmash tax annotate -g GATHER.csv --taxonomy DB_1.csv --taxonomy DB_2.csv`

Here, we only read `DB_2` and `DB_1` is ignored entirely.

**Comment by ctb** [comment]
strikes me as a bug. this can be dealt with easily in argparse.

**Comment by bluegenes** [comment]
Adding action="extend" should handle this nicely. Will PR later today.
