### ISSUE TITLE
readthedocs build failing: missing pkgs/main conda channel

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2227]
we're getting the following error on readthedocs builds as of about 8 hours ago -
```
%  conda env create --quiet --name 2225 --file doc/environment.yml 
 Collecting package metadata: ...working... failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: pkgs/main
  channel url: https://repo.anaconda.com/pkgs/main
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

while this channel is not in our `doc/environment.yml` it looks like it might be something added by RTD, based on free-associating from https://github.com/readthedocs/readthedocs.org/issues/8059.

Reading https://server-docs.anaconda.com/en/latest/reference/troubleshooting.html, it appears that anaconda _might_ be blocking the readthedocs build server from accessing that channel - possible reasons given, in order of likelihood, are -

>The user has misconfigured their channels in their configuration (for example, the secure location where the token is stored was accidentally deleted (most common)

>A firewall or other security device or system is preventing user access (second most common)

>We are blocking their access because of a potential terms of service violation (third most common)

I'm not going to do anything more to troubleshoot it just yet, maybe it'll get fixed over the weekend or something...

**Comment by robelgeda** [comment]
Can confirm I see it too, good to know its wide spread.
