### ISSUE TITLE
report abundance weighted hashes/bp from gather and tax?

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2240]
In #2239, I found myself wanting the a summarized weighted bp -- the total bp matched via sourmash gather. We don't currently summarize that in `sourmash tax`, partially because we don't report it from gather. 

- Is it valid to just multiply `f_unique_weighted` by the `query_scaled`?
- How can we get at the weighted unclassified bp? afaict, we don't currently store the original `total_weighted_bp` for the query...

Backing up to `sourmash gather`, we could:
- Report `weighted_unique_intersect_bp` from `gather`.
- Report query weighted bp (to allow weighted unclassified)

These would allow summarization in tax.

Somewhat separately,  @taylorreiter has suggested that reporting hashes, rather than bp, would be more useful so as not to inflate our numbers / impact downstream methods, e.g. diff abundance.

She suggested some/any of the following:
```
n_hashes
n_hashes_weighted
n_unique_hashes
n_unique_hashes_weighted
```

But in thinking through reporting hashes, I realized this creates a secondary issue. Since gather can function at multiple scaled vals and will dynamically downsample as needed, `n_hashes` matched in one comparison may _mean_ something different than `n_hashes` matched in the another, if the comparison scaled was different. Only an issue for matching against db's with mixed scaled values.

Just documenting rn, thoughts welcome.

**Comment by bluegenes** [comment]
weighted missed will be useful: https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/search.py#L783

**Comment by bluegenes** [comment]
To be a little clearer/ write this another way:

In `kreport` output, since we are outputting `abundance-weighted fraction of the k-mers in the dataset matched` as the first column, it would be good to output an abundance-weighted total number of estimated base pairs as the second column, rather than unweighted, as originally written in #2239.

To do this:

1. keep track of and report the weighted hashes and/or bp (hashes * scaled) during gather. Turns out we already keep track of this, but don't store it usefully.
2. Also keep track of the total number of weighted hashes/bp of the query? I think we need this in order to keep track of the #weighted bp that are unclassified after taxonomic summarization. 
3.  Summarize weighted bp during `sourmash tax`, and report as 2nd column in `kreport` output format

related to 1, it would be useful to keep track of `n_weighted hashes` matched for each result. This is the best input to use for downstream differential abundance programs.

**Comment by ctb** [comment]
digging - it's even worse! we already store `total_abund` in `GatherResult` but don't output it 😆
