### ISSUE TITLE
Adapter and quality trimming of reads

### ISSUE THREAD

**Issue by aboffin** [sourmash-bio/sourmash#2266]
Hi,

It is usually not clear if public SRA reads have been filtered for adapters, barcodes and quality. Is it necessary for the reads to be adapter and quality trimmed or can the reads be directly used with sourmash (after running the recommended khmer step) ?

Thank you,
Senthil

**Comment by ctb** [comment]
no need! see https://github.com/sourmash-bio/sourmash/issues/2122 for advice that also applies to adapters.

tl;dr adapters, barcodes, and quality filtering are important elsewhere, but not for the kinds of reference-based stuff that we do with sourmash.

**Comment by ctb** [comment]
note, screening metagenomes for host contamination / removing host k-mers can be important for getting a sense of how much of the metagenome is, well, host - but this is only important if you're using gather and care about the % characterized.

**Comment by aboffin** [comment]
@ctb Thank you for the quick response. So if I understand correctly: a) there is no need to filter for adapters or quality and b) running `trim-low-abund.py` from khmer is still recommended ?

**Comment by ctb** [comment]
welcome!

I'm actually waffling on trim-low-abund too - see https://github.com/dib-lab/genome-grist/issues/197. I think it's probably not important, unless you're doing assembly-graph work (e.g. spacegraphcats).

**Comment by ctb** [comment]
so suggest just running sourmash, and if you get some weird results check back with us! (but you probably won't)

happy to chat through things privately if you want to run what you're planning past a semi-interested semi-expert ;)

**Comment by aboffin** [comment]
Sounds good! Thank you for the clarification.

**Comment by ctb** [comment]
closing - don't hesitate to ask questions here or in a new issue tho!
