### ISSUE TITLE
Prepared databases not accessible

### ISSUE THREAD

**Issue by hoelzer** [sourmash-bio/sourmash#2325]
Hi, I wanted to download some of the databases here: https://sourmash.readthedocs.io/en/latest/databases.html#genbank-genomes-from-march-2022, but they seem not accessible. I always get a `HTTP request sent, awaiting response... 403 Forbidden
`.

Thanks!
Martin

**Comment by ctb** [comment]
hi @hoelzer apologies our HPC is undergoing planned maintenance 😭 and that's where we're serving these big files from! It will be back up on Thursday. I will alert you when it is back up.

In the meantime here are some alternatives you can try: https://github.com/sourmash-bio/sourmash/issues/2179

**Comment by hoelzer** [comment]
hi @ctb - alright, great thanks for the info!

**Comment by ctb** [comment]
It's back up! Give it a try!

**Comment by hoelzer** [comment]
Great, works 👍 thx!
