### ISSUE TITLE
`sourmash gather --output-unassigned` does not zip-compress signatures

### ISSUE THREAD

**Issue by vmikk** [sourmash-bio/sourmash#2337]
Hello!
First of all, thank you for the great software!

I've experimented with the `sourmash gather` command, and it looks like one of the outputs (`--output-unassigned`) does not support zip compression of signatures. E.g.:
```
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR885/005/SRR8859675/SRR8859675_1.fastq.gz
wget https://farm.cse.ucdavis.edu/~ctbrown/sourmash-db/gtdb-rs207/gtdb-rs207.genomic-reps.dna.k31.zip

sourmash sketch dna -p k=31 SRR8859675*.gz -o SRR8859675.sig.gz --name SRR8859675

sourmash gather \
  --save-matches matches.zip \
  --output-unassigned unassigned.zip \
  SRR8859675.sig.gz gtdb-rs207.genomic-reps.dna.k31.zip
```
In the output, `matches` are compressed, while `unassigned` is plain JSON.

`sourmash` v.4.5.0

With kind regards,
Vladimir

**Comment by ctb** [comment]
you're right! 😭 

easy enough to fix. will let you know! thank you for reporting!

**Comment by ctb** [comment]
Fixing in https://github.com/sourmash-bio/sourmash/pull/2338. Found bug related to signature output in `sourmash watch` too. 👍 

Thanks again! Nice, easy to fix problems that lead to more fixed bugs are a nice way to start the morning 😆
