### ISSUE TITLE
installation python 3.11

### ISSUE THREAD

**Issue by gtonkinhill** [sourmash-bio/sourmash#2350]
Hi,

Thanks for developing and maintaining such a useful package! I recently installed sourmash in conda with python v3.11 and ran into the following issue with the argument parser. I realise this python version has only just been released but thought it might be helpful to raise the issue anyway.

Downgrading to python 3.10 fixed the problem. 

The issue was the result of running the following command in python 3.11
```
sourmash gather -h
```

resulting in the error

```
Traceback (most recent call last):
  File "/software/miniconda3/envs/testsour/bin/sourmash", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/software/miniconda3/envs/testsour/lib/python3.11/site-packages/sourmash/__main__.py", line 5, in main
    args = sourmash.cli.get_parser().parse_args(arglist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/miniconda3/envs/testsour/lib/python3.11/site-packages/sourmash/cli/__init__.py", line 135, in get_parser
    getattr(sys.modules[__name__], op).subparser(sub)
  File "/software/miniconda3/envs/testsour/lib/python3.11/site-packages/sourmash/cli/sbt_combine.py", line 14, in subparser
    subparser = subparsers.add_parser('sbt_combine')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/miniconda3/envs/testsour/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument cmd: conflicting subparser: sbt_combine
```

**Comment by ctb** [comment]
thank you! haven't tried running with 3.11 yet myself, very much appreciate the heads up!

**Comment by akrinos** [comment]
Just ended up here to report that I am having the same error come up!

**Comment by ctb** [comment]
fixed in https://github.com/sourmash-bio/sourmash/pull/2393! see https://github.com/sourmash-bio/sourmash/pull/2393#pullrequestreview-1229697364.

This will be available in the next release, which will be 4.6.2 or 4.7.0 - not sure which yet :)

**Comment by akrinos** [comment]
Oh awesome, thanks for directing me there!

**Comment by luizirber** [comment]
We are on 4.8.4 and running on 3.11 for some time, closing this issue. Please reopen if still seeing the error!
