### ISSUE TITLE
does sourmash gather not output a csv file (either empty or with a header) when there are no matches?

### ISSUE THREAD

**Issue by taylorreiter** [sourmash-bio/sourmash#2357]
I'm writing a pipeline that uses sourmash gather, and I found that when I run gather and there are no matches, no csv is output. I can't tell if this is expected behavior, and if it is, can it ...not be? It would be super helpful in a workflow scenario to output an empty csv file if there are no matches.

reprex:
sourmash 4.5.0
```
wget -O contamdb.dna.k21.zip https://osf.io/ma8cf/download
sourmash gather -k 21 --output tmp.csv SRR11140750_T1.sig contamdb.dna.k21.zip
```
[SRR11140746_T1.sig.txt](https://github.com/sourmash-bio/sourmash/files/9930871/SRR11140746_T1.sig.txt)

current stdout is:
```
== This is sourmash version 4.5.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

selecting specified query k=21
loaded query: SRR11140750_T1... (k=21, DNA)
--
loaded 4572 total signatures from 1 locations.
after selecting signatures compatible with search, 4520 remain.

Starting prefetch sweep across databases.
Found 0 signatures via prefetch; now doing gather.
found less than 50.0 kbp in common. => exiting

found 0 matches total;
the recovered matches hit 0.0% of the abundance-weighted query

WARNING: size estimation for at least one of these sketches may be inaccurate. ANI values will not be reported for these comparisons.
```

**Comment by ctb** [comment]
encountered for prefetch here: https://github.com/dib-lab/genome-grist/issues/194

yes, is annoying. willfix.

**Comment by taylorreiter** [comment]
Awesome thank you :)

**Comment by ctb** [comment]
Does snakemake have any kind of simple way to do a "blackhole" designation that says, hey, the results of this rule may not yield anything, in which case you should just punt on all of the downstream rules?

**Comment by taylorreiter** [comment]
This functionality would be super useful, but I don't know if it exists. I've dealt with it before by doing `&& touch {output}` at the end of shell commands that I expect might not produce an output because the input was empty. Or run it in R or python where I can more easily explicitly check for emptiness and touch output files.

**Comment by bluegenes** [comment]
Got another request for producing an output file even when there are no matches, just bumping this back up in our minds

**Comment by ctb** [comment]
My main concern is semantic versioning stuff.

It would be 100% ok (and very straightforward ;) to add a flag that does this, tho.

Plus, I think we could add some guidance about thresholding etc to the command.

**Comment by ctb** [comment]
> This functionality would be super useful, but I don't know if it exists. I've dealt with it before by doing `&& touch {output}` at the end of shell commands that I expect might not produce an output because the input was empty. Or run it in R or python where I can more easily explicitly check for emptiness and touch output files.

I think you might be able to do:
```
rule xyz:
   output: touch("expected_output.csv")
```

as well, but not sure.
