### ISSUE TITLE
sourmash sig extract missing some names

### ISSUE THREAD

**Issue by dkoslicki** [sourmash-bio/sourmash#2358]
I have a database `formatted_db.sig` that has inside it the following:
```
$sourmash sig describe formatted_db.sig
<snip>
signature filename: formatted_db.sig
signature: GCF_000174095.1_wUni_1.0_genomic.fna
source file: formatted_db.fasta
md5: cd7fc82579f3860d6f95a7943d6d8caf
k=31 molecule=DNA num=0 scaled=1000 seed=42 track_abundance=1
size: 809
sum hashes: 823
<snip>
```
So `GCF_000174095.1_wUni_1.0_genomic.fna` is certainly in there. However, `sourmash sig extract` can't find it:
```
$ sourmash sig extract --name GCF_000174095.1_wUni_1.fna formatted_db.sig

== This is sourmash version 4.5.0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 1045 total that matched ksize & molecule type
no matching signatures to save!
```

**Comment by dkoslicki** [comment]
Ugh. Turns out NCBI file names and don't agree with their FASTA headers: note that the first is `GCF_000174095.1_wUni_1.0_genomic.fna` while the second is `GCF_000174095.1_wUni_1.fna`. It's missing the `.0_genomic.`. Red herring

**Comment by ctb** [comment]
you might also be interested in `sourmash sig grep` and `sourmash sig extract --include <pattern>`, for inexact matching.
