### ISSUE TITLE
sourmash compare error with --scaled flag

### ISSUE THREAD

**Issue by jessicalumian** [sourmash-bio/sourmash#2398]
I'm running sourmash 4.5.0 in a conda env. When I ran

`sourmash compare -k 31 --scaled 2000 input.sig -o test_cmp`

I got the following error

`sourmash: error: unrecognized arguments: --scaled`

according to the help message, `--scaled` should be supported. If it's relevant, my `input.sig` was calculated with `sourmash dna sketch` for k = 21,31,51, a scaled value of 2000, and abundance tracking on.

**Comment by ctb** [comment]
> according to the help message, `--scaled` should be supported.

actually turns out it's not listed there!

but I think maybe it should be supported 🤔

**Comment by jessicalumian** [comment]
oooh oops you are right! I conflated gitter chat with the actual help message

**Comment by ctb** [comment]
Fixed over in #2414. Ready for review if you care to take a look ;)
