### ISSUE TITLE
improving help message for sourmash compare with --csv flag

### ISSUE THREAD

**Issue by jessicalumian** [sourmash-bio/sourmash#2399]
greetings! I am running sourmash 4.5.0 in conda. I was trying to use `sourmash compare` to get angular distance signatures but I had the following erroneous command:

`sourmash compare -k 31 --csv <file> -o <output>`

after getting some help in the [sourmash gitter channel](https://gitter.im/sourmash-bio/community#) I realized my command was wrong and should have been

`sourmash compare -k 31 <file> -o <output> --csv <output.csv>`

It would be helpful if the message for `sourmash compare --help` and/or [the help docs](https://sourmash.readthedocs.io/en/latest/command-line.html#sourmash-compare-compare-many-signatures) (which is my first point of reference for finding which command info) could include an example command like the one above to make it clear that the csv output is separate from output matrix. Or, something to indicate which flags go before `-o` and which go after. thanks!!

**Comment by ctb** [comment]
Hi @jessicalumian see updated docs here: https://sourmash--2400.org.readthedocs.build/en/2400/command-line.html#sourmash-compare-compare-many-signatures - seem good?

**Comment by jessicalumian** [comment]
yes that last bullet point is perfect!
