### ISSUE TITLE
upgrade labels on `sourmash plot` with `--labels-from` or some such

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2452]
Labels on `sourmash plot` are complicated and ugly ;(.

Random thought: we could add a `--labels-to` option to `sourmash compare` that supports a simple labeling output spreadsheet, and then support a `--labels-from` option with `sourmash plot`.

**Comment by peterjc** [comment]
Good idea.

As a workaround, I've been editing the ``*.npy.labels.txt`` file which gets created alongside ``*.npy`` and is parsed by ``sourmash plot`` with ``--labels``. This can be as simple as a few in-place ``sed`` edits to do things like remove ``.fasta`` extensions of a common filename prefix.

**Comment by ctb** [comment]
@peterjc check out #2598 - curious what you think. Simple and flexible, or overly complicated? Let me know :)
