### ISSUE TITLE
Difference in sourmash tax metagenome between v.4.6.1 and 4.8.1

### ISSUE THREAD

**Issue by karkman** [sourmash-bio/sourmash#2578]
Hi,

I have been running taxonomic annotation of my metagenomes successfully with sourrmash v.4.6.1. But after updating to the latest version, v.4.8.1,  `sourmash tax metagenome` gives an error. 

Running the the same command to the same gather outputs with different version:

``` 
sourmash tax metagenome \
    -g 05_TAXONOMIC_PROFILE/*.gather.csv \                        
    -t gtdb-rs207.taxonomy.with-strain.csv.gz \                       
    --output-dir 05_TAXONOMIC_PROFILE \
    --output-base sourmash.genus \                        
    --output-format lineage_summary \                         
    --rank genus
```

Gives these two outputs:
```
== This is sourmash version 4.6.1. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 121 gather results from '05_TAXONOMIC_PROFILE/m12208.gather.csv'.
loaded 179 gather results from '05_TAXONOMIC_PROFILE/m12209.gather.csv'.
loaded 33 gather results from '05_TAXONOMIC_PROFILE/nanopore.gather.csv'.
loaded 156 gather results from '05_TAXONOMIC_PROFILE/o12208.gather.csv'.
loaded 194 gather results from '05_TAXONOMIC_PROFILE/o12209.gather.csv'.
loaded 683 results total from 5 gather CSVs
saving 'lineage_summary' output to '05_TAXONOMIC_PROFILE/sourmash.genus.lineage_summary.tsv'.
```

```
== This is sourmash version 4.8.1. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 1 gather results from '05_TAXONOMIC_PROFILE/m12208.gather.csv'.
loaded 1 gather results from '05_TAXONOMIC_PROFILE/m12209.gather.csv'.
loaded 1 gather results from '05_TAXONOMIC_PROFILE/nanopore.gather.csv'.
loaded 1 gather results from '05_TAXONOMIC_PROFILE/o12208.gather.csv'.
loaded 1 gather results from '05_TAXONOMIC_PROFILE/o12209.gather.csv'.
loaded results for 5 queries from 5 gather CSVs
WARNING: found results for multiple gather queries. Can only output multi-query result formats: skipping lineage_summary
ERROR: No output formats remaining.
```

So the older version works fine, even with gather results produced by v.4.8.1.
Has something changed with how `sourmash gather` or `sourmash tax metagenome` should be run in the latest  version?

Best,
Antti

**Comment by ctb** [comment]
oh dear! that should not happen! we will look into it and maybe ask you some more questions :)

cc @bluegenes

**Comment by ctb** [comment]
@karkman if you get a chance to try with v4.8.0 it would help us to track down the bug!

**Comment by karkman** [comment]
I’m pretty sure that this happens also with v.4.8.0. I can double check tomorrow morning (which means in about 12 h).

-Antti

C. Titus Brown ***@***.***> kirjoitti 19.4.2023 kello 20.56:

﻿

@karkman<https://github.com/karkman> if you get a chance to try with v4.8.0 it would help us to track down the bug!

**Comment by bluegenes** [comment]
Hi @karkman, sorry about that -- this is a bug! It was introduced in v4.7.0, no need to check v4.8.
Thanks for reporting -- fix coming soon!

**Comment by ctb** [comment]
This should have been fixed in v4.8.2, which is now available via pip and conda: https://github.com/sourmash-bio/sourmash/releases/tag/v4.8.2

Give it a try and let us know! thank you for reporting the bug!!!

**Comment by karkman** [comment]
Thank you for the quick fix!

I tried `sourmash tax metagenome` on gather files created with v.4.8.0. 

v.4.8.2 seems to give same results as v.4.6.1. So fixed.

**Comment by ctb** [comment]
yay!! thanks!
