### ISSUE TITLE
rust beta lints are failing

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2591]
e.g. https://github.com/sourmash-bio/sourmash/actions/runs/4791302059

<img width="701" alt="Screenshot 2023-04-24 at 3 07 22 PM" src="https://user-images.githubusercontent.com/51016/234127140-f62a0f11-a2c5-4c91-be38-f36c4c84e876.png">

**Comment by luizirber** [comment]
Fixed in https://github.com/sourmash-bio/sourmash/pull/2596
