### ISSUE TITLE
unexpected `sig grep`, `sig extract` behavior with identical md5s

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2593]
`sig grep` produces an unintuitive result if sigs have identical md5's:

```
sourmash sig grep "AY770193" output.spillover/spillover100.dna.zip -k 21 --dna > test.sig

== This is sourmash version 4.8.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

saving matching signatures to '-'
loaded 100 total that matched ksize & molecule type
extracted 2 signatures from 1 file(s)
```
And the signatures:
```
sourmash sig describe test.sig

== This is sourmash version 4.8.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

---
signature filename: test.sig
signature: AY770193 Andes orthohantavirus
source file: output.spillover/genomic/AY770193.fna.gz
md5: 31d1b130702bc77a42d3876259fe2835
k=21 molecule=DNA num=0 scaled=1 seed=42 track_abundance=1
size: 212
sum hashes: 212
signature license: CC0

---
signature filename: test.sig
signature: AY770195 Andes orthohantavirus
source file: output.spillover/genomic/AY770195.fna.gz
md5: 31d1b130702bc77a42d3876259fe2835
k=21 molecule=DNA num=0 scaled=1 seed=42 track_abundance=1
size: 212
sum hashes: 212
signature license: CC0

loaded 2 signatures total, from 1 files
```

if I grep for "AY770195" , I get the same two signatures.
But, if I grep for "AY77019" instead, I get 8 signatures, all of the AY77019*.

As Mo pointed out, the md5sums are identical. I think sig grep is using the md5 to pull out the signatures, which is why I'm getting both of these signatures here, despite their name differences. 

Note, the same thing happens with `sig extract` (which makes sense, because I think it uses a similar strategy).

```
sourmash sig extract -k 21 --dna --name  "AY770193 Andes orthohantavirus" output.spillover/spillover100.dna.zip > test6.sig
```
```
== This is sourmash version 4.8.2. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 100 total that matched ksize & molecule type
extracted 2 signatures from 1 file(s)
```

I was testing some extremely short sequences here (and the reference sequences themselves seem to be identical), so running into identical md5's not super surprising, though I'll look into it. But we should still consider how to handle behavior in these cases, as identical md5's do happen (albeit more rarely) with our more standard uses.

This db can be found on farm: `/home/ntpierce/2023-spillover/output.spillover/spillover100.dna.zip`.

One of my main issues with this behavior is that if you build a single zip database, there's no way to extract these signatures separately for downstream steps, e.g. `gather` against a reference database.

**Comment by bluegenes** [comment]
Trying to track this down a bit more --

The relevant `grep`  code is here:

https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/sig/grep.py#L85-L113

specifically, 

```
# find all matching rows.
sub_manifest = manifest.filter_on_columns(search_pattern, ["name", "filename", "md5"])
#do output signatures. convert manifest to picklist, apply.
sub_picklist = sub_manifest.to_picklist()
idx = idx.select(picklist=sub_picklist)
```

so the relevant steps are: 
1. filter the manifest
2. convert this to a picklist for use with`idx.select`

Manifest Filtering is here: https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/manifest.py#LL317C1-L322C47

```
    def filter_on_columns(self, col_filter_fn, col_names):
        "Create a new manifest based on column matches."
        def row_filter_fn(row):
            x = [ row[col] for col in col_names if row[col] is not None ]
            return col_filter_fn(x)
        return self.filter_rows(row_filter_fn)
```

which seems .. fine! So then I looked at picklist conversion...


https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/manifest.py#L340-L345
```
    def to_picklist(self):
        "Convert this manifest to a picklist."
        picklist = SignaturePicklist('md5')
        picklist.pickset = set(self._md5_set)

        return picklist
```
..and that looks like where we're using just md5 and thus returning both signatures.

**Comment by ctb** [comment]
yep.
