### ISSUE TITLE
`tax grep` doesn't search the identifiers!

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2607]
which seems odd.

**Comment by bluegenes** [comment]
right -- currently just searches `name`, `filename`, `md5`.

For our database sigs, ident is always contained within `name`, so it's not functionally a problem. However, it would be an issue for anyone not building `name` in this way...

**Comment by ctb** [comment]
Right - `sig grep` searches for identifiers, `tax grep` is only for taxonomic names.
