### ISSUE TITLE
Transcriptome of interest, gather in metaTs signatures, repeat. Faster or directly to mapping? 

### ISSUE THREAD

**Issue by adriaaula** [sourmash-bio/sourmash#2610]
Hello sourmashers, 

Our objective is to interrogate an specific transcriptome to multiple samples. We will have multiple transcriptomes in our hands, and we will want to interrogate multiple metaT that will fall in our hands for open projects out there such as Tara. 

My train of thought was the following: 

- For new public metaTs, create a signature, save it in a dedicated directory.
- Whenever I have a transcriptome to interrogate, sketch it too, and afterwards `gather` with sourmash. 
- From all the samples presenting a high jaccard or ANI value, perform a mapping of the sample in a more traditional way such as with `salmon`. 

Some questions arise to me: 
- Does this makes sense computationally? I think I am saving computing time, since I do not have to `sketch` the metaTs every time. Well, I am basically following your Branchwater project but on a more local scale hehe. 
- What threshold should I use for containment. Erring in the conservative site, a 50% of transcriptome detection? From [here](https://osf.io/w2396) there are some estimates but I do not know for sure. 
- Not weighting for abundance is faster than a direct Jaccard measurement no? And since here I only want presence / absence it makes sense.

**Comment by ctb** [comment]
rings true to me!

> Our objective is to interrogate an specific transcriptome to multiple samples. We will have multiple transcriptomes in our hands, and we will want to interrogate multiple metaT that will fall in our hands for open projects out there such as Tara.

👍
 
> My train of thought was the following:
> 
>* For new public metaTs, create a signature, save it in a dedicated directory.
> 
>* Whenever I have a transcriptome to interrogate, sketch it too, and afterwards `gather` with sourmash.

yep! note that you can provide your set of previous matches from gather to a new gather and it may speed up things, and/or save the prefetch results from gather against database A and then use that + new database B to avoid once-again searching things from database A that had no previous results.

(let me know if that doesn't make sense 😂)

also: remember to use zip files for everything per [docs](https://sourmash.readthedocs.io/en/latest/command-line.html#choosing-signature-output-formats)!

>* From all the samples presenting a high jaccard or ANI value, perform a mapping of the sample in a more traditional way such as with `salmon`.

yes! honestly suggest just using containment, but you can convert that to ANI if you wish 😉 

> Some questions arise to me:
> 
>* Does this makes sense computationally? I think I am saving computing time, since I do not have to `sketch` the metaTs every time. Well, I am basically following your Branchwater project but on a more local scale hehe.

yes! 

we have various faster ways of doing certain things, e.g. [pyo3_branchwater](https://github.com/sourmash-bio/pyo3_branchwater) that might be interesting. but probably not worth taking on the technical issues with that.
 
>* What threshold should I use for containment. Erring in the conservative site, a 50% of transcriptome detection? From [here](https://osf.io/w2396) there are some estimates but I do not know for sure.

would suggest doing initial search with very low threshold and seeing what you get. 50% seems really high to me, but ...transcriptomes. not sure.

>* Not weighting for abundance is faster than a direct Jaccard measurement no? And since here I only want presence / absence it makes sense.

speed shouldn't factor in, but agree, presence/absence <=> jaccard.

@taylorreiter @bluegenes might have thoughts too!

**Comment by taylorreiter** [comment]
I have very little to add other than all of the above sounds great and that when it comes to the mapping step, I have found that reads need to be mapped in single end mode to recover as many mapped reads as possible.

**Comment by adriaaula** [comment]
Thanks to both for the fast response! 

> yep! note that you can provide your set of previous matches from gather to a new gather and it may speed up things, and/or save the prefetch results from gather against database A and then use that + new database B to avoid once-again searching things from database A that had no previous results.

Cool! 

> would suggest doing initial search with very low threshold and seeing what you get. 50% seems really high to me, but ...transcriptomes. not sure.

I am going to start with 20% and see how we go from there. Thanks. 

> I have very little to add other than all of the above sounds great and that when it comes to the mapping step, I have found that reads need to be mapped in single end mode to recover as many mapped reads as possible.

Thank you for that :)

**Comment by adriaaula** [comment]
In fact I am realising now that I mixed up the commands: I was working with `compare`, and therefore the output is a jaccard index, which also gives information about the overall metaT (given that that IS the denominator), and since I am working with a single transcriptome vs a metaT it is more forward the `gather` output, specifically the `f_query` column, which is by default containment.

Just a clarification in case anyone reaches this post. Closing it now :)
