### ISSUE TITLE
If loaded `0` signatures from a file, still writes an output

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#2664]
I was downsampling some sketches of k=31. Then, I downsampled with `k=51` by mistake. The command printed (loaded 0 signatures), yet it wrote the output to the disk.

It will be less confusing not to write anything to the disk. This behavior may not be expected through other commands that read and write a signature.

**Comment by ctb** [comment]
thanks mo!

realistically we want to allow both "fail if nothing" and "create empty file if no results" - the former because it makes sense, the latter because workflows sometimes want files to be created (see https://github.com/sourmash-bio/sourmash/issues/2357).

**Comment by mr-eyes** [comment]
I can see your point. So, in my specific case, and in large values of `scale`, I would need to check every signature file if it really contains hashes or not. Also will need to check if this kmer-size exists in the signature file.

Thanks, Titus!
