### ISSUE TITLE
Differing dendrogram outputs from plot - `--labeltext` is honored differently by dendrogram and matrix outputs

### ISSUE THREAD

**Issue by Glfrey** [sourmash-bio/sourmash#2667]
Hello,

I'm currently having an issue where `sourmash plot` is outputting two different dendrograms. I've attached an example and the code I used below. I get the same issue with version 4.0.0.(using for some old work) and the latest version.  

```
sourmash compare -k=21 --output k21_all_compare --csv k21_all_compare.csv /home/b56j439/sourmash/all/sigs/*sig

sourmash plot k21_all_compare --labeltext new_labels.txt --csv k21_all_plot.csv
```

I've confirmed the `new_labels.txt ` contains the same labels in the same order as the original label file, I just wanted to remove the directory structure from the labels. 

![k21_all_compare matrix](https://github.com/sourmash-bio/sourmash/assets/33197909/2f3907e7-3eb7-49bc-bdf6-f4176cf026bf)
![k21_all_compare dendro](https://github.com/sourmash-bio/sourmash/assets/33197909/f908b19b-a04a-436e-b1a2-7c6d025ef981)

**Comment by mr-eyes** [comment]
Hi,
To make sure I understand the issue. In summary, the only difference here is the tree coloring in the clustermap and the dendrogram, right?

Update: I can see the problem now. Thanks.

**Comment by Glfrey** [comment]
Thanks @mr-eyes , let me know if you need anything from me.

**Comment by Glfrey** [comment]
Hi @mr-eyes,

I have identified the problem,  part of which was my fault ( I was missing the  `-labels` argument) and the other part was due to asymmetric handling of the `-labels` argument for the two plots. I've implemented a fix and opened a pull request.

**Comment by mr-eyes** [comment]
Thanks @Glfrey 
I will take a deeper look in a few days and update the issue.

**Comment by ctb** [comment]
ok, got it ;).

The problem is that the matrix plot is not observing the labels passed in by `--labeltext` without `--labels`, while the dendrogram plot _is_ observing those labels.

One fix (that would not be backwards compatible necessarily) is to force `args.labels` to True if `--labeltext` is provided.

Related, it seems to me that having `sourmash_fig.plot_composite_matrix` take both `show_labels` and `show_indices` is confusing...

**Comment by ctb** [comment]
To test this all out, examine the dendrogram and matrix output of the following commands:

1. `sourmash plot compare-demo` - labels on dendrogram, indices on matrix (BUG)

2. `sourmash plot compare-demo --labels` - labels on both dendrogram and matrix ✅ 

3. `sourmash plot compare-demo --indices` - labels on dendrogram, no indices on matrix (BUG)

4. `sourmash plot compare-demo --labels --indices` - labels on both ✅ 

#2790 fixes this behavior.
