### ISSUE TITLE
smol typo in sourmash prefetch help docs

### ISSUE THREAD

**Issue by jessicalumian** [sourmash-bio/sourmash#2709]
From the prefetch section, second paragraph of Caveats and Comments: https://sourmash.readthedocs.io/en/latest/command-line.html#sourmash-prefetch-select-subsets-of-very-large-databases-for-more-processing

A motivating use case for sourmash prefetch is to run it on multiple large databases with a metagenome query using --threshold-bp=0, --save-matching-hashes matching_hashes.sig, and --save-matches db-matches.sig, and then run sourmash gather matching-hashes.sig db-matches.sig.

In the first sentence, you have matching_hashes.sig, in the second it is matching-hashes.sig. Changing the first instance to use a - would be consistent with everything else!

**Comment by ctb** [comment]
Fixed in #2713!

**Comment by ctb** [comment]
@jessicalumian could you confirm that the new docs make sense? see #2713 header for direct links. thank you!
