### ISSUE TITLE
`SaveSignatures_Directory` writes 2x-compressed signatures

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2751]
In `save_load.py::SaveSignatures_Directory.add(...)`, the following code gzips already compressed JSON:
```
        with gzip.open(outname, "wb") as fp:
            sigmod.save_signatures([ss], fp, compression=1)
```

what is truly weird is that the Python layer can read these files just fine - it's only the pure Rust call to `Signature::from_path` that complains!?

Fix is easy, at least - just use `open` rather than `gzip.open`. But WTF??

**Comment by luizirber** [comment]
Probably the Python `gzip` module adapts to multiple gz headers, while the Rust code... doesn't. But yeah, the fix is to not do what the code is asking it to do (compress twice =P), and let `.save_signatures` do the compression

**Comment by ctb** [comment]
> Probably the Python `gzip` module adapts to multiple gz headers, while the Rust code... doesn't. But yeah, the fix is to not do what the code is asking it to do (compress twice =P), and let `.save_signatures` do the compression

Still don't quite understand where the ungz is being performed - I'm 99% sure it's in the rust code! - but I'm good with doing it right to begin with 😆
