### ISSUE TITLE
release notes for sourmash v4.8.4

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2759]
note to self: include link to pyo3_branchwater in the release notes :)

**Comment by ctb** [comment]
maybe also ask users to identify themselves so we can talk about who uses sourmash?

**Comment by ctb** [comment]
We are proud to release sourmash v4.8.4, now with even fewer bugs!

In addition to the patches and updates below, we would like to announce the availability of [branchwater](https://github.com/sourmash-bio/pyo3_branchwater), a sourmash plugin that supports **fast, low-memory, and multithreaded** search, compare, and gather operations. [branchwater v0.8.0](https://github.com/sourmash-bio/pyo3_branchwater/releases/tag/v0.8.0) is now available and is between 10 and 100 times faster and lower memory than sourmash. (However, it does not support all the sourmash features; that will come with time!) Please give it a try!

Last but not least, we would like to ask people who use sourmash regularly to [fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSePkHGaJqFSwiBZ9PwudV309fqQ6i9f9s4BVTBQpqXCuglJfw/viewform) so that we can include your information in some of our upcoming requests for funding support. Your use will not be made public but your support _will_ help us continue to develop sourmash!

On to the release notes for sourmash v4.8.4!

Bug fixes:

* fix exponential time explosion in `sig check` (#2762)
* fix duplicate md5 in picklist problem (#2747)
* avoid compressing sig files in directory output twice (#2752)

Developer updates:

* Remove BIGSI and SBT code (#2732)
* bump version to 4.8.4-dev (#2720)
* build: updates spun off mastiff PR (#2723)
* Build: Remove deprecated system_packages from readthedocs (#2740)
* build: remove specific tooling that breaks s390x (#2725)
* Add cargo deny and bump deps now that MSRV is 1.64 (#2724)

Dependabot updates:

* Bump serde_json from 1.0.105 to 1.0.106 (#2757)
* Bump actions/checkout from 2 to 4 (#2746)
* Bump supercharge/redis-github-action from 1.6.0 to 1.7.0 (#2745)
* Bump cachix/install-nix-action from 22 to 23 (#2744)
* Bump ouroboros from 0.17.2 to 0.18.0 (#2743)
* Bump chrono from 0.4.26 to 0.4.30 (#2755)
* Bump thiserror from 1.0.47 to 1.0.48 (#2742)
* Bump thiserror from 1.0.44 to 1.0.47 (#2730)
* Bump serde_json from 1.0.104 to 1.0.105 (#2731)
* Bump actions/upload-artifact from 1 to 3 (#2729)

**Comment by luizirber** [comment]
nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/255999

**Comment by luizirber** [comment]
pyodide PR: https://github.com/pyodide/pyodide/pull/4154

**Comment by luizirber** [comment]
spack PR: https://github.com/spack/spack/pull/40062

**Comment by ctb** [comment]
Release candidate testing:
- [x] Command line tests pass for a release candidate
- [x] All eight release candidate wheels are built

Releasing to PyPI:

- [x] RC tag(s)s deleted on github
- [x] Release tag cut
- [x] Release notes written
- [x] All eight release wheels built
- [x] Release wheels uploaded to pypi
- [x] tar.gz distribution uploaded to pypi

After release to PyPI and conda-forge/bioconda packages built:

- [x] [PyPI page](https://pypi.org/project/sourmash/) updated
- [x] Zenodo DOI successfully minted upon new github release - [see search results](https://zenodo.org/search?page=1&size=20&q=sourmash&sort=mostrecent)
- [x] `pip install sourmash` installs the correct version
- [x] [conda-forge sourmash-minimal-feedstock](https://github.com/conda-forge/sourmash-minimal-feedstock) has updated `sourmash-minimal` to the correct version 
- [x] `mamba create -n smash-release -y sourmash` installs the correct version

**Comment by ctb** [comment]
released!
