### ISSUE TITLE
reference databases don't seem accessible

### ISSUE THREAD

**Issue by jorondo1** [sourmash-bio/sourmash#2801]
Hi ! I'm trying to download the latest GTDB db for sourmash and can't seem to resolve. I tried curl -JLO as well as wget. Simply following the link show a forbidden access. Is something wrong or am I doing something wrong?

**Comment by ctb** [comment]
ugh, I'm so sorry, our file serving system (our campus HPC) is down through 10/11 😭

my apologies. I'll see if I can find a new place to put the files!

**Comment by bluegenes** [comment]
@jorondo1 they should be accessible now - please let us know if you have any further issues!

**Comment by jorondo1** [comment]
They are, thank you so much!
