### ISSUE TITLE
Creating signatures from multiple .fna files 

### ISSUE THREAD

**Issue by tasha99** [sourmash-bio/sourmash#2855]
Hello, 

I have the .fna files of over a thousand reference sequences that I am currently trying to creat signatures of. I currently have the following line of code, but my issue is that it is taking all of the reference sequence fna files, and producing only 1 signature file. Is there a way I can easily produce an individual signature file from each of the fna files?

sourmash sketch dna ./refseq/bactera/GCF_*/GCF_*.fna.gz -o ./p-syringae-ref-sigs/GCF_*.sig

Many thanks

**Comment by ctb** [comment]
Yep! Shortest answer:

```
sourmash sketch dna *.fna.gz
```

This will produce separate output .sig files for each .fna.gz input file.

## More explanation than you maybe wanted

The command you were running was actually producing multiple sketches, just in one signature file!

sourmash can happily make use of many sketches in one file, although it is typically something we do for databases than for queries.

### Examining files

You can examine a sourmash file like so:
```
sourmash sig summarize filename
```
and it will tell you if there is more than one sketch. Here is some example output for a file with three sketches in it:
```
path filetype: MultiIndex
location: 0.fa.sig
is database? no
has manifest? yes
num signatures: 3
** examining manifest...
total hashes: 12327
summary of sketches:
   1 sketches with DNA, k=21, scaled=1000             4036 total hashes
   1 sketches with DNA, k=31, scaled=1000             4168 total hashes
   1 sketches with DNA, k=51, scaled=1000             4123 total hashes
```

### Making efficient use of a file with many sketches inside

The biggest problem with a `.sig` file that contains many sketches is that sourmash has to load all of the sketches before it can do anything with any one of them. This is a failing of the `.sig` format and the way sourmash reads it.

If you had done:
```
sourmash sketch dna *.fna.gz -o output.zip
```
you would have gotten a zip file containing many different `.sig` files and this is something sourmash can work with efficiently. Moreover, you could use standard zip manipulation utilities to look at it.

(This is our currently recommend output format for multiple sketches in a single file.)

### Why oh why do we do things this way!?

We know it's confusing, but we allow multiple sketches in a single file for several reasons -

* if you have multiple sketches from the same input sequence, then you generally want those sketches in a single file. This is the original reason we supported it :).
* there are situations where people want to sketch hundreds or thousands of individual fasta sequences, in which case having one file containing many sketches is much easier than other approaches.
* for really large database collections, it's very nice to have a single compressed file to download and use! This is what the `.zip` format was designed for.

Hope this all helps & please let me know if you run into additional problems or have other questions!

**Comment by ctb** [comment]
You might also be interested in the branchwater plugin, `sourmash_plugin_branchwater`, which contains a command `manysketch` that is ...extremely fast. See [the docs](https://github.com/sourmash-bio/sourmash_plugin_branchwater/tree/main/doc).

Closing this for now!
