### ISSUE TITLE
consider running flake8 and automatically fixing

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2908]
per [review](https://github.com/pyOpenSci/software-submission/issues/129#issuecomment-1870572982)

>Flake8 revealed a lot of errors, it might not be the worst idea to run code through a linter and fix everything that can be automatically fixed, this may help with the unused imports as well. These are none critical but it helps.

**Comment by luizirber** [comment]
time for https://github.com/sourmash-bio/sourmash/pull/2427 to be updated?

**Comment by ctb** [comment]
I knew that PR was out there somewhere... yes, I think so. You up for it?

**Comment by luizirber** [comment]
Yup

**Comment by ctb** [comment]
bump! if it's easy...
