### ISSUE TITLE
add comparison / references to other packages to README

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#2911]
per [review](https://github.com/pyOpenSci/software-submission/issues/129#issuecomment-1870572982)

> If applicable, how the package compares to other similar packages and/or how it relates to other packages in the scientific ecosystem.

**Comment by bluegenes** [comment]
I think this checkbox specifically pertains to the README, though this could be useful in either/both places.

**Comment by ctb** [comment]
oh! oops.

ok, updated title. If you feel inspired, please post some text here and/or set up a PR - I'll get to it sooner or later if you don't 😆
