### ISSUE TITLE
Update docs: Threshold-bp and scaled relationship

### ISSUE THREAD

**Issue by ccbaumler** [sourmash-bio/sourmash#2929]
Update the [Faq](https://github.com/sourmash-bio/sourmash/blob/latest/doc/faq.md) after [What scaled values should I use with sourmash?](https://sourmash.readthedocs.io/en/latest/faq.html#id7) with "What threshold-bp should I use?".

This has been discussed in lab a few time over the last couple weeks and it may be relevant to others without direct lab access.

**Comment by ctb** [comment]
notes from talking with colton in person - 

3x the scaled value is a good default that limits false positives. But not yet published.

**Comment by ctb** [comment]
reference: https://github.com/sourmash-bio/sourmash/issues/2360
