### ISSUE TITLE
how to do group-to-group searches?

### ISSUE THREAD

**Issue by marade** [sourmash-bio/sourmash#2932]
As far as I can tell, sourmash supports one-to-all searches via 'search,' one-to-group searches via 'search --picklist,' and all-to-all searches via 'compare,' but what about group-to-group searches, e.g. something like this:

sourmash search --picklist mylist.csv -o results.csv queries.sbt.zip targets.sbt.zip

As I understand it currently one cannot supply multiple queries at once, forcing a reload of targets.sbt.zip for each single query, yes? My use case is actually more simple, a group-to-all scenario where I don't need a subgroup of the targets, so more like this:

sourmash search -o results.csv queries.sbt.zip targets.sbt.zip

Is that possible somehow? Thanks.

**Comment by ctb** [comment]
sourmash itself doesn't support that directly, I don't think, but you might be interested in the branchwater plugin which supports this quite well - see commands `multisearch` and `manysearch`. https://github.com/sourmash-bio/sourmash_plugin_branchwater

It doesn't support SBT inputs, note.

**Comment by marade** [comment]
Ah, that looks promising. I reckon the Rust speed-ups will help compensate for whatever performance I'm losing not using SBTs. Thanks. I'll reopen this if needed, but hopefully I can navigate the plugin.
