### ISSUE TITLE
fasterq-dump is broken? was: Sketching at `1k` then downsampling to `10k` is different from sketching at 10k

### ISSUE THREAD

**Issue by mr-eyes** [sourmash-bio/sourmash#2941]
**Reproduce:**

```bash
aws s3 cp --quiet --no-sign-request s3://sra-pub-run-odp/sra/SRR7107867/SRR7107867 SRR7107867.sra

fasterq-dump --stdout --skip-technical --fasta-unsorted --threads 8 --bufsize 1000MB --curcache 10000MB --mem 5000 SRR7107867.sra | sourmash sketch dna -p k=51,scaled=10000,abund - -o scale_10k.sig

fasterq-dump --stdout --skip-technical --fasta-unsorted --threads 8 --bufsize 1000MB --curcache 10000MB --mem 5000 SRR7107867.sra | sourmash sketch dna -p k=51,scaled=1000,abund - -o scale_1k.sig

sourmash signature downsample -q scale_1k.sig  --scaled 10000 -k 51 -o down_10k_scale_1k.sig

```

---

`sig describe`

```bash
signature filename: scale_10k.sig
signature: ** no name **
source file: ** no name **
md5: 73d2e50512717737245c4892e56843ec
k=51 molecule=DNA num=0 scaled=10000 seed=42 track_abundance=1
size: 661644
sum hashes: 3490622
signature license: CC0

signature filename: down_10k_scale_1k.sig
signature: ** no name **
source file: ** no name **
md5: 469d8b903df0f17a087f30c5ee6fbcfe
k=51 molecule=DNA num=0 scaled=10000 seed=42 track_abundance=1
size: 645846
sum hashes: 3402668
signature license: CC0
```

**Comment by mr-eyes** [comment]
I am unsure if this is an expected behavior or a bug. But I was expecting them to be the same.

**Comment by mr-eyes** [comment]
I may also suspect inconsistent dumping from the SRA file. I should dump to on-disk fasta first, then redo the sketching.

**Comment by ctb** [comment]
they should be identical. It's a huge problem if they're not ;)

**Comment by mr-eyes** [comment]
> they should be identical. It's a huge problem if they're not ;)

After sketching directly from the FASTA file, I found that they are identical. 
I don't know how the SRA dumping can cause this inconsistency, but it's good information to know.

**Comment by ctb** [comment]
> I don't know how the SRA dumping can cause this inconsistency, but it's good information to know.

ITYM "it's terrifying"?

cc @luizirber

**Comment by mr-eyes** [comment]
> ITYM "it's terrifying"?


Exactly...
I am no longer sure about the reproducibility of my snakemake workflows, relying on SRA formats, downloading>>dumping>>sketching.

**Comment by mr-eyes** [comment]
More checks:

- [x] FASTA checksum another dump of the same sra dump command.
- [ ] sketch by streaming the fasta file to assert same results as sketching the fasta file.

**Comment by mr-eyes** [comment]
For records:
After sketching directly from the fasta file (loading the file, not streaming):

**This gave different results from the first streaming-based sketching.**

```
signature filename: 10k_SRR7107867.sig
signature: ** no name **
source file: SRR7107867.fasta
md5: 5b4b5909bb761b1683f0888857be9a34
k=51 molecule=DNA num=0 scaled=10000 seed=42 track_abundance=1
size: 640282
sum hashes: 3369834
signature license: CC0

signature filename: down_10k_1k_SRR7107867.sig
signature: ** no name **
source file: SRR7107867.fasta
md5: 5b4b5909bb761b1683f0888857be9a34
k=51 molecule=DNA num=0 scaled=10000 seed=42 track_abundance=1
size: 640282
sum hashes: 3369834
signature license: CC0
```

**Comment by mr-eyes** [comment]
More questions:

1- If something went wrong while dumping the FASTA from sra to sourmash, sourmash will stop creating the signature?

**Comment by mr-eyes** [comment]
🐛 🐛 🐛 🐛 🐛 🐛 🐛 🐛 🐛 


Dumping command: `fasterq-dump --skip-technical --fasta-unsorted --threads 8  --bufsize 1000MB --curcache 10000MB --mem 5000 SRR7107867.sra  --outfile $FASTAOUT`

**First dumping:**
```
spots read      : 362,839,714
reads read      : 701,045,366
reads written   : 701,045,366
```

---

**second dumping**
```
spots read      : 362,839,714
reads read      : 725,679,428
reads written   : 725,679,428
```

---

```
-rw-rw-r-- 1 mhussien ctbrowngrp 101341885438 Jan 23 11:08 SRR7107867.fasta
-rw-rw-r-- 1 mhussien ctbrowngrp 104868137974 Jan 23 14:27 dumping2_SRR7107867.fasta
```

**Comment by ctb** [comment]
I'm sorry what??

**Comment by luizirber** [comment]
> More questions:
> 
> 1- If something went wrong while dumping the FASTA from sra to sourmash, sourmash will stop creating the signature?

No. sourmash has no way of knowing that, since it's coming from the pipe, and the pipe is a shell feature. I'm pretty sure `fasterq-dump` just stop sending data, but has no way to communicate to next process that something went wrong.

I try to be [conservative in `wort`](https://github.com/sourmash-bio/wort/blob/09d6ee552c85360fdc60e9d59e2fc757c2c6dd99/wort/blueprints/compute/tasks.py#L38-L61):
- run `fastq-dump` without multithreading
- set `-o pipefail` in bash
- capture and ignore [`SIGPIPE`](http://www.pixelbeat.org/programming/sigpipe_handling.html) error, because it is a warning that a process was closed

and with this is should still error out if `fastq-dump` ends early. :crossed_fingers: 

so: do you get different data even with `fastq-dump`?

**Comment by mr-eyes** [comment]
Yes, I greatly suspect the multi-threading. I will try the conservative approach and post the results.

**Comment by mr-eyes** [comment]
fasterq basic command w/o threads: (more to follow)


`fasterq-dump --skip-technical --fasta-unsorted  SRR7107867.sra  --outfile fasterqdump_skiptechnical_fastaunsorted_SRR7107867.fasta`

```
spots read      : 362,839,714
reads read      : 698,086,602
reads written   : 698,086,602
```

Same command, another dump

`fasterq-dump --skip-technical --fasta-unsorted  SRR7107867.sra  --outfile dump2_fasterqdump_skiptechnical_fastaunsorted_SRR7107867.fasta`

```
spots read      : 362,839,714
reads read      : 725,679,428
reads written   : 725,679,428
```

**Comment by mr-eyes** [comment]
`fasterq-dump --fasta  SRR7107867.sra  --outfile fasterqdump_fasta_SRR7107867.fasta`

```
spots read      : 362,839,714
reads read      : 725,679,428
reads written   : 725,679,428
```

---

`fasterq-dump --fasta  SRR7107867.sra  --outfile dump2_fasterqdump_fasta_SRR7107867.fasta`

```
spots read      : 362,839,714
reads read      : 725,679,428
reads written   : 725,679,428
```

---

`fastq-dump --skip-technical --fasta SRR7107867.sra  --stdout > fastqdump_skiptechnical_fasta_SRR7107867.fasta`

```
Read 362839714 spots for SRR7107867.sra
Written 362839714 spots for SRR7107867.sra

file                                            format  type     num_seqs         sum_len  min_len  avg_len  max_len
fastqdump_skiptechnical_fasta_SRR7107867.fasta  FASTA   DNA   362,839,714  72,200,025,902        2      199      200
```

**Comment by rchikhi** [comment]
Can't reproduce it locally (using a Sept 2023 build of `fasterq-dump`) when `prefetch`'ing the file. I always get the right number of reads. This is a aligned SRA file, it pulls references from RefSeq if they're not present locally. When you `prefetch` the accession rather than to `aws s3 cp`, it will also download the RefSeq references. Perhaps download errors during `fasterq-dump` were the cause of inconsistencies?

**Comment by mr-eyes** [comment]
> Can't reproduce it locally (using a Sept 2023 build of `fasterq-dump`) when `prefetch`'ing the file. I always get the right number of reads. This is a aligned SRA file, it pulls references from RefSeq if they're not present locally. When you `prefetch` the accession rather than to `aws s3 cp`, it will also download the RefSeq references. Perhaps download errors during `fasterq-dump` were the cause of inconsistencies?

Hey Rayan, I downloaded the SRA file and then dumped it multiple times with the command mentioned. So, there is no fetching from the remote.

```
aws s3 cp --quiet --no-sign-request s3://sra-pub-run-odp/sra/SRR7107867/SRR7107867 SRR7107867.sra

fasterq-dump --stdout --skip-technical --fasta-unsorted --threads 8 --bufsize 1000MB --curcache 10000MB --mem 5000 SRR7107867.sra > test1.fa
fasterq-dump --stdout --skip-technical --fasta-unsorted --threads 8 --bufsize 1000MB --curcache 10000MB --mem 5000 SRR7107867.sra > test2.fa
```

Sketching both files (might) give unidentical sketches does not have to happen every time.

**Comment by rchikhi** [comment]
With SRA aligned files, even if you download the `.sra` file locally, the download job is not done. `fasterq-dump` stealthly downloads missing references because they are never packaged in the `.sra` file. This is little-known. Using `prefetch` avoids this by also prefetching references. With `fasterq-dump` it is unclear to me if reference then forever remain in your local nbci cache directory or if this is dependent on a particular `vdb-config` setting.

**Comment by rchikhi** [comment]
I guess what I'm saying, it would be good to reproduce this sort of bug in a non-aligned SRA file to isolate the problem.
