### ISSUE TITLE
adjust `Cargo.toml` to ensure `sourmash_plugin_branchwater` compatibility

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/sourmash#2944]
Note that for `sourmash_plugin_branchwater` compatibility, we need:

- `byteorder` = "1.4.3"
- `wasm-bindgen` = "0.2.89"
- `once_cell` = "1.18.0"
- `chrono` = `0.4.32`

we could pin to these exactly (`==`? )to prevent dependabot updates

**Comment by ctb** [comment]
two notes:

* this needs to be done in `src/core/Cargo.toml`
* there seems to be no simple way to "pin" this with respect to dependabot specifically, or Rust tests generally. So barring magic ✨ that @luizirber knows about, we simply need to keep an eye out for these.

Actually... I wonder if we could just specify `<=`? That seems dangerous tho. Or maybe

```
byteorder >= "1.4.3",<="1.4.3"
```

**Comment by ctb** [comment]
turns out there's a way to set "ignore" on certain packages - just had to find the right search string, "how can I prevent dependabot from upgrading specific packages"

**Comment by mr-eyes** [comment]
> turns out there's a way to set "ignore" on certain packages - just had to find the right search string, "how can I prevent dependabot from upgrading specific packages"

[dependabot ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#:~:text=%23%20Use%20%60ignore%60%20to%20specify%20dependencies%20that%20should%20not%20be%20updated)?
Update: Sorry, just realized you [applied it](https://github.com/sourmash-bio/sourmash/pull/3065#issue-2170013696), not looking for it.
