### ISSUE TITLE
Error with 'sourmash tax genome' command

### ISSUE THREAD

**Issue by agombolay** [sourmash-bio/sourmash#3253]
I would like to run `sourmash tax genome` using the CSV file generated from `fastgather` rather than `gather`. However, when I run `sourmash tax genome` with the fastgather CSV, I receive the following error message:

`sourmash tax genome --gather-csv sample.fastgather.csv --taxonomy-csv gtdb-rs214.lineages.csv.gz --output-dir sourmash_output` 
Error Message: ERROR: 'sample.fastgather.csv' is missing columns needed for taxonomic summarization.

**Comment by ctb** [comment]
hi @agombolay thanks for reporting!

could you please share the headers for your `sample.fastgather.csv` file (`head -1 sample.fastgather.csv`) as well as the output of `sourmash info -v`? thanks!

**Comment by agombolay** [comment]
Headers: query_filename,rank,query_name,query_md5,match_name,match_md5,intersect_bp

== This is sourmash version 4.8.8. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

sourmash version 4.8.8
- loaded from path: /path/.conda/envs/sourmash/lib/python3.12/site-packages/sourmash/cli

khmer version: None (internal Nodegraph)

screed version 1.1.3
- loaded from path: /path/.conda/envs/sourmash/lib/python3.12/site-packages/screed

the following plugins are installed:

plugin type          from python module             v     entry point name
-------------------- ------------------------------ ----- --------------------
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 manysearch
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 multisearch
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 fastgather
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 fastmultigather
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 index
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 check
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 manysketch
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 pairwise
sourmash.cli_script  sourmash_plugin_branchwater    0.9.3 cluster

**Comment by ctb** [comment]
yep! The `fastgather` and `fastmultigather` output was finally made completely compatible with sourmash in sourmash_branchwater_plugin v0.9.5, and you have v0.9.3. So you'll need to update that! You should also consider updating sourmash to v4.8.10, although I think that is not required.

related issues:
* https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/331#issuecomment-2177630339

**Comment by agombolay** [comment]
Updating the versions worked for me! Thanks!

**Comment by ctb** [comment]
great, thank you for confirming!!!
