### ISSUE TITLE
ahash cyclic dependence with the js feature for getrandom crate

### ISSUE THREAD

**Issue by jianshu93** [sourmash-bio/sourmash#3263]
Dear sourmash team, 

When use sourmash as a library dependency, the js feature from get random is enabled by default and cause this error:

error: cyclic package dependency: package `ahash v0.8.11` depends on itself. Cycle:
package `ahash v0.8.11`
    ... which satisfies dependency `ahash = "^0.8.7"` of package `hashbrown v0.14.5`
    ... which satisfies dependency `hashbrown = "^0.14.1"` of package `indexmap v2.2.6`
    ... which satisfies dependency `indexmap = "^2.2.3"` of package `serde_json v1.0.120`
    ... which satisfies dependency `serde_json = "^1.0"` of package `wasm-bindgen v0.2.92`
    ... which satisfies dependency `wasm-bindgen = "^0.2.92"` of package `js-sys v0.3.69`
    ... which satisfies dependency `js-sys = "^0.3"` of package `getrandom v0.2.15`
    ... which satisfies dependency `getrandom = "^0.2.7"` of package `ahash v0.8.11`

https://github.com/tkaitchuck/aHash/issues/95#issuecomment-881152315, see also discussion here. Ahash is a widely used hash library for many other crates this is why we see the error. Since the wasm feature of sourmash is not enabled by default, the js feature is also not needed I think? I disabled the js from getrandom crate in Cargo.toml and it worked. A solution related to wasm-bingen is also provided: https://github.com/tkaitchuck/aHash/issues/95#issuecomment-1937448134, maybe also this solution. Not sure about it. 

Can you please check and update the sourmash crate on crates.io?

Thanks,

Jianshu

**Comment by luizirber** [comment]
Thanks for the info, @jianshu93!

`ahash` is turning into quite a problematic indirect dependency, it also affected the [emscripten-forge](https://github.com/emscripten-forge/recipes/pull/288 package PR) and was fixed in https://github.com/sourmash-bio/sourmash/pull/3243 (still need to do a Python release for it).

#3250 is bumping the Rust crate to 0.15.0, will work on releasing it to crates.io this weekend

**Comment by luizirber** [comment]
@jianshu93 can you try with
```
sourmash = { git = "https://github.com/sourmash-bio/sourmash.git", branch = "lirber/rocksdb_storage", features = ["branchwater"] }
```
in your `Cargo.toml` to see if the problem still happen?

**Comment by jianshu93** [comment]
hi @luizirber,

It worked but for me, build the lib rocksdb_storage took much longer and the binary size is also much larger. Is the js feature from getrandom necessary for the database storage features? Is there a possibility to make it optional in this case.

Thanks,
Jianshu

**Comment by luizirber** [comment]
oh, yes, you don't need the `features = ["branchwater"]` bit if you're not using the rocksdb stuff, forgot to take it out :sweat:

**Comment by jianshu93** [comment]
It worked and is fast now to build! Thanks. I will use the v0.15.0 on crates.io when you publish it this weekend. 

Jianshu

**Comment by luizirber** [comment]
https://crates.io/crates/sourmash/0.15.0 released!

Thanks again for reporting the problem and pointing to the solution =]

**Comment by jianshu93** [comment]
Thank you so much!
