### ISSUE TITLE
HLL/MLE estimator bug

### ISSUE THREAD

**Issue by LucaCappelletti94** [sourmash-bio/sourmash#3295]
Hi - the [first unwrap in the MLE method](https://github.com/sourmash-bio/sourmash/blob/bc2297050b6db10b144916700b4550ec50b26a8f/src/core/src/sketch/hyperloglog/estimators.rs#L22) will crash the library in some (yet not understood) cases. I just found this out while running some benchmarks on about 100k random sets, so I am not yet sure of the cause. Will try to fix it if I can, but I thought it important to let you guys know about the problem.

https://github.com/sourmash-bio/sourmash/blob/bc2297050b6db10b144916700b4550ec50b26a8f/src/core/src/sketch/hyperloglog/estimators.rs#L16-L31

**Comment by LucaCappelletti94** [comment]
It started to happen at precision 16, precisions 4 to 15 work fine.

**Comment by LucaCappelletti94** [comment]
Oh, I understand - with 2^16 or more registers, the type you are using for the multiplicities just won't do. I'll be fixing that shortly.

**Comment by luizirber** [comment]
Fixed in #3296, thanks again @LucaCappelletti94!
