### ISSUE TITLE
Upgrading old data

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#447]
Rebuilding the SBT (like in #446) might be expensive, and most of the times the underlying data doesn't change, only the JSON file describing the SBT. Add a command (`sourmash sbt upgrade`?) to bring an older SBT to the latest version.

This also works for signatures (`sourmash sig upgrade`?), since we dropped support for the old YAML sigs and there is no clear path on how to use them now...

**Comment by ctb** [comment]
#1059 makes it possible to build a new SBT from an old database, but it doesn't really address the expense issue. On the other hand, building our databases doesn't seem to be very expensive any more, either!

**Comment by ctb** [comment]
Closing as obsolete.
