### ISSUE TITLE
Create a new "old DBs" section on the docs, to keep track of where they are

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#487]
Every time we updated the "Prepared DBs" section we removed the old links and added new ones. Maybe create another page and move old links there, instead of removing them?

**Comment by ctb** [comment]
why keep old links?

**Comment by luizirber** [comment]
Maybe we don't need the old links, but there is the question of what to do with old DBs. Keep them on S3? Remove them?

**Comment by ctb** [comment]
Separate but related - an idea that came up in discussion with Jason Stajich, it'd be handy to have a machine-readable (JSON? YAML?) file of available databases, that was kept up to date in some standard location. That way we and others could programmatically check to see what databases are available for download, etc.

**Comment by ctb** [comment]
ref #1005

**Comment by ctb** [comment]
fixed in https://github.com/sourmash-bio/sourmash/pull/1581.
