### ISSUE TITLE
Would sourmash lca classify be a good tool to distinguish 16s from 18s?

### ISSUE THREAD

**Issue by jcmcnch** [sourmash-bio/sourmash#548]
Hi Titus,

I've got some mixed amplicon libraries that contain both prokaryotic and eukaryotic sequences. We have to first separate them into 16S and 18S pools because they cannot be analyzed with the same pipeline. I was thinking that the sourmash LCA classify tool might be good for this purpose as it would presumably be faster than BLAST or similar algorithms. I noticed that you mentioned 16S as a potential emerging use case for sourmash and was wondering if you think it might work well in this case? Thanks in advance for your help,

Jesse

**Comment by ctb** [comment]
hi @jcmcnch sorry for never answering :(. Please see https://github.com/sourmash-bio/sourmash/issues/1421#issuecomment-864439542 for an up-to-date perspective... happy to chat more if you're ever interested!

**Comment by ctb** [comment]
(Err, and the answer is "yes, I would guess so", but we don't know :)

**Comment by jcmcnch** [comment]
No worries Titus, I ended up using bbsplit with curated subsets of SILVA for this in the end. Hope all is well.
