### ISSUE TITLE
move SBT to database

### ISSUE THREAD

**Issue by phiweger** [sourmash-bio/sourmash#645]
hi @luizirber 

I haven't checked for a while -- what is the current status of not having to load the "raw" SBT into memory and instead have a database/ key-value store handle it?

thanks a lot,
Adrian

**Comment by phiweger** [comment]
I've come across #648 -- can you point me to any code/ examples on how to load the SBT given a zipped index?

**Comment by luizirber** [comment]
Hi @phiweger!

I never did a full run, but we have Redis tests working on every PR. I think the workflow would be 
```bash
$ sourmash storage convert -b redis genbank-k2-d21.sbt.json
$ sourmash search query.sig genbank-k2-d21.sbt.json
```

as for #648, I compressed all the internal nodes and signatures to bzip2 and then created a Zip file (just storing, no compression), and put the `.sbt.json` file inside as `tree.sbt.json`. I will try to write more docs for it soon, but the main issue is that it was slower in my tests (even though `Zipfile` supports random access, it is not as fast as reading files from a hidden dir)

**Comment by phiweger** [comment]
I'll give `sourmash storage convert` a try, thanks!

**Comment by phiweger** [comment]
@luizirber what would be the workflow for the zip storage?

Furthermore, does it allow parallel read access? Like I want to query the SBT in parallel, it this supported?

Thanks a lot!

**Comment by ctb** [comment]
I'm going to close this because the underlying use case is not clear, we've moved quite a bit from SBTs to other faster approaches, and I don't think there's anywhere to go from this issue specifically :)
