### ISSUE TITLE
Bring in ANGUS tutorial to docs

### ISSUE THREAD

**Issue by luizirber** [sourmash-bio/sourmash#698]
... or at least point to it:
https://angus.readthedocs.io/en/2019/sourmash.html

**Comment by erikyoung85** [comment]
So I'm finally getting started on this issue, but im not exactly sure how the docs system work. Would the way to add this tutorial to docs be to add a .md file in the docs folder? Then maybe add a line with a link to that file in the tutorials.md file? Also quick question: does "point to it" mean just add a link to the website? Or something completely different.

**Comment by ctb** [comment]
On Sun, Jul 19, 2020 at 12:46:27PM -0700, Erik Young wrote:
> So I'm finally getting started on this issue, but im not exactly sure how the docs system work. Would the way to add this tutorial to docs be to add a .md file in the docs folder? Then maybe add a line with a link to that file in the tutorials.md file? Also quick question: does "point to it" mean just add a link to the website? Or something completely different.

I think add md file to docs folder, then add a link that file in tutorials.md.

--t
