### ISSUE TITLE
add GTDB databases to docs

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#816]
http://ivory.idyll.org/blog/2019-sourmash-lca-db-gtdb.html etc

**Comment by ctb** [comment]
well, we probably want to post GTDB .sbt.zip and lca.json.gz with k=21, 31, and 51... gotta check to see if I have all of those built.

**Comment by ctb** [comment]
https://osf.io/wxf9z/

**Comment by mikemc** [comment]
Any plans to add the July GTDB release, v95?

**Comment by ctb** [comment]
we'll get there soon - no specific plans, however!

**Comment by ctb** [comment]
hi @mikemc nucleotide databases for release 95 are here,

https://osf.io/wxf9z/files/

k=21, k=31, and k=51 databases are available. The links should be permalinks.

**Comment by mikemc** [comment]
Thanks! I ended up making my own mash sketches once I realized that these are just using the GTDB representative genomes and not the full ~200K genome set, which I wanted for screening. But I hope to try sourmash out with these eventually.

**Comment by mikemc** [comment]
Thanks!

**Comment by ctb** [comment]
closed by #1581.
