### ISSUE TITLE
Use underscores instead of directory structure to define CLI nesting

### ISSUE THREAD

**Issue by standage** [sourmash-bio/sourmash#827]
In [this comment](https://github.com/dib-lab/sourmash/pull/785#issuecomment-570922418), @ctb suggests that we use filename prefixes rather than directories to group related subcommands into submodules: `lca_index.py` instead of `lca/index.py`.

Note: this will be tricky if we allow underscores in command names, such as `import_csv` or `sbt_combine`. The latter could be addressed by adding an SBT submodule—reading #177 and #785 as an interloper, there may or may not be broad interest in this from the core contributors.

**Comment by ctb** [comment]
I like the directory structure nowadays, no reason to rock the boat.
