### ISSUE TITLE
Add an FAQ?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash#932]
It would be nice to transfer information from issues into the sourmash docs. Maybe a lightweight way to do this is with an FAQ?

[#908 Should I expect identical result after rescale?](https://github.com/dib-lab/sourmash/issues/908) would be good one to start things off.

**Comment by luizirber** [comment]
Maybe checking the [question](https://github.com/dib-lab/sourmash/issues?q=label%3Aquestion+) label too.

(and also start labeling more issues with `question` =P)

**Comment by ctb** [comment]
note 'faq' labelled issues: https://github.com/dib-lab/sourmash/labels/faq

**Comment by ctb** [comment]
suggestions from @bluegenes -

1. What is FracMinHash and how does it differ from MinHash?
2. When do you use Containment vs. Jaccard for FracMinHash sketch
comparisons
3. How does Containment enable metagenome comparisons?
4. What is cANI (containment ANI)?
5. Is sourmash the same as Mash?
A: (slightly tongue-in-cheek): No - you can find the mash folks over here:
(their documentation). See also, #1 (How does FracMinHash differ from       
MinHash)
6. What version should I install?
A: If installing for the first time, always choose our latest release from      
bioconda or pip! We follow standard semantic versioning, so you can freely      
upgrade across minor versions without any functionality changes (except
improvements, additions, and bug fixes)!
7. You didn't answer my question! Is there a place I can ask?
A: Yes! Find us on the sourmash gitter here (link) or the sourmash issue
tracker (link)!
